Add parquet nanosecond support
rapidsai/cudf pull request #10063
Opened 2022-01-17 23:00 UTC by PointKernel

Closes https://github.com/rapidsai/cudf/issues/9393

TBD

2022-03-14 10:17 UTC, devavret requested changes
Looks good. Only one blocking concern about statistics.

2022-03-14 16:01 UTC, PointKernel commented on cpp/src/io/parquet/reader_impl.cu
> +  if (logical_type.isset.TIMESTAMP) {
How about replacing this line with:
```cpp
if (inferred_converted_type == parquet::UNKNOWN and physical == parquet::INT64) {
```
`inferred_converted_type` is the return of `logical_type_to_converted_type` and `physical == parquet::INT64` can guarantee int96 timestamps won't be affected.

2022-03-15 19:00 UTC, PointKernel commented on cpp/src/io/parquet/writer_impl.cu
> +      col_schema.ts_scale = -1000;  // negative value indicates division by absolute value
The current implementation fails statistics tests for int96 timestamp types. Filed https://github.com/rapidsai/cudf/issues/10438 to track this issue.

2022-03-16 16:39 UTC, PointKernel commented
@vuule requesting your review as well. 
I've touched the common statistics calculation by adding an `int96_timestamps` argument. It's used to distinguish the `int96` and `int64` conversion map where `int96` nanoseconds are converted to microseconds but not `int64`.

2022-03-18 01:10 UTC, vuule requested changes
Looks great, especially changes to compact protocol RW.
Couple of nitpicks and a suspected bug:

2022-03-18 01:10 UTC, vuule commented on cpp/src/io/parquet/reader_impl.cu
> +    if (logical_type.TIMESTAMP.unit.isset.NANOS) {
```suggestion
  if (inferred_converted_type == parquet::UNKNOWN and physical == parquet::INT64 and logical_type.TIMESTAMP.unit.isset.NANOS) {
```

2022-03-18 18:08 UTC, PointKernel commented on cpp/src/io/statistics/statistics.cuh
> + * Copyright (c) 2019-2022, NVIDIA CORPORATION.
Right, I was intended to correct the copyright year because `2019-20` is definitely not what we want. Should I revert this change?

2022-03-18 18:11 UTC, vuule commented on cpp/src/io/statistics/statistics.cuh
> + * Copyright (c) 2019-2022, NVIDIA CORPORATION.
it's fine
I didn't pay attention to the content here

2022-03-18 18:36 UTC, PointKernel commented on cpp/src/io/statistics/column_statistics.cuh
> +    if (not int96_timestamps) {
Can you be more specific? There is an else branch to handle `int96_timestamps` statistics calculation from line 270 to 275.

2022-03-18 19:56 UTC, PointKernel commented on cpp/src/io/statistics/column_statistics.cuh
> +    if (not int96_timestamps) {
Thanks for catching this bug. Corrected.

2022-03-18 20:32 UTC, vuule approved these changes

2022-03-21 06:32 UTC, devavret commented on cpp/src/io/parquet/reader_impl.cu
> +  if (logical_type.isset.TIMESTAMP) {
I meant something more on the lines of
```
if (logical type == X or converted type == x) {
  // Do what you would've done in the switch case
} else if (logical type == Y or converted type == y) {
...
```
But maybe out of scope for this PR.

2022-03-21 06:32 UTC, devavret approved these changes

2022-03-21 13:30 UTC, karthikeyann approved these changes

2022-03-21 13:38 UTC, PointKernel commented on cpp/src/io/parquet/reader_impl.cu
> +  if (logical_type.isset.TIMESTAMP) {
Thanks for clarifying. I will leave this to a future PR.

2022-03-21 13:39 UTC, merged