Add CMake `install` rule for tests
rapidsai/cudf pull request #10190
Opened 2022-02-02 16:33 UTC by ajschmidt8

This PR adds a CMake `install` rule for test targets. This step is a prerequisite to being able to package tests in their own `conda` package, which will enable us to deprecate _Project Flash_.

2022-02-02 17:12 UTC, ttnghia approved these changes
Approval, pending cmake-style fix.

2022-02-02 18:23 UTC, robertmaynard requested changes
We need to also change the tests to have a `INSTALL_RPATH` target property of `"\$ORIGIN/../lib"` so that they can be run after installation.

```diff
--- a/cpp/tests/CMakeLists.txt
+++ b/cpp/tests/CMakeLists.txt
@@ -22,7 +22,9 @@ function(ConfigureTest CMAKE_TEST_NAME)
   set_target_properties(
     ${CMAKE_TEST_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY
                                   "$<BUILD_INTERFACE:${CUDF_BINARY_DIR}/gtests>"
+                                  INSTALL_RPATH "\$ORIGIN/../lib"
   )
+

```

2022-02-02 18:50 UTC, robertmaynard approved these changes

2022-02-07 14:07 UTC, robertmaynard approved these changes

2022-02-07 20:37 UTC, ajschmidt8 commented
@gpucibot merge

2022-02-07 20:37 UTC, merged