Create a dispatcher for invoking regex kernel functions
rapidsai/cudf pull request #10349
Opened 2022-02-23 20:18 UTC by davidwendt

Closes #10138 

Refactor the various regex function calls to use a dispatcher instead of if-else clauses. Each regex call currently requires different stack sizes (and later launch parameters). Changes to these parameters are sometimes difficult to coordinate since they usually need to be duplicated across about 10 APIs that are currently using regex calls. The new `regex_dispatcher` makes calling these much cleaner and easier to maintain. This will be helpful when experimenting with possibly using different launch parameters.

No functions have changed. Mostly this is a refactoring and cleanup effort. The `findall.cu` was also recoded to use the new `count_matches` utility.

2022-02-25 19:04 UTC, vyasr approved these changes
A few minor suggestions, but no blockers. LGTM!

2022-02-25 19:04 UTC, vyasr commented on cpp/src/strings/contains.cu
> +  bool const bmatch{false};  // do not make this a template parameter to keep compile times down
Ah never mind. I see that it is not always const but is in fact always provided on construction. Is there value to providing a default here, or should the user always have to initialize it?

2022-02-28 15:05 UTC, davidwendt commented on cpp/src/strings/replace/multi_re.cu
> +  reprog_device* max_prog = nullptr;  // keep track of the largest one
I think you are right. This could be broken up to use `std::transform` and `std::max_element`. Slightly verbose but definitely more clear.

2022-03-01 16:12 UTC, cwharris approved these changes

2022-03-01 16:15 UTC, davidwendt commented on cpp/src/strings/contains.cu
> - * Longer patterns require global memory.
It is, just not here anymore. I moved it to the regex/dispatcher.hpp doxygen.

2022-03-01 17:02 UTC, bdice requested changes
This is awesome! Cleans up a lot of code. I have a few suggestions.

2022-03-01 17:42 UTC, davidwendt commented on cpp/src/strings/regex/dispatcher.hpp
> +#include <strings/regex/regex.cuh>
The include is needed for calling the `d_prog.insts_count()` member function as well as referencing the `RX_` values. The member function is declared as `host/device`. The `RX_` values are needed exclusively for calling the member functions declared in `regex.cuh`.

I don't think a header file should be declared as `.cuh` unless it actually has device functions defined in it. We have a few places where including a `.cuh` in a `.hpp` or `.cpp` is unavoidable (`iterator.cuh` comes to mind) but those cases only call host or host/device functions.

2022-03-01 17:42 UTC, davidwendt commented on cpp/src/strings/search/findall.cu
> +      epos = d_str.byte_offset(epos);  // to bytes
Sigh. I really like this style and use it whenever I can.

2022-03-01 17:51 UTC, davidwendt commented on cpp/src/strings/contains.cu
> +                              : -1;  // this handles empty strings too
I fixed the 2nd comment. I feel an inline comment here is better than trying to explain this in a comment above this line. Let me know what you think.

2022-03-01 22:12 UTC, bdice commented on cpp/src/strings/contains.cu
> +                              : -1;  // this handles empty strings too
The fix here is clearer, thank you!

2022-03-01 22:13 UTC, bdice commented on cpp/src/strings/regex/dispatcher.hpp
> +#include <strings/regex/regex.cuh>
Thanks for the explanation.

> I don't think a header file should be declared as `.cuh` unless it actually has device functions defined in it.

This seems consistent with some other examples, upon further inspection.

2022-03-01 22:14 UTC, bdice approved these changes

2022-03-02 11:15 UTC, rgsl888prabhu approved these changes

2022-03-02 15:52 UTC, merged