Remove _getattr_ method in RangeIndex class
rapidsai/cudf pull request #10538
Opened 2022-03-29 23:46 UTC by skirui-source

This PR is partial fix in efforts to reduce implicit conversions to minimize unnecessary column materialization ( PR https://github.com/rapidsai/cudf/issues/9593).

Replaces https://github.com/rapidsai/cudf/pull/10388

@vyasr comment: Currently RangeIndex implicitly defers all methods that aren't implemented to Int64Index via the __getattr__ override. We should remove this override and actually implement the relevant methods in RangeIndex. In cases where materializing an Int64Index is necessary, we should exploit the sort of monkey-patching that we do for defining unary and binary operations for RangeIndex to add those methods explicitly. In other words, we should use an allowlist rather than a blocklist to choose methods where the conversion happens.

2022-05-18 20:32 UTC, vyasr reviewed
I see at least two methods that could be implemented without using `_values`. Let me know if you need some hints!

2022-05-18 20:32 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._values.distinct_count(dropna=dropna)
Can you think of a faster way to implement this method?

2022-05-18 20:32 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._values.to_arrow()
Can you think of a way to implement this method without using `_values`?

2022-05-19 18:40 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._stop  # or len(self)
Does `len(self)` always equal `self._stop`? What happens if you test it on something like `cudf.RangeIndex(9, 10)`?

2022-05-19 18:40 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._stop  # or len(self)
I'm guessing that this method is being called indirectly through some other test, but is not being tested directly so I would recommend adding that.

2022-05-19 18:41 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._stop - 1
What happens if `self._step != 1`?

2022-05-19 18:42 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._start
Looks like we need tests added for min and max.

2022-05-19 18:43 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._values.to_arrow()
Hint: What type of object is returned by this method? Can you construct it directly?

2022-05-20 16:45 UTC, vyasr requested changes

2022-05-20 16:45 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +    def max(self):
This calculation still isn't quite right. Consider the following:
```
>>> idx = pd.RangeIndex(1, 21, 5)
>>> idx.max()
16
>>> idx.stop - 1
20
```
It turns out that we already [precompute this in the constructor](https://github.com/rapidsai/cudf/blob/branch-22.06/python/cudf/cudf/core/index.py#L184), though, so you can just use that!

2022-05-20 16:45 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._column.to_arrow()
Looks like this isn't quite there yet. You replaced `_values` with `_column`, but that has the same effect of creating a Column. Remember that the goal of this function is to generate a PyArrow array. It turns out that you can actually generate a PyArrow array directly from a range object, which would completely avoid creating a column. 
```
>>> import pyarrow
>>> idx = cudf.RangeIndex(10)
>>> idx._range
range(0, 10)
>>> pyarrow.array(idx._range)
<pyarrow.lib.Int64Array object at 0x7f5d08d645e0>
[
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9
]
>>> idx.to_arrow()
<pyarrow.lib.Int64Array object at 0x7f5d08d64520>
[
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9
]
```

2022-05-20 20:50 UTC, skirui-source commented
@gpucibot  rerun tests

2022-05-20 21:04 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +
We don't need to add a new property that doesn't exist in pandas, just use it in defining `max`.
```suggestion
```

2022-05-20 21:05 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self.end
```suggestion
        return self._end
```

2022-05-20 22:08 UTC, vyasr commented
@skirui-source while we wait for CI to get fixed, could you rerun all the benchmarks that you added for this PR and post before/after numbers?

2022-05-26 07:24 UTC, skirui-source commented
@gpucibot  rerun tests

2022-05-26 07:46 UTC, skirui-source commented
> @skirui-source while we wait for CI to get fixed, could you rerun all the benchmarks that you added for this PR and post before/after numbers?

@vyasr  i believe this PR is ready to merge once CI passes? please confirm.

2022-05-26 21:44 UTC, vyasr commented
@skirui-source it looks like there's a minor issue with my suggestion for `to_arrow` for when the index is empty. Let me know if you have trouble resolving that. Once that's done, please post before/after benchmarks so that we know the impact of this PR before we merge.

2022-06-24 23:04 UTC, skirui-source commented
@gpucibot rerun tests

2022-06-27 22:25 UTC, vyasr commented
rerun tests

2022-06-28 00:17 UTC, vyasr reviewed
It looks like `dask_cudf` heavily relies on `isna`, so you'll need to add that as well. That's another method that should be possible to implement significantly more efficiently than the current approach!

2022-06-28 00:17 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._as_int64().to_numpy()
This can just call self._values_host

2022-06-28 23:57 UTC, vyasr commented
@galipremsagar I am curious, are any of these methods important enough that we might see impacts in the dask layer?

2022-06-29 05:35 UTC, skirui-source commented
A comparison of before/after benchmark results outlined below  || CC: @vyasr 


<details><summary>Benchmarks -- isna()</summary>
<p>

```
---------------------------- benchmark '-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_false_rows_100': 2 tests ----------------------------
Name (time in us)                                                                                Min                Max               Mean          
----------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_false_rows_100] (0001)     53.7170 (1.0)      87.9790 (1.0)      54.9051 (1.0)    
bench_isna[-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_false_rows_100] (0002)     54.2990 (1.01)     93.5810 (1.06)     55.7662 (1.02)   
----------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------- benchmark '-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_true_rows_100': 2 tests ------------------------------
Name (time in us)                                                                               Min                   Max               Mean          
------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_true_rows_100] (0001)     54.5150 (1.0)         86.3610 (1.0)      55.7907 (1.0)    
bench_isna[-alt0-series_dtype_int_rows_100-series_dtype_int_nulls_true_rows_100] (0002)     54.9030 (1.01)     1,336.0490 (15.47)    56.4717 (1.01)   
------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------- benchmark '-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_false_rows_10000': 2 tests ----------------------------
Name (time in us)                                                                                    Min                 Max               Mean          
---------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_false_rows_10000] (0001)     52.7260 (1.0)      215.1110 (2.43)     53.9606 (1.0)    
bench_isna[-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_false_rows_10000] (0002)     54.3860 (1.03)      88.5800 (1.0)      55.5691 (1.03)   
---------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------- benchmark '-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_true_rows_10000': 2 tests ----------------------------
Name (time in us)                                                                                   Min                Max               Mean          
-------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_true_rows_10000] (0001)     53.5440 (1.0)      91.5190 (1.02)     54.6892 (1.0)    
bench_isna[-alt0-series_dtype_int_rows_10000-series_dtype_int_nulls_true_rows_10000] (0002)     55.1240 (1.03)     89.5140 (1.0)      55.9766 (1.02)   
-------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------ benchmark '-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_false_rows_1000000': 2 tests -----------------------------
Name (time in us)                                                                                        Min                   Max               Mean          
---------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_false_rows_1000000] (0001)     61.8980 (1.0)      1,341.3070 (13.29)    63.7352 (1.00)   
bench_isna[-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_false_rows_1000000] (0002)     62.2410 (1.01)       100.9180 (1.0)      63.5270 (1.0)    
---------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------- benchmark '-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_true_rows_1000000': 2 tests -----------------------------
Name (time in us)                                                                                       Min                 Max               Mean          
------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_true_rows_1000000] (0001)     70.9560 (1.0)      102.6580 (1.06)     72.1038 (1.0)    
bench_isna[-alt0-series_dtype_int_rows_1000000-series_dtype_int_nulls_true_rows_1000000] (0002)     71.8020 (1.01)      97.0450 (1.0)      72.7449 (1.01)   
------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------- benchmark '-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_false_cols_1_rows_100': 2 tests -----------------------------
Name (time in us)                                                                                                                               Min                 Max               Mean          
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_false_cols_1_rows_100] (0001)     57.3780 (1.0)      115.8750 (1.24)     58.7856 (1.0)    
bench_isna[-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_false_cols_1_rows_100] (0002)     60.8120 (1.06)      93.5670 (1.0)      62.3965 (1.06)   
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------- benchmark '-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_true_cols_1_rows_100': 2 tests ----------------------------
Name (time in us)                                                                                                                              Min                 Max               Mean          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_isna[-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_true_cols_1_rows_100] (0001)     58.2100 (1.0)      244.7910 (1.0)      59.7907 (1.0)    
bench_isna[-alt1-dataframe_dtype_int_cols_1-dataframe_dtype_int_cols_1_rows_100-dataframe_dtype_int_nulls_true_cols_1_rows_100] (0002)     61.4090 (1.05)     626.0160 (2.56)     62.6226 (1.05)   

```
</p>
</details>


<details><summary>Benchmarks -- argsort()</summary>
<p>

```
------------------------------- benchmark '-alt0-series_dtype_int_rows_ [...]

2022-06-29 18:24 UTC, vyasr commented
@skirui-source it looks like you ran all the benchmarks for DataFrame/Series/Index objects, but what we want to see is the performance of RangeIndex objects. Can you run those benchmarks?

2022-07-06 23:19 UTC, skirui-source commented
@vyasr Below is the  updated summary of before/after comparison-results  for the ` RangeIndex` methods implemented in this PR.
Top = before , 
Bottom = after 

There's a performance gain with the new implementations of `values_host, to_numpy, nunique, min and max` 

For `isna()`, there's a 5x decrease in performance  for smaller (100, 10k rows)  and ~23% gain for  larger (1000k rows) , 
whereas `argsort`  shows a  5x gain for larger rows and ~27% loss for smaller (100 rows) 

`to_arrow()` has a very significant decrease in perfomance for larger rows (10k and 1000k rows), which indicates that an alternative implementation should definitely be considered. 
 


**<details><summary>Benchmarks -- values_host() </summary>**
<p>

```
-------------------------------- benchmark '100': 2 tests ---------------------------------
Name (time in us)                      Min                 Max                Mean          
--------------------------------------------------------------------------------------------
bench_values_host[100] (0001)     130.4040 (8.19)     208.3239 (8.15)     150.4182 (9.28)   
bench_values_host[100] (0010)      15.9210 (1.0)       25.5479 (1.0)       16.2057 (1.0)    
--------------------------------------------------------------------------------------------


---------------------------------- benchmark '10000': 2 tests ----------------------------------
Name (time in us)                        Min                   Max                Mean          
------------------------------------------------------------------------------------------------
bench_values_host[10000] (0001)     143.2470 (7.45)     1,636.6240 (44.72)    151.8111 (7.78)   
bench_values_host[10000] (0010)      19.2380 (1.0)         36.5990 (1.0)       19.5163 (1.0)    
------------------------------------------------------------------------------------------------


------------------------------ benchmark '1000000': 2 tests ------------------------------
Name (time in ms)                        Min               Max              Mean          
------------------------------------------------------------------------------------------
bench_values_host[1000000] (0001)     1.9555 (5.27)     2.0689 (3.55)     1.9764 (5.25)   
bench_values_host[1000000] (0010)     0.3710 (1.0)      0.5835 (1.0)      0.3765 (1.0)    
------------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- to_numpy() </summary>**
<p>

```
--------------------------------- benchmark '100': 2 tests --------------------------------
Name (time in us)                   Min                   Max                Mean          
-------------------------------------------------------------------------------------------
bench_to_numpy[100] (0002)     140.4630 (8.59)     2,684.6200 (82.00)    156.0319 (9.42)   
bench_to_numpy[100] (0011)      16.3490 (1.0)         32.7390 (1.0)       16.5626 (1.0)    
-------------------------------------------------------------------------------------------


--------------------------------- benchmark '10000': 2 tests --------------------------------
Name (time in us)                     Min                   Max                Mean          
---------------------------------------------------------------------------------------------
bench_to_numpy[10000] (0002)     175.5400 (9.09)     2,172.9690 (58.60)    181.8639 (9.29)   
bench_to_numpy[10000] (0011)      19.3160 (1.0)         37.0831 (1.0)       19.5867 (1.0)    
---------------------------------------------------------------------------------------------


----------------------------- benchmark '1000000': 2 tests ----------------------------
Name (time in ms)                     Min               Max              Mean          
---------------------------------------------------------------------------------------
bench_to_numpy[1000000] (0002)     4.0722 (11.07)    4.2537 (2.28)     4.1229 (10.85)  
bench_to_numpy[1000000] (0011)     0.3679 (1.0)      1.8640 (1.0)      0.3800 (1.0)    
---------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- to_arrow() </summary>**
<p>

```

------------------------------ benchmark '100': 2 tests ------------------------------
Name (time in us)                  Min                Max               Mean          
--------------------------------------------------------------------------------------
bench_to_arrow[100] (0003)     31.0621 (1.49)     62.9970 (1.53)     32.4056 (1.52)   
bench_to_arrow[100] (0012)     20.8389 (1.0)      41.1680 (1.0)      21.3884 (1.0)    
--------------------------------------------------------------------------------------


----------------------------------- benchmark '10000': 2 tests ----------------------------------
Name (time in us)                       Min                   Max                  Mean          
-------------------------------------------------------------------------------------------------
bench_to_arrow[10000] (0003)        51.5661 (1.0)        132.3780 (1.0)         53.7369 (1.0)    
bench_to_arrow[10000] (0012)     1,338.6020 (25.96)    2,574.3520 (19.45)    1,394.9370 (25.96)  
-------------------------------------------------------------------------------------------------


-------------------------------- benchmark '1000000': 2 tests -------------------------------
Name (time in ms)                       Min                 Max                Mean          
---------------------------------------------------------------------------------------------
bench_to_arrow[1000000] (0003)       1.6222 (1.0)        6.4185 (1.0)        1.6711 (1.0)    
bench_to_arrow[1000000] (0012)     136.0984 (83.90)    157.4108 (24.52)    146.2887 (87.54)  
---------------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- argosrt() </summary>**
<p>

```

-------------------------------- benchmark '100': 2 tests --------------------------------
Name (time in us)                  Min                   Max                Mean          
------------------------------------------------------------------------------------------
bench_argsort[100] (0004)     292.5890 (1.0)      2,025.7250 (3.93)     303.4653 (1.0)    
bench_argsort[100] (0013)     338.3789 (1.16)       515.2241 (1.0)      386.7162 (1.27)   
------------------------------------------------------------------------------------------


-------------------------------- benchmark '10000': 2 tests --------------------------------
Name (time in us)                    Min                   Max                Mean          
--------------------------------------------------------------------------------------------
bench_argsort[10000] (0004)     346.4050 (1.14)     4,957.3990 (1.18)     381.0494 (1.20)   
bench_argsort[10000] (0013)     304.6320 (1.0)      4,212.4250 (1.0)      318.0467 (1.0)    
--------------------------------------------------------------------------------------------


---------------------------- benchmark '1000000': 2 tests ----------------------------
Name (time in ms)                    Min               Max              Mean          
--------------------------------------------------------------------------------------
bench_argsort[1000000] (0004)     2.2952 (6.48)     2.8936 (1.0)      2.4156 (5.48)   
bench_argsort[1000000] (0013)     0.3541 (1.0)      3.8453 (1.33)     0.4409 (1.0)    
--------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- nunique() </summary>**
<p>

```
----------------------------- benchmark '100': 2 tests ----------------------------
Name (time in us)                Min                Max              Mean          
-----------------------------------------------------------------------------------
bench_nuni [...]

2022-07-06 23:49 UTC, vyasr reviewed
There's something odd with `isna` and `argsort`. On my current branch, I don't get very consistent measurements of the performance of `cupy.zeros` or `cupy.arange`. I suspect that it has to do with either underlying memory allocation characteristics or some initialization logic rather than the performance of the API itself, but I'm not 100% sure. I don't quite trust those numbers, though.

The `to_arrow` measurement, definitely looks like it's problematic. I think that's basically indicating that populating a PyArrow array sequentially on the host is just a lot slower than populating it in parallel on device. My guess is that this is an API where we are probably willing to eat the GPU memory hit of a conversion to an Int64Index rather than the performance hit. Unless @shwina or @galipremsagar disagree (maybe there are Dask impacts that I am unaware of) I would recommend reverting that implementation to just the naive `self._as_int64().to_arrow()`.

2022-07-06 23:49 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self.start
The `min` isn't necessarily the start. What happens if `step` is negative?

2022-07-06 23:49 UTC, vyasr commented on python/cudf/cudf/core/index.py
> +        return self._end
Same question as `min`, what if `step` is negative?

2022-07-07 22:36 UTC, vyasr commented
It looks like there's still a pandas-incompatible benchmark in there. To find these, take your benchmarks and run them like this:
```
CUDF_BENCHMARKS_USE_PANDAS=ON CUDF_BENCHMARKS_DEBUG_ONLY=ON pytest...
```
That will tell you if any of your benchmarks will fail when run with pandas. See #11122 for more information (hopefully that gets merged soon, then it'll be available on our main docs page).

2022-07-13 05:24 UTC, skirui-source commented
> It looks like there's still a pandas-incompatible benchmark in there. To find these, take your benchmarks and run them like this:
> 
> ```
> CUDF_BENCHMARKS_USE_PANDAS=ON CUDF_BENCHMARKS_DEBUG_ONLY=ON pytest...
> ```
> 
> That will tell you if any of your benchmarks will fail when run with pandas. See #11122 for more information (hopefully that gets merged soon, then it'll be available on our main docs page).


In response to this, `to_arrow()` seems to be the only pandas- incompatible benchmarks, how should i resolve? 


```
FAILED bench_rangeindex.py::bench_to_arrow[20] - AttributeError: 'RangeIndex' object has no attribute 'to_arrow'
FAILED bench_rangeindex.py::bench_to_arrow[10] - AttributeError: 'RangeIndex' object has no attribute 'to_arrow'
```

2022-07-13 16:46 UTC, vyasr commented
Any method that doesn't have a pandas equivalent can't be run with pandas. I added a mark to solve this case. You should decorate those benchmarks with that mark `pandas_incompatible`. See [this example](https://github.com/rapidsai/cudf/blob/branch-22.08/python/cudf/benchmarks/API/bench_frame_or_index.py#L39).

2022-07-13 18:52 UTC, skirui-source commented
@vyasr  I have resolved the t`o_arrow()` benchmark, any feedback on the other implem. before i proceed with benchmarking?

2022-07-14 03:40 UTC, skirui-source commented
@vyasr The updated  before/after comparison benchmark results:


**<details><summary>Benchmarks -- values_host() </summary>**
<p>

```

--------------------------------- benchmark '100': 2 tests ---------------------------------
Name (time in us)                      Min                 Max                Mean          
--------------------------------------------------------------------------------------------
bench_values_host[100] (0001)     130.7169 (8.15)     210.0670 (6.23)     151.7630 (9.21)   
bench_values_host[100] (0010)      16.0381 (1.0)       33.7029 (1.0)       16.4822 (1.0)    
--------------------------------------------------------------------------------------------


---------------------------------- benchmark '10000': 2 tests ----------------------------------
Name (time in us)                        Min                   Max                Mean          
------------------------------------------------------------------------------------------------
bench_values_host[10000] (0001)     145.7820 (7.51)     2,037.2421 (54.40)    153.6504 (7.48)   
bench_values_host[10000] (0010)      19.4218 (1.0)         37.4499 (1.0)       20.5327 (1.0)    
------------------------------------------------------------------------------------------------


------------------------------ benchmark '1000000': 2 tests ------------------------------
Name (time in ms)                        Min               Max              Mean          
------------------------------------------------------------------------------------------
bench_values_host[1000000] (0001)     1.8607 (5.07)     1.9168 (3.33)     1.8733 (4.84)   
bench_values_host[1000000] (0010)     0.3673 (1.0)      0.5760 (1.0)      0.3869 (1.0)    
------------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- to_numpy() </summary>**
<p>

```

--------------------------------- benchmark '100': 2 tests --------------------------------
Name (time in us)                   Min                   Max                Mean          
-------------------------------------------------------------------------------------------
bench_to_numpy[100] (0002)     132.7849 (8.26)     1,384.7651 (41.82)    138.6965 (8.34)   
bench_to_numpy[100] (0011)      16.0839 (1.0)         33.1162 (1.0)       16.6237 (1.0)    
-------------------------------------------------------------------------------------------


-------------------------------- benchmark '10000': 2 tests -------------------------------
Name (time in us)                     Min                 Max                Mean          
-------------------------------------------------------------------------------------------
bench_to_numpy[10000] (0002)     166.8851 (8.61)     223.9509 (4.20)     172.1689 (8.68)   
bench_to_numpy[10000] (0011)      19.3850 (1.0)       53.2640 (1.0)       19.8280 (1.0)    
-------------------------------------------------------------------------------------------


----------------------------- benchmark '1000000': 2 tests ----------------------------
Name (time in ms)                     Min               Max              Mean          
---------------------------------------------------------------------------------------
bench_to_numpy[1000000] (0002)     4.3659 (11.89)    4.5955 (8.19)     4.4503 (11.88)  
bench_to_numpy[1000000] (0011)     0.3671 (1.0)      0.5614 (1.0)      0.3745 (1.0)    
---------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- argsort() </summary>**
<p>

```

-------------------------------- benchmark '100': 2 tests --------------------------------
Name (time in us)                  Min                   Max                Mean          
------------------------------------------------------------------------------------------
bench_argsort[100] (0004)     301.8749 (1.0)      1,885.9080 (3.53)     313.4095 (1.0)    
bench_argsort[100] (0013)     318.6350 (1.06)       533.6509 (1.0)      371.2334 (1.18)   
------------------------------------------------------------------------------------------


-------------------------------- benchmark '10000': 2 tests --------------------------------
Name (time in us)                    Min                   Max                Mean          
--------------------------------------------------------------------------------------------
bench_argsort[10000] (0004)     359.0430 (1.18)     4,981.6479 (2.75)     383.8440 (1.23)   
bench_argsort[10000] (0013)     303.5921 (1.0)      1,808.2329 (1.0)      313.1777 (1.0)    
--------------------------------------------------------------------------------------------


---------------------------- benchmark '1000000': 2 tests ----------------------------
Name (time in ms)                    Min               Max              Mean          
--------------------------------------------------------------------------------------
bench_argsort[1000000] (0004)     2.2911 (6.56)     2.9083 (1.0)      2.4202 (5.84)   
bench_argsort[1000000] (0013)     0.3492 (1.0)      4.2373 (1.46)     0.4146 (1.0)    
--------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- nunique() </summary>**
<p>

```

---------------------------- benchmark '100': 2 tests ----------------------------
Name (time in us)                Min                Max              Mean          
-----------------------------------------------------------------------------------
bench_nunique[100] (0005)     9.0001 (4.72)     14.7661 (2.65)     9.1371 (4.67)   
bench_nunique[100] (0014)     1.9080 (1.0)       5.5791 (1.0)      1.9572 (1.0)    
-----------------------------------------------------------------------------------


----------------------------- benchmark '10000': 2 tests -----------------------------
Name (time in us)                  Min                 Max              Mean          
--------------------------------------------------------------------------------------
bench_nunique[10000] (0005)     9.0371 (4.64)      26.3380 (1.0)      9.3150 (4.57)   
bench_nunique[10000] (0014)     1.9481 (1.0)      887.4950 (33.70)    2.0378 (1.0)    
--------------------------------------------------------------------------------------


----------------------------- benchmark '1000000': 2 tests ----------------------------
Name (time in us)                    Min                Max              Mean          
---------------------------------------------------------------------------------------
bench_nunique[1000000] (0005)     9.1090 (4.64)     26.3939 (1.22)     9.7936 (4.81)   
bench_nunique[1000000] (0014)     1.9611 (1.0)      21.5990 (1.0)      2.0376 (1.0)    
---------------------------------------------------------------------------------------
```
</p>
</details>


**<details><summary>Benchmarks -- isna() </summary>**
<p>

```

------------------------------ benchmark '100': 2 tests -----------------------------
Name (time in us)               Min                 Max                Mean          
-------------------------------------------------------------------------------------
bench_isna[100] (0006)      53.5939 (1.0)      140.1899 (1.0)       55.6012 (1.0)    
bench_isna[100] (0015)     267.8588 (5.00)     513.0582 (3.66)     330.8294 (5.95)   
-------------------------------------------------------------------------------------


------------------------------- benchmark '10000': 2 tests ------------------------------
Name (time in us)                 Min                   Max                Mean          
-----------------------------------------------------------------------------------------
bench_isna[10000] (0006)      53.8230 (1.0)         89.7220 (1.0)       54.8441 (1.0)    
bench_isna[10000] (0015)     266.2621 (4.95)     1,266.3819 (14.11)    273.8039 (4.99)   
----------------------------- [...]

2022-07-14 16:42 UTC, vyasr commented
OK, so I have a theory about what's going on with the `isna` benchmark. The performance of cupy changes quite significantly depending on whether or not `cudf` is imported, and _when_ `cudf` is imported. Part of that makes sense to me since `cudf` changes `cupy`'s memory allocator, but I do find it a bit confusing that it matters whether or not `cupy` performs any allocations before `cudf` is imported. I strongly suspect that the effect of importing `cudf` on `cupy` performance is responsible for the `isna` perf that you're seeing. IMO it's probably still OK to move forward since to me this indicates that the real problem is around our need/ability to improve the performance of the rmm allocator with cupy, especially since switching to pool mode makes the `cupy` approach faster again. The numbers below are entirely reproducible for me on multiple runs:

```
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy

In [2]: N = 10000

In [3]: %timeit cupy.zeros(N, dtype=bool)
10.6 µs ± 7.24 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: %timeit cupy.zeros(N, dtype=bool)
6.82 µs ± 51.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [5]: import cudf

In [6]: %timeit cupy.zeros(N, dtype=bool)
The slowest run took 4.11 times longer than the fastest. This could mean that an intermediate result is being cached.
41.3 µs ± 26.2 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [7]: %timeit cupy.zeros(N, dtype=bool)
23.6 µs ± 1.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [8]:
Do you really want to exit ([y]/n)? y
(rapids) rapids@compose:~$ ipython
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cupy

In [2]: import cudf

In [3]: N = 10000

In [4]: %timeit cupy.zeros(N, dtype=bool)
307 µs ± 57.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit cupy.zeros(N, dtype=bool)
268 µs ± 3.37 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [6]: idx = cudf.RangeIndex(N)

In [7]: %timeit idx.isna()
79.1 µs ± 1.93 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [8]: cudf.set_allocator(pool=True)

In [9]: %timeit cupy.zeros(N, dtype=bool)
13.2 µs ± 71.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [10]: %timeit idx.isna()
69.9 µs ± 812 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
``` 

@shwina @galipremsagar what do you think?

2022-07-14 16:56 UTC, galipremsagar commented
> @shwina @galipremsagar what do you think?

Yeah. That and even if you carefully see the allocated memory isn't freed up in cupy for other libraries to utilize.. I think we should move forward since this is a known problem.

2022-07-14 19:41 UTC, skirui-source commented
@vyasr  is this PR ready to merge?

2022-07-14 20:37 UTC, vyasr approved these changes
Thanks for all your hard work and all the iterations!

I was going to let Ashwin and/or Prem take a final look just in case they have a strong opinion on the `isna` benchmark. Let's definitely merge by EOD today though! This PR has been floating around for a long time. If they don't get to it, we can always roll back a change if they feel strongly about it. So unless someone explicitly says otherwise, I would go ahead and merge before you check out for the day.

2022-07-14 20:40 UTC, galipremsagar requested changes
Just a placeholder request, will unblock as I finish the review.

2022-07-14 22:19 UTC, galipremsagar approved these changes
@vyasr Looks like I think it is okay for now to leave the implementation as is, these are the numbers that I was getting:
```python
In [2]: idx = cudf.RangeIndex(0, 1000000)

# This PR (cupy.zeros)
In [3]: %timeit idx.isna()
361 µs ± 78.1 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


# branch-22.08 (Materializing + isna)

In [3]: %timeit idx.isna()
441 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Sure they aren't being quite consistent across runs. But we'd be avoiding the materialization step for now, if we see this show up in dask profiles we can think about how to optimize it then.

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def where(self, cond, other=None, inplace=False):
```suggestion
    @_cudf_nvtx_annotate
    def where(self, cond, other=None, inplace=False):
```

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def to_numpy(self):
```suggestion
    @_cudf_nvtx_annotate
    def to_numpy(self):
```

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def to_arrow(self):
```suggestion
    @_cudf_nvtx_annotate
    def to_arrow(self):
```

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def nunique(self):
```suggestion
    @_cudf_nvtx_annotate
    def nunique(self):
```

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def isna(self):
```suggestion
    @_cudf_nvtx_annotate
    def isna(self):
```

2022-07-14 22:19 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +    def _minmax(self, meth: str):
```suggestion
    @_cudf_nvtx_annotate
    def _minmax(self, meth: str):
```

2022-07-15 00:44 UTC, galipremsagar commented
@gpucibot merge

2022-07-15 00:44 UTC, merged