Support for Zstandard decompression in Parquet reader
rapidsai/cudf pull request #10847
Opened 2022-05-13 07:13 UTC by vuule

2022-05-16 18:52 UTC, galipremsagar approved these changes

2022-05-16 19:05 UTC, hyperbolic2346 requested changes
Nit at best, but I prefer caps for `#define` and it seems that RMM and CUDF follow this as well. Other than that this looks great. Thank you.

2022-05-16 19:05 UTC, hyperbolic2346 commented on cpp/src/io/comp/nvcomp_adapter.cpp
> +#endif
```suggestion
#include nvcomp_zstd_header
#define NVCOMP_HAS_ZSTD 1
#else
#define NVCOMP_HAS_ZSTD 0
#endif
```

2022-05-16 19:05 UTC, hyperbolic2346 commented on cpp/src/io/comp/nvcomp_adapter.cpp
> +#if nvcomp_has_zstd
```suggestion
#if NVCOMP_HAS_ZSTD
```

2022-05-16 19:05 UTC, hyperbolic2346 commented on cpp/src/io/comp/nvcomp_adapter.cpp
> +#if nvcomp_has_zstd
```suggestion
#if NVCOMP_HAS_ZSTD
```

2022-05-16 21:01 UTC, hyperbolic2346 approved these changes
🚀

2022-05-17 10:33 UTC, karthikeyann approved these changes

2022-05-17 15:03 UTC, charlesbluca approved these changes

2022-05-17 22:41 UTC, vuule commented
@gpucibot merge

2022-05-17 22:41 UTC, merged