fix doxygen warnings in fixed_point.hpp
rapidsai/cudf pull request #10922
Opened 2022-05-22 12:31 UTC by karthikeyann

Fixes parts of https://github.com/rapidsai/cudf/issues/9373
added missing documentation to fix doxygen warnings in `fixed_point/fixed_point.hpp`
fixes some existing docstrings.
fixes 47 warnings.

2022-05-22 20:07 UTC, davidwendt commented on cpp/include/cudf/fixed_point/fixed_point.hpp
> +  using rep = Rep;  //!< The representation type
```suggestion
  using rep = Rep;  ///< The representation type
```

2022-05-25 13:42 UTC, davidwendt requested changes

2022-05-25 13:42 UTC, davidwendt commented on cpp/include/cudf/fixed_point/fixed_point.hpp
> + * @brief Returns `true` if the type is supported underlying representation type by `fixed_point`
```suggestion
 * @brief Returns `true` if the representation type is supported by `fixed_point`
```

2022-05-25 13:42 UTC, davidwendt commented on cpp/include/cudf/fixed_point/fixed_point.hpp
> + * @return `true` if the type is supported value type to construct a `fixed_point` type
```suggestion
 * @brief Returns `true` if the value type is supported for constructing a `fixed_point`
 *
 * @tparam T The construction value type
 * @return `true` if the value type is supported to construct a `fixed_point` type
```

2022-05-25 19:09 UTC, vyasr approved these changes
One minor suggestion, but nothing blocking assuming you address @davidwendt's review!

2022-06-01 09:31 UTC, karthikeyann commented
@gpucibot merge

2022-06-01 09:31 UTC, merged