Add strong index type adapters for `cudf::experimental::row::` operators
rapidsai/cudf pull request #11095
Opened 2022-06-12 21:37 UTC by ttnghia

Row operators for two tables such as equality comparison require strong index types. As such, the users need to feed into the comparator some input iterators of strong index types for the comparison. However, on each of the comparing tables, we may also want to perform self-comparison or hashing on its rows. Unfortunately, the current implementation of table self comparators and row hasher only accepts `size_type` input for row indices.

This PR adds strong index type adapters for the table self comparators and row hasher.

2022-06-13 16:48 UTC, jrhemstad requested changes
I do not think this is a wise change. It is definitely not something that we should broadly apply by default to every `self_comparator` operator.

I think it would be astonishing and error prone for this code to work as it defeats the purpose of the strong types.
```
auto less = self_comparator.less();
auto r0 = less(size_type{i}, size_type{j});
auto r1 = less(lhs_index_type{i], lhs_index_type{j});
auto r2 = less(rhs_index_type{i}, rhs_index_type{j});
```

I understand the need to sometimes do a "self" operation in a context where one only has strongly-typed indices. Without having seen a concrete example, my intuition would be that it should be the calling code's responsibility to convert a strong type index into a raw `size_type` as opposed to it being handled implicitly and leading to astonishing results. 

@ttnghia could you point me to an example of what inspired this?

2022-06-13 16:59 UTC, ttnghia commented
> @ttnghia could you point me to an example of what inspired this?

Sure, here is the example: https://github.com/rapidsai/cudf/pull/10656/commits/0d66a8cb5f60739c2afc88307726fb1d873a86d7#diff-8d714835115e07e9f7ac9cc8a3e095fbda10768b15a86be65116388f1a4bfd46R114-R124

That use case is no longer needed as I have switched to using `static_multimap`+`pair_contains`. But I believe that if other people need to implement `static_map` then this PR is necessary.

2022-06-16 17:51 UTC, bdice commented
> Without having seen a concrete example, my intuition would be that it should be the calling code's responsibility to convert a strong type index into a raw `size_type` as opposed to it being handled implicitly and leading to astonishing results.

> If we don't create adapters in `row_operator`, we still have to create them at the caller site to convert strong index types into `size_type` anyhow. This may be repetitive.

I agree with @jrhemstad that it is most appropriate to do this in the calling code when required. I concur that the proposed change would break the current design's symmetry/clarity and increase "astonishment." We may wish to revisit this in the future, but it feels unnecessary from what I know right now.

2022-06-16 17:52 UTC, ttnghia commented
Okay then I'm going to close this for now, as it is no longer my blocker. Will revisit this if needed.

2022-06-16 17:52 UTC, closed without merging