Documentation fix for concatenate
rapidsai/cudf pull request #11187
Opened 2022-07-01 16:33 UTC by dagardner-nv

cudf::concatinate returns a table not a table_view as the docstrings suggest

fixes #11186

2022-07-01 16:33 UTC, GPUtester commented
Can one of the admins verify this patch?

2022-07-01 17:00 UTC, davidwendt requested changes

2022-07-01 17:00 UTC, davidwendt commented on cpp/include/cudf/concatenate.hpp
> + * @return std::unique_ptr<table> single table having all the rows from the elements of
Do not include the return type in the `@return` tag:
https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/docs/DOCUMENTATION.md#return

2022-07-01 17:17 UTC, davidwendt approved these changes

2022-07-04 01:09 UTC, ttnghia approved these changes

2022-07-08 13:42 UTC, ttnghia commented
Rerun tests.

2022-07-08 14:40 UTC, ajschmidt8 commented
ok to test

2022-07-08 17:14 UTC, davidwendt commented
@gpucibot merge

2022-07-08 17:14 UTC, merged