Use `cudf::lists::distinct` in Java binding
rapidsai/cudf pull request #11233
Opened 2022-07-08 23:12 UTC by ttnghia

Java binding has `dropListDuplicates` and `dropListDuplicatesWithKeysValues` APIs to create lists column having distinct list elements. Previously they have been implemented by calling to `cudf::lists::drop_list_duplicates`, which relies on stably sorting the input lists column to extract unique list elements.

This PR makes the following changes:
 * Modifying the underlying implementation of `dropListDuplicates` to use `cudf::lists::distinct`, which has `O(n)` time complexity, and
 * Adding a new JNI-dedicated function `cudf::jni::lists_distinct_by_key` so `dropListDuplicatesWithKeysValues` will call it instead of `cudf::lists::drop_list_duplicates`. Removing lists duplicate with keys-values pair input is only needed by Spark's `create_map` function.

Depends on:
 * https://github.com/rapidsai/cudf/pull/11149

2022-07-18 20:08 UTC, mythrocks commented on java/src/main/native/src/ColumnViewJni.cu
> +  cudf::detail::label_segments(input.offsets_begin(), input.offsets_end(), labels.begin(),
Also, the code that constructs the group-labels column for keys: That is pretty sleek.

2022-07-18 20:35 UTC, mythrocks requested changes
Good work!

One minor documentation rephrasing requested. Plus, we've relaxed the requirement for non-sliced input columns; we should add a test to confirm.

2022-07-18 21:37 UTC, ttnghia commented on java/src/main/native/src/ColumnViewJni.cpp
> -    CUDF_EXPECTS(input_cv->offset() == 0, "Input column has non-zero offset.");
Got it. I just added a test for that in Java.

2022-07-19 02:03 UTC, mythrocks approved these changes
LGTM!

2022-07-19 02:25 UTC, ttnghia commented
@gpucibot merge

2022-07-19 02:26 UTC, merged