Add --output-on-failure to ctest args.
rapidsai/cudf pull request #11321
Opened 2022-07-21 16:00 UTC by vyasr

Resolves #3036 by making `make test` or `ninja test` default to showing output when tests fail.

2022-07-21 16:01 UTC, vyasr commented
@robertmaynard is this change too broad in scope? I don't see any obvious way to make this configurable, nor am I sure that it's particularly beneficial to do so.

2022-07-21 18:01 UTC, robertmaynard requested changes
Since `CMAKE_CTEST_ARGUMENTS` is evaluated in the context of the root CMakeLists.txt we should instead move this logic to the `if(CUDF_BUILD_TESTS)` logic where we call `include(CTest)`.

2022-07-21 22:00 UTC, robertmaynard approved these changes

2022-07-21 22:53 UTC, bdice approved these changes

2022-07-22 20:05 UTC, vyasr commented
@gpucibot merge

2022-07-22 20:05 UTC, merged