Sanitize percentile_approx() output for empty input
rapidsai/cudf pull request #11498
Opened 2022-08-09 15:30 UTC by SrikarVanavasam

Closes #10856 

If all of the tdigest inputs to percentile_approx are empty, it will return a column containing null rows, as expected, but they will have unsanitary offsets. This PR checks if all the inputs are empty and returns an empty column as expected.

2022-08-09 19:48 UTC, ttnghia commented on cpp/src/quantiles/tdigest/tdigest.cu
> +  bool empty_input   = thrust::reduce(input.size_begin(), input.size_begin() + input.size()) == 0;
This is not safe. The size vales may have something like `-2, 2, -3, 3, ...` which sum to zero.

Let's check if all the size values are zero:
```suggestion
  bool empty_input   = thrust::count_if(rmm::exec_policy(), []__device__() { size[i] == 0} ) == input.size();
```

2022-08-09 19:53 UTC, ttnghia commented on cpp/src/quantiles/tdigest/tdigest.cu
> +  bool empty_input   = thrust::reduce(input.size_begin(), input.size_begin() + input.size()) == 0;
If the input is guaranteed to have size initialized (i.e., the size values are all valid) then `thrust::reduce` is enough. But don't forget to add `rmm::exec_policy`.

2022-08-10 17:08 UTC, mythrocks commented on cpp/src/quantiles/tdigest/tdigest.cu
> +  bool empty_input   = thrust::count_if(rmm::exec_policy(stream),
```suggestion
  auto const empty_input   = thrust::count_if(rmm::exec_policy(stream),
```
Please forgive my quoting [the Good Book](https://www.goodreads.com/book/show/105125.Effective_C_): Item 3 suggests: "Use const wherever possible".
By default, consider making variables `auto const`, and then removing the `const` if they are indeed "variable".  

Also, would `all_empty_rows` be a more descriptive name? `empty_input` implies `input.size() == 0`, which isn't the case.

I think you've made the right call on using `count_if()`; I think the intention is captured better here. I'm sure `reduce()` would have worked too, but not as clear in intention. 
`thrust::all_of()` would have fit best, but [it is slow](https://github.com/NVIDIA/thrust/issues/1016).

2022-08-10 17:10 UTC, mythrocks commented on cpp/src/quantiles/tdigest/tdigest.cu
> +                                      [] __device__(int x) { return x == 0; }) == input.size();
```suggestion
                                      [] __device__(auto const x) { return x == 0; }) == input.size();
```
We could have used `size_type` as well, but `auto` would guarantee a match.

2022-08-10 17:11 UTC, mythrocks commented on cpp/tests/quantiles/percentile_approx_test.cu
> +  CUDF_TEST_EXPECT_COLUMNS_EQUAL(*result, *expected);
:clap:

2022-08-10 17:11 UTC, mythrocks requested changes
Looks pretty good! Some minor nitpicks.

2022-08-10 17:18 UTC, mythrocks commented on cpp/src/quantiles/tdigest/tdigest.cu
> +  bool empty_input   = thrust::count_if(rmm::exec_policy(stream),
> I think you've made the right call on using `count_if()`...

Ah, I see that @ttnghia was here already. :p

2022-08-11 02:35 UTC, ttnghia approved these changes

2022-08-11 03:30 UTC, mythrocks approved these changes
Ship it!

2022-08-11 18:30 UTC, nvdbaranec approved these changes

2022-08-11 18:31 UTC, nvdbaranec commented
@gpucibot merge

2022-08-11 18:31 UTC, merged