Move cudf::strings::findall_record to cudf::strings::findall
rapidsai/cudf pull request #11575
Opened 2022-08-22 15:12 UTC by davidwendt

## Description
Replaces `cudf::strings::findall` with the implementation from `cudf::strings::findall_record`.
As referenced in #11510, the column-based `findall` implementation is not used and unnecessary over `findall_record` which returns a lists result. For documentation and discoverability `findall_record` is renamed to `findall` and the current `findall` implementation is removed.

Closes #11510 

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2022-08-23 17:23 UTC, davidwendt commented on cpp/src/strings/search/findall.cu
Nothing actually has been modified in this file. The original `findall.cu` was deleted and this file was renamed to `findall.cu`. Github did not detect this and so is just highlighting the differences between the two files.

2022-08-24 00:09 UTC, davidwendt commented on cpp/src/strings/search/findall.cu
Nothing actually has been modified in this file. The original `findall.cu` was deleted and this file was renamed to `findall.cu`. Github did not detect this and so is just highlighting the differences between the two files.

2022-08-24 13:54 UTC, robertmaynard approved these changes
CMake changes LGTM

2022-08-25 18:40 UTC, galipremsagar approved these changes

2022-08-25 21:01 UTC, bdice requested changes

2022-08-25 21:02 UTC, galipremsagar commented on python/cudf/cudf/core/column/string.py
> +        2      []
I checked that, and doc-tests don't seem to be covering `StringMethods` somehow. Is it because it isn't listed in `__all__`?

2022-08-25 21:07 UTC, bdice commented on python/cudf/cudf/core/column/string.py
> +        2      []
It looks like this is being missed in our doctests. I suspect that none of the `.str` class `StringMethods` or similar accessors for lists/structs are being doctested. I'll file an issue.

2022-08-25 21:13 UTC, bdice commented on python/cudf/cudf/core/column/string.py
> +        2      []
Issue filed. I'd like to see these docstrings tested/verified by hand, and the issue will guide us for future work. https://github.com/rapidsai/cudf/issues/11606

2022-08-26 14:36 UTC, davidwendt commented on python/cudf/cudf/core/column/string.py
> +        2      []
I've updated the docstring and verified it manually by executing:
```
>>> s = cudf.Series(['Lion', 'Monkey', 'Rabbit'])
>>> s.str.findall('Monkey')
0          []
1    [Monkey]
2          []
dtype: list
>>> s.str.findall('on')
0    [on]
1    [on]
2      []
dtype: list
>>> s.str.findall('on$')
0    [on]
1      []
2      []
dtype: list
>>> s.str.findall('b')
0        []
1        []
2    [b, b]
dtype: list

```

2022-08-29 18:51 UTC, bdice approved these changes
Thanks @davidwendt!

2022-08-29 20:47 UTC, jlowe approved these changes

2022-08-29 20:48 UTC, galipremsagar commented
@gpucibot merge

2022-08-29 20:48 UTC, merged