Fix exception in segmented-reduce benchmark
rapidsai/cudf pull request #11588
Opened 2022-08-24 14:25 UTC by davidwendt

## Description
Fixes exception thrown in `REDUCTION_NVBENCH`. 

```
Run:  [121/768] segmented_reduction_simple [Device=0 InputType=bool OutputType=F32 AggregationKinds=2 column_size=100000 num_segments=1000]
Fail: Unexpected error: cuDF failure at: /cudf/cpp/src/reductions/segmented_min.cu:33: segmented_min() operation requires matching output type
```

The code is refactored to reduce the generated benchmark code match input and output types and to force the output type to BOOL8 for aggregation kind ALL. This also removes code generated that is only _skipped_:

```
Run:  [277/768] segmented_reduction_simple [Device=0 InputType=I32 OutputType=I32 AggregationKinds=7 column_size=100000 num_segments=1000]
Skip: Invalid combination of dtype and aggregation type.

```

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-08-25 21:13 UTC, PointKernel requested changes
768 -> 192 :fire: 

Only one small issue when benchmarking with implicit stream.

2022-08-25 21:13 UTC, PointKernel commented on cpp/benchmarks/reduction/segment_reduce.cu
> +      segmented_reduce(input_view, offset_span, *agg, output_type, cudf::null_policy::INCLUDE);
Similar to the implementation here: https://github.com/rapidsai/cudf/blob/63a47d91fc558a5b0b89f3ce9b0a61ffb3ed84f5/cpp/benchmarks/groupby/group_max.cpp#L55-L57
We need to pass the target stream to nvbench `state` thus performance metrics can be recorded properly. I'm a bit surprised that the execution didn't crash with the current implementation.

2022-08-26 02:50 UTC, bdice approved these changes
Thanks @davidwendt! Please add the stream as noted by @PointKernel, otherwise LGTM.

2022-08-26 14:32 UTC, PointKernel approved these changes
LGTM

2022-08-26 15:48 UTC, ttnghia approved these changes

2022-08-29 12:27 UTC, merged