Ensure that all tests launch kernels on cudf's default stream
rapidsai/cudf pull request #11726
Opened 2022-09-21 00:16 UTC by vyasr

## Description

Currently many of our tests are only stream-safe because we run everything on the default stream. This PR updates tests to ensure that everything launches on cudf's default stream even when it is _not_ CUDA's default stream.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-09-21 04:06 UTC, bdice approved these changes

2022-09-21 13:26 UTC, robertmaynard requested changes
git grep `thrust::device` returns the following places we need to change as well:

```
copying/detail_gather_tests.cu:  thrust::sequence(thrust::device, gather_map.begin(), gather_map.end());
io/json_type_cast_test.cu:  thrust::transform(thrust::device,
io/json_type_cast_test.cu:  thrust::transform(thrust::device,
io/json_type_cast_test.cu:  thrust::transform(thrust::device,
iterator/optional_iterator_test_numeric.cu:  thrust::transform(thrust::device,
iterator/optional_iterator_test_numeric.cu:  auto result = thrust::reduce(thrust::device, results.begin(), results.end(), T_output{});
join/conditional_join_tests.cu:    thrust::device_vector<thrust::pair<cudf::size_type, cudf::size_type>> result_pairs(
join/conditional_join_tests.cu:    thrust::device_vector<thrust::pair<cudf::size_type, cudf::size_type>> reference_pairs(
join/conditional_join_tests.cu:    thrust::transform(thrust::device,
join/conditional_join_tests.cu:    thrust::transform(thrust::device,
join/conditional_join_tests.cu:    thrust::sort(thrust::device, result_pairs.begin(), result_pairs.end());
join/conditional_join_tests.cu:    thrust::sort(thrust::device, reference_pairs.begin(), reference_pairs.end());
join/conditional_join_tests.cu:      thrust::device, reference_pairs.begin(), reference_pairs.end(), result_pairs.begin()));
join/conditional_join_tests.cu:    thrust::sort(thrust::device, result->begin(), result->end());
join/conditional_join_tests.cu:    thrust::sort(thrust::device, reference->begin(), reference->end());
join/conditional_join_tests.cu:    EXPECT_TRUE(thrust::equal(thrust::device, result->begin(), result->end(), reference->begin()));
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:    auto const d_offsets = thrust::device_vector<size_type>(offsets);
reductions/segmented_reduction_tests.cpp:  auto const d_offsets = thrust::device_vector<size_type>(offsets);
strings/factories_test.cu:  thrust::transform(thrust::device,
transform/row_bit_count_test.cu:    thrust::device, ints_view.begin<int32_t>(), ints_view.end<int32_t>(), thrust::identity{});
transform/row_bit_count_test.cu:  thrust::tabulate(thrust::device,
transform/row_bit_count_test.cu:  thrust::fill_n(thrust::device,
utilities/column_utilities.cu:  EXPECT_TRUE(thrust::equal(thrust::device, typed_lhs, typed_lhs + size_bytes, typed_rhs));
utilities_tests/span_tests.cu:  auto d_thrust_vector = thrust::device_vector<int>(1);
```

2022-09-21 22:45 UTC, vyasr commented
A lot of those are `thrust::device_vector`, which is fine, but I do see some that are actually the execution policy. I'll have to investigate and see why my code didn't detect those.

That also raises another question, though. If someone does something like `thrust::host_vector<T> x = my_device_vector;`, thrust is going to synchronously copy that, right? Assuming that is correct, implicit `device_vector<->host_vector` copies in thrust are not stream safe (if cudf's default stream is switched away from the CUDA default stream), which is definitely something that thrust users rely on. That's something we need to keep in mind.

2022-09-21 23:27 UTC, vyasr commented
I was omitting to account for `cudaStreamLegacy`. Now I should get the rest.

2022-09-23 12:37 UTC, robertmaynard commented
> A lot of those are `thrust::device_vector`, which is fine, but I do see some that are actually the execution policy. I'll have to investigate and see why my code didn't detect those.
> 
> That also raises another question, though. If someone does something like `thrust::host_vector<T> x = my_device_vector;`, thrust is going to synchronously copy that, right? Assuming that is correct, implicit `device_vector<->host_vector` copies in thrust are not stream safe (if cudf's default stream is switched away from the CUDA default stream), which is definitely something that thrust users rely on. That's something we need to keep in mind. Once I extend my code to also check APIs like `cudaMemcpy` it should start catching cases like this, but I'm not sure what we want to do about it.

As far as I understand your assumptions are correct and those will copies will occur on the default CUDA stream.

2022-09-23 12:37 UTC, robertmaynard approved these changes

2022-09-23 20:26 UTC, ttnghia approved these changes
Curious if using the default stream for tests has been documented in the dev guide.

2022-09-23 22:04 UTC, vyasr commented
@gpucibot merge

2022-09-23 22:04 UTC, merged

2022-09-23 22:05 UTC, vyasr commented
@ttnghia I don't think so, but at this point I'm not even sure that's the best place for it. Since we're thinking about how to expose streams publicly, this is going to end up being a user-facing issue that needs documentation not just something for devs.