Add cudf::strings:udf::replace function
rapidsai/cudf pull request #12210
Opened 2022-11-18 22:53 UTC by davidwendt

## Description
Add udf function for replacing all occurrences of a target string within a source string with a replacement string.
This is to support #12207 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-11-21 23:40 UTC, DaceT commented
run benchmarks

2022-11-22 13:52 UTC, bdice commented on python/strings_udf/cpp/include/cudf/strings/udf/replace.cuh
> +  if (target.empty()) return udf_string(source);
Does this fit Python’s replace logic for empty targets? Or does pandas differ from this behavior / do we have an alternative function?
```python
>>> print('test'.replace('', 'a'))
ataeasata
```

2022-11-22 15:04 UTC, brandon-b-miller requested changes
I tried patching https://github.com/rapidsai/cudf/pull/12207 locally with this code and I found that this function passes my tests, _except_ for the cases @bdice mentioned where an empty string is being replaced by a nonempty character or sequence. 

there, my shim function around this is
```c++
extern "C" __device__ int replace(
  int* nb_retval, void* udf_str, void* const src, void* const to_replace, void* const replacement)
{
  auto src_ptr         = reinterpret_cast<cudf::string_view const*>(src);
  auto to_replace_ptr  = reinterpret_cast<cudf::string_view const*>(to_replace);
  auto replacement_ptr = reinterpret_cast<cudf::string_view const*>(replacement);

  auto udf_str_ptr = new (udf_str) udf_string;
  udf_string result;

  result = replace(*src_ptr, *to_replace_ptr, *replacement_ptr);

  *udf_str_ptr = result;

  return 0;
}

2022-11-22 19:54 UTC, bdice approved these changes
LGTM if the tests for empty targets are passing. I suppose the tests aren't supposed to be in this PR, but another one (#12207).

2022-11-22 20:06 UTC, brandon-b-miller approved these changes
Tests pass in my PR now with these changes.

2022-11-23 14:44 UTC, davidwendt commented
@gpucibot merge

2022-11-23 14:44 UTC, merged