Spill Statistics
rapidsai/cudf pull request #12223
Opened 2022-11-22 16:34 UTC by madsbk

Implements statistics of spilling, enable by setting `CUDF_SPILL_STATS=2`.

It is possible to access the statistics through the spill manager like:
```python
>>> get_global_manager().statistics
<SpillStatistics level=1>
```

To have each work in dask print spill statistics, do something like:
```python
    def spill_info():
        from cudf.core.buffer.spill_manager import get_global_manager
        manager = get_global_manager()
        stat = manager.statistics
        ret = f"spill_info() - get_global_manager: {manager}\n"
        ret += f"{stat}"
        print(ret)

    client.submit(spill_info)
```

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2022-11-23 17:10 UTC, wence- requested changes
Some minor things, but overall I think this looks good.

2022-11-24 07:37 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +           permanently (potential high overhead).
Yes, I think that could be useful.

2022-11-24 07:51 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +            The buffer being exposed.
I agree, but this is how it is done throughout cudf. Of cause, we could change this? `numpydoc` supports [non-typed parameters](https://numpydoc.readthedocs.io/en/latest/format.html#parameters).

cc. @shwina @galipremsagar

2022-11-24 07:56 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +        return ret[:-1]  # Remove last `\n`
True, but I like the convenience of `textwrap.indent` and I would also have to strip the newlines in `s.traceback`.

2022-11-24 08:13 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +        self.spills_totals = defaultdict(lambda: (0, 0))
Done

2022-11-24 08:21 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +        self.spills_totals = defaultdict(lambda: (0, 0))
Done

2022-11-24 08:25 UTC, madsbk commented on python/cudf/cudf/core/buffer/spill_manager.py
> +            ret += f"    {src} => {dst}: {format_bytes(nbytes)} in {time}s\n"
Done

2022-11-24 08:38 UTC, madsbk commented on python/cudf/cudf/tests/test_spilling.py
> +    assert len(manager.statistics.exposes) == 2
Added comment

2022-11-24 08:57 UTC, madsbk commented on python/cudf/cudf/tests/test_spilling.py
> +        buffers[i].ptr
It shouldn't have any consequences if it goes over the limit. `spill_device_limit` is a _soft_ limit, which I have added to the docs: d0271a51f85a7d71ad3a0982d8598f662d107343

2022-11-24 08:59 UTC, madsbk commented
@wence-, thanks for the review! I think it is ready for another round.

2022-11-24 09:34 UTC, wence- commented on python/cudf/cudf/core/buffer/spill_manager.py
> +        return ret[:-1]  # Remove last `\n`
Fair.

2022-11-25 17:20 UTC, wence- approved these changes
Very minor documentation quibbles, otherwise thanks!

2022-11-28 07:11 UTC, madsbk commented
rerun tests

2022-11-28 14:00 UTC, madsbk commented
@gpucibot merge

2022-11-28 14:00 UTC, merged

2022-11-28 14:00 UTC, madsbk commented
> Very minor documentation quibbles, otherwise thanks!

Thanks @wence- !