Patch CUB DeviceSegmentedSort and remove workaround
rapidsai/cudf pull request #12234
Opened 2022-11-23 15:09 UTC by davidwendt

## Description
Fix in CUB DeviceSegmentedSort allows for workaround to removed. The CUB fix is applied as a patch in the libcudf build process.
Reference https://github.com/NVIDIA/cub/issues/594 and #12217

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-11-28 13:59 UTC, elstehle approved these changes
Looks good. Thanks for the patch 👍

2022-11-28 13:59 UTC, robertmaynard requested changes

2022-11-28 13:59 UTC, robertmaynard commented on cpp/cmake/thirdparty/patches/thrust_override.json
> +          "fixed_in" : ""
```suggestion
          "fixed_in" : "2.1"
```

2022-11-28 14:10 UTC, robertmaynard approved these changes

2022-11-29 00:19 UTC, davidwendt commented
@gpucibot merge

2022-11-29 00:19 UTC, merged