Add cudf::strings:like function with multiple patterns
rapidsai/cudf pull request #12269
Opened 2022-11-30 17:53 UTC by davidwendt

## Description
Adds a `cudf::strings::like` function that accepts a column of patterns for matching against corresponding input string row elements.

Closes #10797 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-12-09 14:41 UTC, robertmaynard requested changes

2022-12-09 14:41 UTC, robertmaynard commented on cpp/include/cudf/strings/contains.hpp
> + * - `%` any number of any character (including no characters)
```suggestion
 * - `%` zero or more of any character
```

2022-12-09 14:41 UTC, robertmaynard commented on cpp/src/strings/like.cu
> +std::unique_ptr<column> like(strings_column_view const& input,
We should add a test for when input and pattern are both zero length.

2023-01-03 16:25 UTC, bdice approved these changes
Very clean!

2023-01-04 14:11 UTC, davidwendt commented
@gpucibot merge

2023-01-04 14:11 UTC, merged