Change reductions any/all to return valid values for empty input
rapidsai/cudf pull request #12279
Opened 2022-12-01 17:13 UTC by davidwendt

## Description

Changes reduction aggregation-all to return true for empty or all-null column.
Changes reduction aggregation-any to return false for empty or all-null column.
This is consistent with the behavior of [`std::all_of` and `std::any_of`](https://en.cppreference.com/w/cpp/algorithm/all_any_none_of)
The empty/all-null logic was simplified as well. Additional gtests added for this new behavior.

Closes #8757 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2022-12-08 14:21 UTC, bdice requested changes
I have thought about this before and I’m not sure what semantics are best. This breaks some symmetry. Perhaps we only want to return a boolean instead of a null if an initial value is supplied. Otherwise we are introducing odd behavior with respect to the monoidal structure of reductions. I can try to document this in more detail later or discuss on a call. I have notes somewhere.

2022-12-08 14:21 UTC, bdice commented on cpp/src/reductions/reductions.cpp
> +  // Returns default scalar if input column is empty or all non-valid
```suggestion
  // Returns default scalar if input column is empty or all null
```

2022-12-09 15:35 UTC, bdice commented
I wrote a comment about my views on this proposed change:
https://github.com/rapidsai/cudf/issues/8757#issuecomment-1344451607

I will remove my request for changes on this PR, but I would recommend having a bit more discussion on that issue about whether this is the right thing to do.

2022-12-09 20:51 UTC, bdice approved these changes
Code looks good. I had some reservations about the change in behavior but am okay with this in its current state after some consideration.

2022-12-10 05:40 UTC, ttnghia commented on cpp/tests/reductions/reduction_tests.cpp
> +  auto bool_type = cudf::data_type{cudf::type_id::BOOL8};
Nit: `const`?

2022-12-10 05:40 UTC, ttnghia commented on cpp/tests/reductions/reduction_tests.cpp
> +  cudf::test::fixed_width_column_wrapper<T> col_nulls = construct_null_column(col_data, valids);
Nit: `const`?

2022-12-10 05:40 UTC, ttnghia approved these changes

2022-12-12 23:14 UTC, davidwendt commented
@gpucibot merge

2022-12-12 23:15 UTC, merged