[REVIEW] Unpin `dask` and `distributed` for development
rapidsai/cudf pull request #12710
Opened 2023-02-06 19:27 UTC by galipremsagar

## Description
This PR unpins `dask` and `distributed` for `23.04` development.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-02-06 21:53 UTC, pentschev requested changes
Same as in https://github.com/rapidsai/dask-cuda/pull/1110: just to be sure, nothing has changed w.r.t. the procedure, right? We still need to wait for the actual 23.02 to release before merging this, otherwise forward merge will revert this change. Blocking for now, but please correct me if anything has changed and this can be merged immediately.

2023-02-10 14:52 UTC, pentschev approved these changes
LGTM, thanks @galipremsagar !

2023-02-10 17:28 UTC, raydouglass approved these changes

2023-02-10 17:29 UTC, galipremsagar commented
/merge

2023-02-10 17:29 UTC, merged