[WIP] Add try/except for expected null-schema error in read_parquet
rapidsai/cudf pull request #12756
Opened 2023-02-10 19:39 UTC by rjzamora

## Description
Temporary workaround for https://github.com/rapidsai/cudf/issues/12702 - Adds a try/except to concatenate distinct `cudf.read_parquet` results instead of requiring file aggregation to occur within libcudf.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-03-07 17:54 UTC, wence- requested changes
Can we test that the test is successful please? Otherwise looks good.

2023-03-07 18:26 UTC, rjzamora commented on python/dask_cudf/dask_cudf/io/tests/test_parquet.py
> +        ).compute()
yup - makes sense

2023-03-08 09:37 UTC, wence- approved these changes
Thanks!

2023-03-08 09:38 UTC, wence- commented
/merge

2023-03-08 21:21 UTC, merged