[REVIEW] Drop `Index.is_*` methods
rapidsai/cudf pull request #12909
Opened 2023-03-08 21:26 UTC by galipremsagar

## Description
This PR removes the following Index APIs to match with pandas 2.0:

- [x]  is_numeric
- [x]  is_boolean
- [x]  is_integer
- [x]  is_floating
- [x]  is_object
- [x]  is_categorical
- [x]  is_interval 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-03-10 17:28 UTC, vyasr requested changes
Still need to clean out the implementations in index.py, right?

2023-03-10 17:44 UTC, galipremsagar commented
> Still need to clean out the implementations in index.py, right?

The implementations were converted as internal APIs to be used as fast paths for `is_numeric_dtype`, `is_bool_dtype`, etc: here: https://github.com/rapidsai/cudf/pull/12820/files#diff-ef94b3e28724ebfe959cd02a9f37427cefcdc118799490453fbe1c6299dc0324R63

2023-03-10 18:06 UTC, vyasr commented
Ah OK I see. Now that these APIs are not public I think it would be better to remove those helper functions and implement the `api.types` functions in terms of a simple hash lookup (i.e. store some module-level dicts in api/types.py mapping `{cudf.$INDEX_CLASS: bool}`). If these APIs are no longer public I don't think the organization of having helper functions like this is very helpful, it just makes the code less readable and harder to maintain (and incurs unnecessary performance costs too with Python function calls). If you'd like to refactor that in a separate PR I'd be OK with that though.

2023-03-10 18:07 UTC, galipremsagar commented
> Ah OK I see. Now that these APIs are not public I think it would be better to remove those helper functions and implement the `api.types` functions in terms of a simple hash lookup (i.e. store some module-level dicts in api/types.py mapping `{cudf.$INDEX_CLASS: bool}`). If these APIs are no longer public I don't think the organization of having helper functions like this is very helpful, it just makes the code less readable and harder to maintain (and incurs unnecessary performance costs too with Python function calls). If you'd like to refactor that in a separate PR I'd be OK with that though.

Got it, it makes sense to have this kind of a refactor done in this PR itself. I'll make those changes here. 👍

2023-03-10 18:12 UTC, mroeschke commented
FWIW these were only deprecated in pandas 2.0 not removed. These will be removed in pandas 3.0

2023-03-10 18:16 UTC, galipremsagar commented
> FWIW these were only deprecated in pandas 2.0 not removed. These will be removed in pandas 3.0

Ah, my bad. So let's probably keep them deprecated and not drop them now. Will add comments to this PR about the delayed removal of these APIs.

2023-03-10 23:05 UTC, galipremsagar commented
This should be now ready for review.

2023-03-13 19:58 UTC, mroeschke approved these changes

2023-03-13 21:06 UTC, shwina approved these changes

2023-03-13 21:06 UTC, merged