Fix conda recipe post-link.sh typo
rapidsai/cudf pull request #12916
Opened 2023-03-09 14:59 UTC by pentschev

## Description

Following an internal discussion, fix a typo in conda recipe `post-link.sh`. For some conda versions relying solely on `prelink_message` is insufficient, thus this file has to still be maintained.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x ] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-03-09 15:00 UTC, robertmaynard approved these changes

2023-03-09 15:01 UTC, jjacobelli approved these changes

2023-03-09 16:11 UTC, vyasr requested changes
Blocking until we hear from @jakirkham on whether we can delete this file altogether in favor of the prelink message alone or whether the post-link script is still needed for some conda versions that we care about.

2023-03-17 21:48 UTC, vyasr approved these changes

2023-03-17 21:49 UTC, vyasr commented
/merge

2023-03-21 11:52 UTC, merged