Add string scalar support in AST
rapidsai/cudf pull request #13061
Opened 2023-04-04 22:06 UTC by karthikeyann

## Description
Adding string scalar support in AST.
A new generic scalar device view class is added in AST to support numeric, timestamp, duration and string scalars.

TBD: Register count and benchmark results.
 
Addressed part of #8858

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-04-05 12:20 UTC, karthikeyann commented
All benchmarks results are almost same.

./_deps/nvbench-src/scripts/nvbench_compare.py JOIN_NV.before.json ../../fea-string_scalar_ast_compare/release/JOIN_NV.after.json
<details>
['JOIN_NV.before.json', '../../fea-string_scalar_ast_compare/release/JOIN_NV.after.json']
# inner_join_32bit

## [0] Quadro GV100

|  Key Type  |  Payload Type  |  Nullable  |  Build Table Size  |  Probe Table Size  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |         Diff |   %Diff |  Status  |
|------------|----------------|------------|--------------------|--------------------|------------|-------------|------------|-------------|--------------|---------|----------|
|    I32     |      I32       |     0      |       100000       |       100000       | 259.062 us |       4.26% | 276.762 us |      45.22% |    17.700 us |   6.83% |   FAIL   |
|    I32     |      I32       |     0      |       100000       |       400000       | 725.774 us |      21.08% | 743.625 us |      22.41% |    17.852 us |   2.46% |   PASS   |
|    I32     |      I32       |     0      |      10000000      |      10000000      |  17.822 ms |       2.76% |  17.789 ms |       2.60% |   -32.671 us |  -0.18% |   PASS   |
|    I32     |      I32       |     0      |      10000000      |      40000000      |  47.758 ms |       1.09% |  46.829 ms |       1.32% |  -929.068 us |  -1.95% |   FAIL   |
|    I32     |      I32       |     0      |      10000000      |     100000000      | 102.037 ms |       0.49% | 102.084 ms |       0.34% |    47.677 us |   0.05% |   PASS   |
|    I32     |      I32       |     0      |      80000000      |     100000000      | 144.044 ms |       0.39% | 145.223 ms |       0.63% |     1.179 ms |   0.82% |   FAIL   |
|    I32     |      I32       |     0      |     100000000      |     100000000      | 156.077 ms |       0.29% | 155.823 ms |       0.27% |  -254.788 us |  -0.16% |   PASS   |
|    I32     |      I32       |     0      |      10000000      |     240000000      | 236.961 ms |       0.32% | 235.956 ms |       0.28% | -1004.461 us |  -0.42% |   FAIL   |
|    I32     |      I32       |     0      |      80000000      |     240000000      | 269.564 ms |       0.23% | 270.752 ms |       0.22% |     1.188 ms |   0.44% |   FAIL   |
|    I32     |      I32       |     0      |     100000000      |     240000000      | 282.870 ms |       0.07% | 282.251 ms |       0.39% |  -618.483 us |  -0.22% |   FAIL   |

# inner_join_64bit

## [0] Quadro GV100

|  Key Type  |  Payload Type  |  Nullable  |  Build Table Size  |  Probe Table Size  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |         Diff |   %Diff |  Status  |
|------------|----------------|------------|--------------------|--------------------|------------|-------------|------------|-------------|--------------|---------|----------|
|    I64     |      I64       |     0      |      40000000      |      50000000      |  76.408 ms |       1.65% |  76.398 ms |       1.21% |    -9.267 us |  -0.01% |   PASS   |
|    I64     |      I64       |     0      |      50000000      |      50000000      |  83.026 ms |       0.97% |  82.899 ms |       0.84% |  -126.140 us |  -0.15% |   PASS   |
|    I64     |      I64       |     0      |      40000000      |     120000000      | 140.004 ms |       0.36% | 140.594 ms |       0.40% |   590.421 us |   0.42% |   FAIL   |
|    I64     |      I64       |     0      |      50000000      |     120000000      | 147.258 ms |       0.48% | 146.176 ms |       0.39% | -1081.729 us |  -0.73% |   FAIL   |

# inner_join_32bit_nulls

## [0] Quadro GV100

|  Key Type  |  Payload Type  |  Nullable  |  Build Table Size  |  Probe Table Size  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |         Diff |   %Diff |  Status  |
|------------|----------------|------------|--------------------|--------------------|------------|-------------|------------|-------------|--------------|---------|----------|
|    I32     |      I32       |     1      |       100000       |       100000       | 154.781 us |       3.52% | 156.321 us |       4.37% |     1.540 us |   1.00% |   PASS   |
|    I32     |      I32       |     1      |       100000       |       400000       | 473.075 us |      24.79% | 469.674 us |      24.59% |    -3.401 us |  -0.72% |   PASS   |
|    I32     |      I32       |     1      |      10000000      |      10000000      |   8.539 ms |       6.37% |   8.428 ms |       5.81% |  -111.236 us |  -1.30% |   PASS   |
|    I32     |      I32       |     1      |      10000000      |      40000000      |  19.796 ms |       0.14% |  19.826 ms |       0.23% |    30.043 us |   0.15% |   FAIL   |
|    I32     |      I32       |     1      |      10000000      |     100000000      |  41.030 ms |      19.44% |  35.141 ms |       2.37% | -5889.844 us | -14.35% |   FAIL   |
|    I32     |      I32       |     1      |      80000000      |     100000000      |  56.136 ms |       1.88% |  56.298 ms |       2.52% |   161.466 us |   0.29% |   PASS   |
|    I32     |      I32       |     1      |     100000000      |     100000000      |  60.123 ms |       0.75% |  60.190 ms |       0.95% |    66.722 us |   0.11% |   PASS   |
|    I32     |      I32       |     1      |      10000000      |     240000000      |  99.456 ms |      11.40% |  99.462 ms |      11.46% |     6.308 us |   0.01% |   PASS   |
|    I32     |      I32       |     1      |      80000000      |     240000000      | 103.508 ms |      13.02% | 102.898 ms |      10.87% |  -610.402 us |  -0.59% |   PASS   |
|    I32     |      I32       |     1      |     100000000      |     240000000      | 102.849 ms |       6.74% | 102.108 ms |      10.80% |  -741.125 us |  -0.72% |   PASS   |

# inner_join_64bit_nulls

## [0] Quadro GV100

|  Key Type  |  Payload Type  |  Nullable  |  Build Table Size  |  Probe Table Size  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |        Diff |   %Diff |  Status  |
|------------|----------------|------------|--------------------|--------------------|------------|-------------|------------|-------------|-------------|---------|----------|
|    I64     |      I64       |     1      |      40000000      |      50000000      |  31.353 ms |       3.75% |  31.447 ms |       4.03% |   93.700 us |   0.30% |   PASS   |
|    I64     |      I64       |     1      |      50000000      |      50000000      |  33.667 ms |       1.80% |  33.536 ms |       1.67% | -130.675 us |  -0.39% |   PASS   |
|    I64     |      I64       |     1      |      40000000      |     120000000      |  51.862 ms |       2.44% |  53.442 ms |       1.18% |    1.580 ms |   3.05% |   FAIL   |
|    I64     |      I64       |     1      |      50000000      |     120000000      |  54.871 ms |       1.17% |  54.906 ms |       1.20% |   34.986 us |   0.06% |   PASS   |

# left_join_32bit

## [0] Quadro GV100

|  Key Type  |  Payload Type  |  Nullable  |  Build Table Size  |  Probe Table Size  |   Ref Time |   Ref Noise |   Cmp Time |   Cmp Noise |         Diff |   %Diff |  Status  |
|------------|----------------|------------|--------------------|--------------------|------------|-------------|------------|-------------|--------------|---------|----------|
|    I32     |      I32       |     0      |       100000       |       100000       | 311.202 us |     104.49% | 316.878 us |     101.39% |     5.676 us |   1.82% |   PASS   |
|    I32     |      I32       |     0      |       100000       |       400000       | 753.111 us |      21.89% | 753.446 us |      19.64% |     0.334 us |   0.04% |   PASS   |
|    I32     |      I32       |     0      |      10000000      |      10000000      |  18.551 ms |       3.42% |  18.842 ms |       4.04% |   291.313 us |   1.57% |   PASS   |
|    I32     |      I32       |     0      |      10000000      |      40000000      |  48.120 ms |       1.14% |  46.998 ms |       0.87% | -1122.513 us |  -2.33% |   FAIL   |
|    I32     |      I32       |     0      |      10000000      |     100000000   [...]

2023-04-05 13:05 UTC, karthikeyann commented
Compile time differences (From .ninja_log)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/knataraj/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/knataraj/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



files | branch-23.06 | ast compare | diff | %diff
-- | -- | -- | -- | --
CMakeFiles/cudf.dir/src/join/conditional_join.cu.o | 124817 | 131282 | 6465 | 5%
CMakeFiles/cudf.dir/src/join/cross_join.cu.o | 20121 | 21161 | 1040 | 5%
CMakeFiles/cudf.dir/src/join/hash_join.cu.o | 51821 | 55529 | 3708 | 7%
CMakeFiles/cudf.dir/src/join/join.cu.o | 24475 | 28093 | 3618 | 15%
CMakeFiles/cudf.dir/src/join/join_utils.cu.o | 29909 | 29496 | -413 | -1%
CMakeFiles/cudf.dir/src/join/mixed_join.cu.o | 41330 | 41197 | -133 | 0%
CMakeFiles/cudf.dir/src/join/mixed_join_kernel.cu.o | 134206 | 141358 | 7152 | 5%
CMakeFiles/cudf.dir/src/join/mixed_join_kernel_nulls.cu.o | 179307 | 188245 | 8938 | 5%
CMakeFiles/cudf.dir/src/join/mixed_join_kernels_semi.cu.o | 101032 | 106287 | 5255 | 5%
CMakeFiles/cudf.dir/src/join/mixed_join_semi.cu.o | 53062 | 52447 | -615 | -1%
CMakeFiles/cudf.dir/src/join/mixed_join_size_kernel.cu.o | 146499 | 154751 | 8252 | 6%
CMakeFiles/cudf.dir/src/join/mixed_join_size_kernel_nulls.cu.o | 189890 | 199687 | 9797 | 5%
CMakeFiles/cudf.dir/src/join/mixed_join_size_kernels_semi.cu.o | 103155 | 107622 | 4467 | 4%
CMakeFiles/cudf.dir/src/join/semi_join.cu.o | 26818 | 26362 | -456 | -2%
  |   |   |   |  
CMakeFiles/cudf.dir/src/transform/bools_to_mask.cu.o | 21477 | 22789 | 1312 | 6%
CMakeFiles/cudf.dir/src/transform/compute_column.cu.o | 97877 | 105062 | 7185 | 7%
CMakeFiles/cudf.dir/src/transform/encode.cu.o | 19075 | 20085 | 1010 | 5%
CMakeFiles/cudf.dir/src/transform/mask_to_bools.cu.o | 20944 | 20582 | -362 | -2%
CMakeFiles/cudf.dir/src/transform/nans_to_nulls.cu.o | 22563 | 23055 | 492 | 2%
CMakeFiles/cudf.dir/src/transform/transform.cpp.o | 35600 | 36611 | 1011 | 3%



</body>

</html>

2023-04-11 00:54 UTC, vyasr requested changes
The code looks fine to me. Do we have a plan for how this generic scalar can be pulled out of AST code, though? I believe there is some refactoring needed of the scalar device views for that to be possible, could we open an issue documenting that before we merge this?

2023-04-18 01:57 UTC, harrism approved these changes

2023-04-18 09:21 UTC, karthikeyann commented
Created https://github.com/rapidsai/cudf/issues/13160 to track this.

2023-04-19 19:36 UTC, vyasr approved these changes
LGTM, thanks!

2023-04-20 09:44 UTC, karthikeyann commented
/merge

2023-04-20 09:44 UTC, merged