Separate io-text and nvtext pytests into different files
rapidsai/cudf pull request #13435
Opened 2023-05-24 17:52 UTC by davidwendt

## Description
Cleans up source files for nvtext and io-text pytests. The pytests are placed into separate files: `text_io_text.py` for the io-text pytests and `text_nvtext.py` for the nvtext pytests. Also removed the `python/cudf/cudf/tests/text` folder which contained 2 empty .py files.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-05-24 18:44 UTC, davidwendt commented on python/cudf/cudf/tests/test_nvtext.py
> -
This code moved to `test_io_text.py`

2023-05-24 20:08 UTC, bdice requested changes
Can you please edit these exclude paths so that the smart quotes are retained in the new location for these tests? Thanks!

https://github.com/rapidsai/cudf/blob/19554a1429c8516f73e91065ca03ff97ffff853f/.pre-commit-config.yaml#L83-L89

2023-05-24 20:36 UTC, shwina commented
Yes, this is a good opportunity to do that.

- the "nvtext" tests should go in `cudf/tests/strings/test_string_methods.py`
- the "io-text" tests should go in `cudf/tests/input_output/test_text.py`

2023-05-24 20:57 UTC, davidwendt commented on python/cudf/cudf/tests/input_output/test_text.py
> +# Copyright (c) 2019-2023, NVIDIA CORPORATION.
Moved from `python/cudf/cudf/tests/test_text.py`

2023-05-24 20:57 UTC, davidwendt commented on python/cudf/cudf/tests/strings/test_string_methods.py
> +# Copyright (c) 2019-2023, NVIDIA CORPORATION.
Also moved from `python/cudf/cudf/tests/test_text.py`

2023-05-24 22:08 UTC, wence- commented
FWIW, the empty test file was a deliberate part of https://github.com/rapidsai/cudf/pull/12288

Not sure if we want to delete it in this change set.

2023-05-26 09:02 UTC, wence- approved these changes
Thanks @davidwendt

2023-05-26 09:03 UTC, wence- commented
/merge

2023-05-26 09:03 UTC, merged