Fix `DataFrame.mode` pytest
rapidsai/cudf pull request #13500
Opened 2023-06-02 01:17 UTC by galipremsagar

## Description
This PR xfails a condition that is failing due to a pandas bug: https://github.com/pandas-dev/pandas/issues/53497

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-06-02 15:15 UTC, wence- requested changes
Very minor fixes.

2023-06-02 15:15 UTC, wence- commented on python/cudf/cudf/tests/test_dataframe.py
> +                """,
```suggestion
            reason="https://github.com/pandas-dev/pandas/issues/53497",
```

Or, if that's too long, split the string:
```
reason=(
    "firsthalf"
    "secondhalf"
)
```

2023-06-02 15:17 UTC, galipremsagar commented on python/cudf/cudf/tests/test_dataframe.py
> +            strict=True,
Nope, `False` is the default: https://docs.pytest.org/en/7.3.x/reference/reference.html#pytest.mark.xfail

2023-06-02 21:49 UTC, mroeschke approved these changes

2023-06-05 07:58 UTC, wence- commented on python/cudf/cudf/tests/test_dataframe.py
> +            strict=True,
I mean that we have `xfail_strict=true` configured in the top-level `tests/pytest.ini`. So this _should_ be unnecessary I think.

2023-06-05 15:48 UTC, galipremsagar commented on python/cudf/cudf/tests/test_dataframe.py
> +            strict=True,
Okay, got it. Missed this config there. Removed it.

2023-06-06 08:12 UTC, wence- approved these changes
style-checks are failing due to isort issues (not introduced here, but can we just fix?)

2023-06-06 14:28 UTC, galipremsagar commented
> style-checks are failing due to isort issues (not introduced here, but can we just fix?)

Yes, I'll be opening a separate PR to fix all the style issues.

2023-06-06 14:28 UTC, merged