Update `lists::contains` to experimental row comparator
rapidsai/cudf pull request #13672
Opened 2023-07-07 18:18 UTC by divyegala

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-07-12 13:14 UTC, davidwendt commented
Looks like `src/lists/contains.cu` now takes over an hour to compile on it's own with this change.
71 minutes: https://downloads.rapids.ai/ci/cudf/pull-request/13672/e6059be/cuda12_x86_64.ninja_log.html 
86 minutes: https://downloads.rapids.ai/ci/cudf/pull-request/13672/e6059be/cuda11_aarch64.ninja_log.html

2023-07-17 20:26 UTC, mythrocks commented
This change looks good to me, barring the concern regarding the increased compile time. :/

2023-07-17 20:27 UTC, mythrocks approved these changes

2023-07-18 00:46 UTC, ttnghia commented on cpp/src/lists/contains.cu
> +struct search_list {
There is also the unused code remaining at the top of this file.

2023-07-18 00:48 UTC, ttnghia requested changes
Please provide benchmarks for supporting the changes.

2023-08-28 20:23 UTC, closed without merging