Avoid use of CUDF_EXPECTS in libcudf unit tests outside of helper functions with return values
rapidsai/cudf pull request #13812
Opened 2023-08-02 23:38 UTC by vuule

## Description
`CUDF_EXPECTS` should be used to report internal errors in libcudf. Google test framework has macros that should be used to report failures. The `ASSERT_` macros replace `CUDF_EXPECTS` as they exit the current function (not by throwing as `CUDF_EXPECTS`, but the effect is very similar).

This PR replaces the erroneous use of CUDF_EXPECTS with ASSERT_XYZ macros in unit tests.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-08-03 12:08 UTC, davidwendt commented on cpp/tests/io/arrow_io_source_test.cpp
> +    if (close_s3_func) { ASSERT_TRUE(close_s3_func().ok()); }
Seems this one should be `EXPECT_TRUE` so as to not prevent the call to `dlclose()`.

2023-08-03 12:11 UTC, davidwendt commented on cpp/tests/transpose/transpose_test.cpp
> +    ASSERT_EQ(result_view.column(i).null_count(), expected_nulls[i]);
This one seems safe to use `EXPECT_EQ` instead. Then the test will report all errors instead of just the first one.

2023-08-03 12:13 UTC, davidwendt requested changes

2023-08-03 12:13 UTC, davidwendt commented on cpp/tests/transform/row_bit_count_test.cu
> +    ASSERT_TRUE(result != nullptr && result->size() == 0);
This one does not seem like it should be stopping the entire test.

2023-08-03 12:13 UTC, davidwendt commented on cpp/tests/transform/row_bit_count_test.cu
> +    ASSERT_TRUE(result != nullptr && result->size() == 0);
Seems `EXPECT_TRUE` would be safe here.

2023-08-03 21:22 UTC, davidwendt approved these changes

2023-08-04 15:30 UTC, ttnghia approved these changes

2023-08-04 16:54 UTC, vuule commented
/merge

2023-08-04 16:54 UTC, merged