Expand JIT groupby test suite
rapidsai/cudf pull request #13813
Opened 2023-08-03 02:47 UTC by brandon-b-miller

This PR reorganizes and expands the test suite for groupby apply functions using the JIT engine to include nan cases and cases where the groups are larger than a single thread block.

2023-08-14 16:43 UTC, brandon-b-miller commented
Marking this ready for review - I am going to work on solving some of the `xfails` that came up when putting this PR, so hopefully some of them won't even be necessary by merge time.

2023-08-14 16:51 UTC, bdice reviewed
@brandon-b-miller Just to clarify, you're planning to merge this to introduce new xfailed tests, then fix them in subsequent PRs?

2023-08-14 16:51 UTC, bdice commented on python/cudf/cudf/tests/test_groupby.py
> +@pytest.mark.parametrize("dtype", ["float64"])
Should this test float32, too?

2023-08-15 16:38 UTC, brandon-b-miller commented
> @brandon-b-miller Just to clarify, you're planning to merge this to introduce new xfailed tests, then fix them in subsequent PRs?

Correct, this is my plan, based on not knowing how long it might take to fix some of these.

2023-08-17 21:56 UTC, vyasr requested changes

2023-08-17 21:56 UTC, vyasr commented on python/cudf/cudf/tests/test_groupby.py
>      np.random.seed(0)
I realize it's not quite in this PR, but having the seed be set as part of a fixture seems like a confusing and potentially misleading side effect. If you want the fixture to generate a consistent output, can you use a seeded generator instead? Here are the docs on the canonical way to do this: https://numpy.org/doc/stable/reference/random/generator.html

2023-08-17 21:56 UTC, vyasr commented on python/cudf/cudf/tests/test_groupby.py
> +    )
Writing it this way should make the group sizes more obvious.
```suggestion
    key1 = (
        [1]
        + [2] * 2
        + [3] * 3
        + [4] * 4
    )
```

2023-08-17 21:56 UTC, vyasr commented on python/cudf/cudf/tests/test_groupby.py
> +    df = df.sample(frac=1).reset_index(drop=True)
```suggestion
    df = df.sample(frac=1, ignore_index=True)
```

2023-08-17 21:56 UTC, vyasr commented on python/cudf/cudf/tests/test_groupby.py
> +    df = df.sample(frac=1).reset_index(drop=True)
```suggestion
    df = df.sample(frac=1, ignore_index=True)
```

2023-08-17 21:56 UTC, vyasr commented on python/cudf/cudf/tests/test_groupby.py
> +        with pytest.xfail(
Don't use pytest.xfail directly, use pytest.mark.xfail. More explanation: https://docs.rapids.ai/api/cudf/stable/developer_guide/testing/#conditional-xfails

2023-12-15 16:59 UTC, brandon-b-miller commented
/ok to test

2024-01-04 19:06 UTC, brandon-b-miller commented
/ok to test

2024-01-05 18:07 UTC, bdice approved these changes
A couple small cleanup requests, otherwise LGTM!

2024-01-05 18:07 UTC, bdice commented on python/cudf/cudf/tests/test_groupby.py
> +    Small dataset for testing groupby apply with jit
Can we write this comment with complete sentences / capitalization? It also feels like it's wrapped pretty harshly, like 50-60 chars / line? Same request for other comments below.

2024-01-05 18:07 UTC, bdice commented on python/cudf/cudf/tests/test_groupby.py
> +        # Feature Request:
```suggestion
        # Correlation of floating types is not yet supported:
```

2024-01-09 19:55 UTC, brandon-b-miller commented
/ok to test

2024-01-10 00:19 UTC, vyasr approved these changes

2024-01-10 00:47 UTC, brandon-b-miller commented
/merge

2024-01-10 00:47 UTC, merged