Use `cudf::thread_index_type` in `merge.cu`
rapidsai/cudf pull request #13972
Opened 2023-08-26 00:26 UTC by divyegala

## Description
This PR uses `cudf::thread_index_type` to avoid overflows.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-08-26 00:31 UTC, bdice approved these changes

2023-08-31 16:54 UTC, vyasr requested changes
One requested change, one suggestion re: stride.

2023-08-31 16:54 UTC, vyasr commented on cpp/src/merge/merge.cu
> +             cudf::thread_index_type{blockIdx.x} * cudf::thread_index_type{blockDim.x};
```suggestion
  auto tid = cudf::detail::grid_1d::global_thread_id();
```

2023-08-31 16:54 UTC, vyasr commented on cpp/src/merge/merge.cu
> +    tid += cudf::thread_index_type{blockDim.x} * cudf::thread_index_type{gridDim.x};
Maybe compute this once outside the loop and store as `stride`?

2023-08-31 17:53 UTC, vyasr commented on cpp/src/merge/merge.cu
> +    tid += cudf::thread_index_type{blockDim.x} * cudf::thread_index_type{gridDim.x};
Also if you wait for #13996 to merge you can use that function instead here. At this point we're blocked on CI by #14018 anyway.

2023-09-05 23:16 UTC, ttnghia commented on cpp/src/merge/merge.cu
> +  auto stride = detail::grid_1d::grid_stride();
`const`, and need to move it up to separate it from the other non-const vars.

2023-09-06 16:12 UTC, vyasr approved these changes

2023-09-06 16:13 UTC, divyegala commented
/merge

2023-09-06 16:13 UTC, merged