Expose streams in public strings case APIs
rapidsai/cudf pull request #14056
Opened 2023-09-07 17:29 UTC by davidwendt

## Description
Add stream parameter to public APIs:
- `cudf::strings::capitalize()` 
- `cudf::strings::title()`
- `cudf::strings::is_title()`
- `cudf::strings::to_lower()`
- `cudf::strings::to_upper()`
- `cudf::strings::swapcase()`

Reference #13744

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-09-11 17:06 UTC, vyasr requested changes
Tests please.

2023-09-12 04:39 UTC, harrism approved these changes

2023-09-18 16:39 UTC, vyasr approved these changes

2023-09-18 23:34 UTC, davidwendt commented
/merge

2023-09-18 23:34 UTC, merged