Fix `Index.difference` to match with pandas
rapidsai/cudf pull request #14053
Opened 2023-09-07 05:29 UTC by galipremsagar

## Description

This PR fixes `Index.difference` in following ways:

- [x] Fixes `name` preservation by correctly evaluating the name of two input objects, closes #14019
- [x] Fixes `is_mixed_with_object_dtype` handling that will resolve incorrect results for `CategoricalIndex`, closes #14022
- [x] Raises errors for invalid input types, the error messages are an exact match to pandas error messages for parity.
- [x] Introduce a `Range._try_reconstruct_range_index` that will try to re-construct a `RangeIndex` out of an `Int..Index` to save memory- this is on parity with pandas.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-09-07 10:07 UTC, wence- requested changes
Looks good overall, but I think there's a missing corner-case in the reconstruct logic, and cupy appears to be a bit fast than conversion to a frame for the `unique` call

2023-09-07 10:07 UTC, wence- commented on python/cudf/cudf/core/index.py
> +        if index.dtype.kind == "f":
Under some circumstances, `super().difference(...)` can already return a `RangeIndex` (e.g. `RangeIndex.difference(StringIndex)`)

2023-09-07 10:07 UTC, wence- commented on python/cudf/cudf/core/index.py
> +        unique_diffs = index.to_frame(name="None").diff()["None"].unique()
Prefer cupy?
```
In [1]: import rmm

In [2]: rmm.reinitialize(pool_allocator=True)

In [3]: import cudf
c = 
In [4]: c = cudf.RangeIndex(0, 10_000_000, 2)._as_int_index()
im
In [5]: import cupy

In [6]: %timeit cupy.unique(cupy.diff(c.values));
2.72 ms ± 3.61 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit c.to_frame(name="_").diff()["_"].unique();
4.97 ms ± 3.62 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [8]: c = cudf.RangeIndex(0, 100_000_000, 3)._as_int_index()

In [9]: %timeit cupy.unique(cupy.diff(c.values));
15 ms ± 8.33 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [10]: %timeit c.to_frame(name="_").diff()["_"].unique();
27.3 ms ± 34.5 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [11]: c = cudf.RangeIndex(0, 1000_000, 3)._as_int_index()

In [12]: %timeit cupy.unique(cupy.diff(c.values));
740 µs ± 1.31 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [13]: %timeit c.to_frame(name="_").diff()["_"].unique();
873 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

2023-09-07 18:31 UTC, mroeschke commented
Does this close https://github.com/rapidsai/cudf/issues/14013?

2023-09-07 18:32 UTC, galipremsagar commented
> Does this close #14013?

Yup. Linked to the PR.

2023-09-08 00:16 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +        unique_diffs = index.to_frame(name="None").diff()["None"].unique()
Good analysis here, switched to cupy 👍

2023-09-08 00:16 UTC, galipremsagar commented on python/cudf/cudf/core/index.py
> +        if index.dtype.kind == "f":
Added additional checks

2023-09-08 08:54 UTC, wence- approved these changes
Thanks! (Didn't know an index could have nulls!)

2023-09-08 18:36 UTC, galipremsagar commented
/merge

2023-09-08 18:36 UTC, merged