Expose stream parameter in public strings find APIs
rapidsai/cudf pull request #14060
Opened 2023-09-07 20:36 UTC by davidwendt

## Description
Add stream parameter to public APIs:

- `cudf::strings::find()`
- `cudf::strings::rfind()`
- `cudf::strings::contains()`
- `cudf::strings::starts_with()`
- `cudf::strings::ends_with()`
- `cudf::strings::findall()`
- `cudf::strings::find_multiple()`

Also cleaned up some of the doxygen comments.

Reference #13744 

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-09-11 16:54 UTC, vyasr requested changes
Could we add tests for the new stream-based APIs (see any of my recent PRs for what those should look like)? They're mostly just to be safe, but on occasion they have revealed places where we're internally not forwarding input streams along and are just passing `cudf::get_default_stream()` instead.

2023-09-18 16:40 UTC, vyasr approved these changes

2023-09-18 17:43 UTC, vuule approved these changes

2023-09-18 17:43 UTC, vuule commented on cpp/include/cudf/strings/find.hpp
>   * @param mr Device memory resource used to allocate the returned column's device memory.
missed a period :D 
```suggestion
 * @param mr Device memory resource used to allocate the returned column's device memory
```

2023-09-21 14:42 UTC, davidwendt commented
/merge

2023-09-21 14:42 UTC, merged