Make random data in Python tests deterministic
rapidsai/cudf pull request #14071
Opened 2023-09-08 19:23 UTC by vuule

## Description
Some random data generators in cuDF default to `seed=None`, which means that an OS or time dependent seed is used, leading to different test data between systems/runs.
This PR changes the default to a fixed integer so that the same data is always generated.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2023-09-11 18:21 UTC, vuule commented on python/cudf/cudf/tests/test_array_ufunc.py
> +            set_random_null_mask_inplace(arg, seed=idx)
seed=idx to ensure different null masks for different columns

2023-09-11 18:21 UTC, vuule commented
CC @galipremsagar

2023-09-13 07:55 UTC, wence- requested changes
I realise that tracking down all uses of random sampling in the test suite is a big thing, and providing a default fixed seed everywhere is a pragmatic choice to get deterministic tests, but I think I don't want to break API compatibility with pandas for the two sample calls.

2023-09-13 07:55 UTC, wence- commented on python/cudf/cudf/core/groupby/groupby.py
> +        random_state: Union[np.random.RandomState, int, None] = 1,
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** ‏I am not sure I like this change, it means that user code that previously worked to draw a sequence of independent samples from groupby objects now always returns the same result for each sample.

2023-09-13 07:55 UTC, wence- commented on python/cudf/cudf/core/indexed_frame.py
> +        random_state=1,
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** ‏Similarly here, I don't think we should set a specific seed as a default argument to sample. This is also creating a difference in the default API wrt pandas (which defaults to None https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html)

2023-09-13 07:55 UTC, wence- commented on python/cudf/cudf/datasets.py
> +def randomdata(nrows=10, dtypes=None, seed=1):
<!-- Notes are always non-blocking and simply highlight something the reader should take note of.  -->
**note (non-blocking):** ‏I am on the fence about these defaults. I suppose it is OK. Perhaps better would be to flip this to a no-default keyword only argument, forcing the caller to specify a seed:

```suggestion
def randomdata(nrows=10, dtypes=None, *, seed):
```

2025-01-06 21:09 UTC, closed without merging