Expose stream parameter in public nvtext tokenize APIs
rapidsai/cudf pull request #14317
Opened 2023-10-23 19:03 UTC by davidwendt

## Description
Add stream parameter to public APIs:

- `nvtext::tokenize()` (x2)
- `nvtext::count_tokens()` (x2)
- `nvtext::character_tokenize()` 
- `nvtext::detokenize()`
- 
Also cleaned up some of the doxygen comments and added stream gtests.

Reference #13744 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-10-24 22:13 UTC, hyperbolic2346 approved these changes

2023-10-25 22:19 UTC, bdice approved these changes

2023-10-27 03:43 UTC, karthikeyann requested changes

2023-10-27 03:43 UTC, karthikeyann commented on cpp/include/nvtext/tokenize.hpp
> + * @param input Strings column tokenize
```suggestion
 * @param input Strings column to tokenize
```

2023-10-27 03:43 UTC, karthikeyann commented on cpp/include/nvtext/tokenize.hpp
> + * @param input Strings column to use for this operation
nit: only these 2 `count_tokens` has `Strings column to use for this operation` a bit generalised argument name. others specify what it is used for. It's a matter of personal preferance and general documentation guideline. should this be changed to more specific like `Strings column to count the tokens` ?

2023-10-27 03:43 UTC, karthikeyann commented on cpp/tests/streams/text/tokenize_test.cpp
> +}
Why are there no `EXPECT*` in these unit tests?

2023-10-27 16:35 UTC, karthikeyann approved these changes

2023-10-27 17:23 UTC, davidwendt commented
/merge

2023-10-27 17:23 UTC, merged