Disable dark mode in Python docs.
rapidsai/cudf pull request #14466
Opened 2023-11-21 21:24 UTC by bdice

## Description
This PR disables dark mode in Python docs. The theme is not very legible due to its use of a custom color theme.

Closes #14463.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-11-21 21:28 UTC, bdice commented
Reviewers -- please check the docs preview before merging. I followed the docs at https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/light-dark.html to disable this but haven't rendered it locally yet.

2023-11-21 21:47 UTC, ajschmidt8 approved these changes

2023-11-21 23:00 UTC, bdice commented
This works... halfway. The button to use dark mode has been removed. However, the webpage still used dark mode if I set my system to dark mode _until_ I cleared my site data for `rapids.ai`. The PyData Sphinx theme uses local storage to store the preferred mode, so my previous "auto" preference was being saved -- I think. After this PR is merged, users may need to clear their cookies / site storage to make the site always light.

-----------------------------

Before:
![image](https://github.com/rapidsai/cudf/assets/3943761/edb32e22-5ba8-4c27-8a58-715f8b0131e9)

-----------------------------

After (light/dark switcher removed):
![image](https://github.com/rapidsai/cudf/assets/3943761/493a32ad-eb7d-40bf-ba63-85cfb33756e8)

2023-11-22 01:44 UTC, galipremsagar requested changes
Blocking merge temporarily for a simpler approach

2023-11-22 02:02 UTC, bdice commented
Closing in favor of https://github.com/rapidsai/docs/pull/456

2023-11-22 02:02 UTC, closed without merging