Add a test for issue 12773
rapidsai/cudf pull request #14529
Opened 2023-11-29 22:37 UTC by vyasr

## Description

Closes #12773.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-11-29 22:37 UTC, vyasr commented
CC @wence-

2023-11-29 22:38 UTC, galipremsagar approved these changes

2023-11-30 10:57 UTC, wence- requested changes
Thanks! Would prefer to check the output value as well.

2023-11-30 10:57 UTC, wence- commented on python/dask_cudf/dask_cudf/tests/test_join.py
> +    ddf1.merge(ddf2, left_index=True, right_index=True, how="left").compute()
Can we check for correctness please?

2023-12-07 02:25 UTC, vyasr commented on python/dask_cudf/dask_cudf/tests/test_join.py
> +    ddf1.merge(ddf2, left_index=True, right_index=True, how="left").compute()
Yup, done. Sorry for the delay.

2023-12-07 18:13 UTC, wence- approved these changes
Thanks!

2023-12-07 18:13 UTC, wence- commented
/merge

2023-12-08 01:05 UTC, merged