Change `is_.._dtype` deprecations to `DeprecationWarning` instead of `FutureWarning`
rapidsai/cudf pull request #14617
Opened 2023-12-12 18:07 UTC by galipremsagar

## Description
This PR changes all `FutureWarning`'s to `DeprecationWarning`'s to match with pandas: https://github.com/pandas-dev/pandas/pull/55703

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2023-12-12 18:16 UTC, mroeschke approved these changes

2023-12-12 19:50 UTC, vyasr requested changes

2023-12-12 19:50 UTC, vyasr commented on .pre-commit-config.yaml
Rather than removing the pre-commit filter altogether, can we instead set a `files` pattern to specifically ignore `dtypes.py`? I would still think we want to avoid `DeprecationWarning` where possible.

2023-12-13 19:23 UTC, galipremsagar commented on .pre-commit-config.yaml
Done 👍

2023-12-18 17:31 UTC, merged