API for JSON unquoted whitespace normalization
rapidsai/cudf pull request #15033
Opened 2024-02-13 00:11 UTC by shrshi

## Description
This work is a follow-up to PR #14931 which provided a proof-of-concept for using the a FST to normalize unquoted whitespaces. This PR implements the pre-processing FST in cuIO and adds a JSON reader option that needs to be set to true to invoke the normalizer. 
Addresses feature request #14865 

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-02-14 14:51 UTC, revans2 approved these changes

2024-02-22 00:22 UTC, vuule requested changes
Thank you for iterating on the tests. 
A few suggestions for the test code:

2024-02-22 00:22 UTC, vuule commented on cpp/tests/io/json_whitespace_normalization_test.cu
> +                                cudf::get_default_stream().value()));
can be simplified with make_device_uvector_async

2024-02-23 02:48 UTC, shrshi commented on cpp/tests/io/json_whitespace_normalization_test.cu
> +  CUDF_CUDA_TRY(cudaMemcpyAsync(preprocessed_host_output.data(),
Thanks, you're right - we need a sync there. Changed this to use the utility functions in `vector_factories.hpp`

2024-02-27 02:59 UTC, vuule approved these changes
:fire:

2024-02-27 18:47 UTC, robertmaynard approved these changes
Approving CMake changes

2024-02-29 17:47 UTC, bdice approved these changes

2024-02-29 19:04 UTC, revans2 approved these changes

2024-03-04 20:25 UTC, shrshi commented
/merge

2024-03-04 20:25 UTC, merged