Eliminate duplicate allocation of nested string columns
rapidsai/cudf pull request #15061
Opened 2024-02-15 00:59 UTC by vuule

## Description
Issue https://github.com/rapidsai/cudf/issues/14965

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-02-16 22:24 UTC, nvdbaranec commented on cpp/src/io/parquet/reader_impl.cpp
> +            col_sizes[pass.chunks[c].src_col_index] > 0) {
Recommend renaming this to `col_string_sizes` for clarity.

2024-02-26 19:01 UTC, ttnghia approved these changes

2024-02-26 19:02 UTC, bdice commented on cpp/src/io/parquet/reader_impl.cpp
>          cudaMemcpyAsync(static_cast<int32_t*>(out_buf.data()) + out_buf.size,
This seems like a potential bug -- using `int32_t*` here and `sizeof(size_type)` below. Shouldn't these types match?
```suggestion
        cudaMemcpyAsync(static_cast<size_type*>(out_buf.data()) + out_buf.size,
```

2024-02-26 20:08 UTC, bdice approved these changes

2024-02-26 20:43 UTC, harrism requested changes
Just one missed error handling macro. Otherwise looks good.

2024-02-26 20:43 UTC, harrism commented on cpp/src/io/parquet/reader_impl.cpp
> +        cudaMemcpyAsync(static_cast<size_type*>(out_buf.data()) + out_buf.size,
suggestion: I think this should be wrapped in `CUDF_CUDA_TRY`.

2024-02-26 22:23 UTC, harrism approved these changes
Thanks!

2024-02-29 20:01 UTC, vuule commented
/merge

2024-02-29 20:01 UTC, merged