Remove unneeded script parameters in test_cpp_memcheck.sh
rapidsai/cudf pull request #15158
Opened 2024-02-27 18:47 UTC by davidwendt

## Description
Fixes error introduced in #14992 in `test_cpp_memcheck.sh`
Extra line of parameters removed from the call to `run_cudf_memcheck_ctests.sh`

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-02-27 19:05 UTC, bdice approved these changes

2024-02-27 19:31 UTC, vyasr approved these changes

2024-02-27 19:32 UTC, vyasr requested changes

2024-02-27 19:32 UTC, vyasr commented on ci/test_cpp_memcheck.sh
>   && EXITCODE=$? || EXITCODE=$?;
Can we intend this line too? Otherwise the continuation is lost. Alternatively, maybe just merge lines 11 and 12.

2024-02-29 00:01 UTC, vyasr approved these changes

2024-02-29 00:35 UTC, jakirkham commented
/merge

(adding this proactively so it gets merged once CI passes)

2024-02-29 15:10 UTC, davidwendt commented
/merge

2024-02-29 15:10 UTC, merged

2024-02-29 19:29 UTC, jakirkham commented
Thanks all! 🙏