Revert "Use as_column instead of full"
rapidsai/cudf pull request #15235
Opened 2024-03-05 22:37 UTC by vyasr

Reverts rapidsai/cudf#14698

That change is causing a number of issues downstream that we don't want to try to resolve right now.

2024-03-05 22:38 UTC, jakirkham approved these changes

2024-03-05 22:40 UTC, galipremsagar approved these changes

2024-03-05 22:40 UTC, galipremsagar commented
/merge

2024-03-05 22:46 UTC, jakirkham reviewed
Looks like the style check fails due to copyright year ranges

2024-03-05 22:46 UTC, jakirkham commented on python/cudf/cudf/utils/utils.py
> +# Copyright (c) 2020-2023, NVIDIA CORPORATION.
```suggestion
# Copyright (c) 2020-2024, NVIDIA CORPORATION.
```

2024-03-05 22:47 UTC, mroeschke approved these changes

2024-03-05 23:36 UTC, galipremsagar commented
/merge

2024-03-06 00:11 UTC, bdice commented
Blocking merge of this reversion: https://github.com/rapidsai/cugraph/pull/4215 should fix the last known issue introduced by #14698.

2024-03-06 00:14 UTC, galipremsagar requested changes
blocking merge

2024-03-06 05:41 UTC, galipremsagar commented
Closing this as all dependent repos have been updated.

2024-03-06 05:41 UTC, closed without merging