Patch dask-expr `var` logic in dask-cudf
rapidsai/cudf pull request #15347
Opened 2024-03-20 03:22 UTC by rjzamora

## Description
The `var` logic in dask-expr relies on pandas -> numpy conversion that does not work for cudf -> cupy when null values are present. This PR copies over the custom `var` logic being used in dask-cudf for the legacy API.

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-03-20 13:51 UTC, bdice requested changes
We need to add a test in dask-cudf for the functions used in the 10min notebook.

2024-03-20 13:55 UTC, rjzamora commented
>We need to add a test in dask-cudf for the functions used in the 10min notebook.

Agreed - This is still a draft.

2024-03-20 16:50 UTC, bdice commented on python/dask_cudf/dask_cudf/expr/__init__.py
> +if QUERY_PLANNING_ON:
Merge the upstream to fix this.

2024-03-22 14:22 UTC, rjzamora commented
CI failures are due to a bad/old dask-expr version being pulled (https://github.com/dask/distributed/issues/8574)

2024-04-02 17:37 UTC, rjzamora commented
The dask/dask-expr nightly-conda situation should be fixed now. So dask-related CI *should* start passing now.

2024-04-03 22:33 UTC, bdice commented
I reran the failed CI jobs. @rjzamora Is this ready for review?

2024-04-03 22:35 UTC, bdice approved these changes
Changes look fine to me.

2024-04-03 22:35 UTC, bdice commented on python/dask_cudf/dask_cudf/expr/_expr.py
> +    # Uses the parallel version of Welford's online algorithm (Chan 79')
```suggestion
    # Uses the parallel version of Welford's online algorithm (Chan '79)
```

2024-04-03 23:08 UTC, rjzamora commented
>Is this ready for review?

Yeah, thanks @bdice !

2024-04-05 21:51 UTC, raydouglass approved these changes

2024-04-08 11:14 UTC, galipremsagar approved these changes

2024-04-08 15:20 UTC, rjzamora commented
/merge

2024-04-08 15:20 UTC, merged