Enable all tests for `arm` arch
rapidsai/cudf pull request #15402
Opened 2024-03-27 11:48 UTC by galipremsagar

## Description
This PR enables running all pytests for `arm64` jobs.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-03-27 12:18 UTC, galipremsagar commented
cc: @bdice @vyasr

2024-03-27 15:45 UTC, bdice approved these changes

2024-03-27 16:22 UTC, AyodeAwe approved these changes

2024-03-27 19:01 UTC, galipremsagar commented
Similar PRs in other repos for tracking:

https://github.com/rapidsai/cuml/pull/5824
https://github.com/rapidsai/rmm/pull/1510
https://github.com/rapidsai/raft/pull/2248
https://github.com/rapidsai/cuvs/pull/63
https://github.com/rapidsai/cucim/pull/717
https://github.com/rapidsai/cuopt/pull/1774
https://github.com/rapidsai/legate-cuml/pull/13
https://github.com/rapidsai/ucxx/pull/217
https://github.com/rapidsai/cuspatial/pull/1365

2024-03-27 19:20 UTC, vyasr requested changes
Blocking for the moment, I left some suggestions on Slack. I can approve once we decide whether or not to move forward with them (since they affect all the other repos too it's easier to discuss in Slack).

2024-04-01 17:49 UTC, bdice commented on ci/test_python_common.sh
I'm not really a fan of the changes here. @vyasr I believe you were the one that requested this. Is this what you had in mind? It feels inappropriate to have the majority of the script in an if/else block rather than having a single-purpose script for wheels and for conda testing. Perhaps we could structure this in a way that uses `source some_common_stuff.sh` for the small number of lines defining CI environment variables, but leaves the conda/wheel setup in separate scripts?

2024-04-01 17:52 UTC, bdice commented on ci/test_wheel_cudf.sh
Is this script still needed if we implement `test_python_cudf.sh wheel`? This seems redundant -- but see my other comment since I'm not sure which direction we really want to go.

2024-04-05 17:38 UTC, bdice commented on ci/test_wheel_cudf.sh
Resolving - the "unified" script was reverted.

2024-04-05 17:38 UTC, bdice approved these changes

2024-04-05 17:39 UTC, bdice commented on ci/test_python_common.sh
Resolving - the "unified" script was reverted.

2024-04-05 17:45 UTC, vyasr approved these changes

2024-04-05 17:47 UTC, galipremsagar commented
/merge

2024-04-05 19:30 UTC, merged