Migrate string `capitalize` APIs to `pylibcudf`
rapidsai/cudf pull request #15503
Opened 2024-04-10 16:22 UTC by brandon-b-miller

This PR creates the `pylibcudf.strings.capitalize` namespace and migrates the cuDF cython to use it. Depends on https://github.com/rapidsai/cudf/pull/15489

Part of https://github.com/rapidsai/cudf/issues/15162

WIP

2024-05-23 04:24 UTC, vyasr requested changes
Couple of small things, but this is nearly good to go.

2024-05-23 04:24 UTC, vyasr commented on python/cudf/cudf/_lib/pylibcudf/strings/CMakeLists.txt
> +link_to_pyarrow_headers(pylibcudf_capitalize)
We shouldn't need this anymore.
```suggestion
```

2024-05-23 04:24 UTC, vyasr commented on python/cudf/cudf/_lib/pylibcudf/strings/capitalize.pyx
> +    cdef const string_scalar* cpp_delimiters
Maybe just move this declaration to line 33 where the object is defined.

2024-05-23 04:24 UTC, vyasr commented on python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py
> +    plc_col = plc.interop.from_arrow(title_data)
Fixture :)

2024-05-23 04:24 UTC, vyasr commented on python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py
> +    plc_col = plc.interop.from_arrow(is_title_data)
Can we consolidate to a single fixture?

2024-05-28 18:17 UTC, brandon-b-miller commented on python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py
> +    )
cc @vyasr for our offline conversation about this failing test. I would have thought the latest commit that plumbed this enum would have fixed this test, but currently passing this enum to the pylibcudf API seems to have no effect, possibly due to a bug somewhere.

2024-05-28 19:45 UTC, brandon-b-miller commented on python/cudf/cudf/pylibcudf_tests/test_string_capitalize.py
> +    )
This has been resolved.

2024-05-28 22:43 UTC, vyasr approved these changes
Couple of small comments, but nothing that really requires a change. Everything looks good!

2024-05-28 22:43 UTC, vyasr commented on python/cudf/cudf/_lib/pylibcudf/libcudf/CMakeLists.txt
> +add_subdirectory(strings)
For consistency with other files I'd suggest putting this after the `rapids_cython_create_modules` call, but it doesn't really matter.

2024-05-28 22:43 UTC, vyasr commented on python/cudf/cudf/_lib/pylibcudf/strings/char_types.pxd
I'm fine leaving this as-is, but if the entire module is just the enum I sort of wonder if we shouldn't just lift it up directly into the `__init__.py/pxd` files.

2024-05-28 23:58 UTC, brandon-b-miller commented on python/cudf/cudf/_lib/pylibcudf/strings/char_types.pxd
For me the main justification for leaving it is that if I'd usually `#include` a libcudf header to make use of some API or object, I think I should expect to `import` or `cimport` it from the corresponding pylibcudf "namespace".

2024-05-29 03:49 UTC, brandon-b-miller commented
/merge

2024-05-29 03:50 UTC, merged