Use static gtest and gbench everywhere
rapidsai/cudf pull request #15534
Opened 2024-04-15 17:54 UTC by robertmaynard

## Description
Allows us to remove the gtest and gbench dependencies from our conda env for testing.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-04-15 18:07 UTC, bdice approved these changes

2024-04-16 15:13 UTC, bdice commented
I merged the upstream to get CI unblocked.

2024-04-16 20:30 UTC, vyasr requested changes
While I think this change is already safe across the rest of RAPIDS (https://github.com/rapidsai/build-planning/issues/32), I suspect we need to do a bit more work in cudf. Specifically, I think we have to address #13381. Currently libcudftestutil.a exports a public dependency on GTest. Granting that it is already a static library, that still means that consumers of it will see APIs that have use gtest. What happens if someone tries to link against libcudftestutil.a, but has compiled their code using a different version of gtest? Won't that result in incompatible binaries?

In practice the only use case I'm aware of is cuspatial, which uses rapids-cmake and we control, so it's probably not a serious issue, but unless I'm misunderstanding it is a real potential issue that is worth trying to resolve before merging this.

2024-04-17 15:08 UTC, robertmaynard commented
> While I think this change is already safe across the rest of RAPIDS ([rapidsai/build-planning#32](https://github.com/rapidsai/build-planning/issues/32)), I suspect we need to do a bit more work in cudf. Specifically, I think we have to address #13381. Currently libcudftestutil.a exports a public dependency on GTest. Granting that it is already a static library, that still means that consumers of it will see APIs that have use gtest. What happens if someone tries to link against libcudftestutil.a, but has compiled their code using a different version of gtest? Won't that result in incompatible binaries?
> 
> In practice the only use case I'm aware of is cuspatial, which uses rapids-cmake and we control, so it's probably not a serious issue, but unless I'm misunderstanding it is a real potential issue that is worth trying to resolve before merging this.

This is a great point. Using a static GTest with libcudf would mean that conda consumers would be forced to never have GTest in the conda env. I agree with you that this is not a desired outcome, and it looks like we can't move over to a static GTest for libcudf without first splitting the testing component into a separate conda package.

I am going to close this PR in that case, as that is out of scope of this change

2024-04-18 22:20 UTC, bdice approved these changes

2024-04-19 14:34 UTC, robertmaynard commented
Re-opnening this PR since we realized that by always building our own GTest, we don't need to worry about linking to a static system GTest which wasn't built with fPIC.

2024-04-19 15:13 UTC, bdice approved these changes
Re-reviewed on request. Looks good.

2024-04-19 23:02 UTC, vyasr approved these changes

2024-04-19 23:02 UTC, vyasr commented on cpp/tests/utilities/random_seed.cpp
:upside_down_face:

2024-04-19 23:03 UTC, vyasr commented
/merge

2024-04-23 17:24 UTC, robertmaynard commented on cpp/include/cudf_test/cudf_gtest.hpp
> -#ifdef GTEST_INCLUDE_GTEST_GTEST_H_
This is not needed now that we use a GTest version dowloaded via rapids-cmake. In addition the logic was incorrectly triggering on the devcontainer builds due to a system installed GTest causing us to break the internals of GTest

2024-04-23 19:03 UTC, merged