Minor fixups for future NumPy 2 compatibility
rapidsai/cudf pull request #15590
Opened 2024-04-24 10:46 UTC by seberg

These are some small fixes to be compatible with NumPy 2 python changes, as pointed out by the `ruff` with the `"NPY201"` rule-set.

I am not really happy with the `_NUMPY_SCTYPES` (reaching into what is now private, but figured that others will do so also for a while; feels like we should add a better way to do this in NumPy before removing it).
Listing the full set is also a bit ugly/convoluted, but happy to do so instead.

(I was hoping to get a bit further with testing against the NumPy 2rc, but unfortunately the `numba` dependency makes that at least difficult.)

2024-04-24 13:16 UTC, galipremsagar requested changes
We could rather drop the `np.unicode_` from our code instead of duplicating with `np.str_` because all tests have this covered.

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, True),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), True),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), True),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_, False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.str_(), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        (np.array([], dtype=np.str_), False),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        np.str_,
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        np.str_(),
```suggestion
```

2024-04-24 13:16 UTC, galipremsagar commented on python/cudf/cudf/tests/test_api_types.py
> +        np.array([], dtype=np.str_),
```suggestion
```

2024-04-24 13:30 UTC, seberg commented
> We could rather drop the np.unicode_ from our code instead of duplicating with np.str_ because all tests have this covered.

Yeah good point, should have noticed that it was just duplicating the tests.

2024-04-24 13:31 UTC, galipremsagar approved these changes

2024-04-26 18:50 UTC, galipremsagar commented
/merge

2024-04-26 18:51 UTC, merged