Expose stream parameter in public reduction APIs
rapidsai/cudf pull request #15737
Opened 2024-05-13 21:03 UTC by srinivasyadav18

## Description

Add stream parameter to public reduction APIs:

- `reduce()`
- `segmented_reduce()`
- `scan()`
- `minmax()`

Reference #13744 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-05-13 21:35 UTC, davidwendt commented
/ok to test

2024-05-13 21:35 UTC, davidwendt approved these changes

2024-05-13 21:40 UTC, mhaseeb123 approved these changes
LGTM!

2024-05-14 16:11 UTC, srinivasyadav18 commented
Hello,
3 tests are still failing. I am looking into it ;-). Any leads would be appreciated. Thanks!

2024-05-14 18:26 UTC, davidwendt requested changes

2024-05-14 18:26 UTC, davidwendt commented on cpp/tests/streams/reduction_test.cpp
> +  auto const init_scalar = cudf::make_fixed_width_scalar<int>(3);
```suggestion
  auto const init_scalar = cudf::make_fixed_width_scalar<int>(3, cudf::test::get_default_stream());
```
This is likely why the tests are failing.

2024-05-14 18:26 UTC, davidwendt commented on cpp/tests/streams/reduction_test.cpp
> +  auto const init_scalar = cudf::make_fixed_width_scalar<int>(3);
```suggestion
  auto const init_scalar = cudf::make_fixed_width_scalar<int>(3, cudf::test::get_default_stream());
```

2024-05-14 19:06 UTC, srinivasyadav18 commented
Thank you @davidwendt. Your suggestions worked out!

2024-05-14 19:14 UTC, davidwendt approved these changes

2024-05-15 18:53 UTC, vuule commented
/ok to test

2024-05-15 19:17 UTC, PointKernel approved these changes
LGTM

@srinivasyadav18 Welcome and thanks for the contribution!

Just FYI, CI is broken right now thus it will take a bit longer to merge the current PR.

2024-05-16 03:02 UTC, PointKernel commented
/merge

2024-05-16 03:03 UTC, merged