Make Series/Index.is_monotonic_*/is_unique consistently cached properties
rapidsai/cudf pull request #15751
Opened 2024-05-14 21:22 UTC by mroeschke

## Description
ref https://github.com/rapidsai/cudf/issues/5695

Appears `is_monotonic_*`, `is_unique` was sometimes cached and sometimes not. For consistency, these might as well always be `cached_properties`.

There's an argument that the `Column` version should also be cached, but that could be a follow up

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-05-14 21:39 UTC, galipremsagar requested changes
We may want to consider caching to non-numerical types only. Numerical columns are still mutable today:

With caching we will run into this issue:
```python
In [1]: import cudf

In [2]: s = cudf.Series([1, 2, 3, 4, 5])

In [4]: s.is_unique
Out[4]: True

In [5]: s[0] = 2

In [6]: s.is_unique
Out[6]: True

In [8]: s
Out[8]: 
0    2
1    2
2    3
3    4
4    5
dtype: int64
```

2024-05-15 13:46 UTC, wence- requested changes

2024-05-15 13:46 UTC, wence- commented on python/cudf/cudf/core/series.py
> +    @functools.cached_property
*issue*: `Series` objects can be updated "in-place" so you'd either want to invalidate these cached properties, or else flip back to `@property`

2024-05-15 13:46 UTC, wence- commented on python/cudf/cudf/core/single_column_frame.py
> +    def is_monotonic_decreasing(self) -> bool:
Similarly here, we're allowed to "swap out" the column and leave the same `Frame` object around (see `Frame._mimic_inplace`), so without invalidation, it's unsafe to make these objects cached properties.

2024-05-15 19:16 UTC, mroeschke commented
I forgot about the mutability of there data structures and the issues with caching. Going to close and revisit later

2024-05-15 19:16 UTC, closed without merging