Migrate expressions to pylibcudf
rapidsai/cudf pull request #16056
Opened 2024-06-18 18:50 UTC by lithomas1

## Description

xref #15162

Migrates expresions to use pylibcudf.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-06-25 00:43 UTC, vyasr requested changes
I think we should take a slightly different route here than we currently are with Literals. Instead of having the objects own both a libcudf scalar and a libcudf expression, I think we should have them own a pylibcudf Scalar and a libcudf expression. Right now the only way to construct pylibcudf Scalars is via arrow interop, but the logic that we're using in this file to generate different scalar types is essentially the same as what we would want in a Scalar constructor. Furthermore, once we do that we could replace the branching logic in this PR using a libcudf `type_dispatcher`-based approach that should make it cleaner and easier to maintain. This separation of concerns would also allow us to transparently support arrow scalars, like you asked. I realize that's a pretty big change from how this PR is currently structured, though, and I'm happy to work with you on that if you'd like!

2024-07-15 17:28 UTC, lithomas1 commented
@vyasr Let's put this in as is for now?

2024-07-15 23:52 UTC, lithomas1 commented on python/cudf/cudf/_lib/pylibcudf/expressions.pxd
> +    cdef Expression right
There was a use-after-free here previously, but it didn't get caught I think because the inputs to Operations weren't gc'ed yet.

2024-07-15 23:52 UTC, lithomas1 commented on python/cudf/cudf/_lib/pylibcudf/expressions.pxd
> +    cdef Expression right
In general, if the C++ side takes a reference, we need to hold on to the object on the Python side, right?

2024-07-15 23:52 UTC, lithomas1 commented on python/cudf/cudf/_lib/pylibcudf/expressions.pyx
> +    def __cinit__(self, value):
Punted.

2024-07-16 01:28 UTC, vyasr approved these changes
Let's merge and refactor later.

2024-07-16 01:28 UTC, vyasr commented on python/cudf/cudf/_lib/pylibcudf/expressions.pxd
> +    cdef Expression right
Yup we do, that's a good catch.

2024-07-16 14:00 UTC, wence- commented on python/cudf/cudf/_lib/pylibcudf/expressions.pyx
> +    def __cinit__(self, value):
It would be nice if we could pass a type-erased scalar to the `ast::literal` constructor, but my type-dispatching-fu is not sufficient.

2024-07-16 14:01 UTC, lithomas1 commented
/merge

2024-07-16 14:02 UTC, wence- commented
Ah, I realise I had the same high-level issue as @vyasr, it seems like you'd decided to do that separately?

2024-07-16 14:11 UTC, lithomas1 commented
> Ah, I realise I had the same high-level issue as @vyasr, it seems like you'd decided to do that separately?

Yeah, I kinda thought about this for a bit, but it's a pretty involved fix.
(but eventually, I would like this to take a pylibcudf Scalar)

Easy way out is:
Just convert everything to a pyarrow scalar and call interop on it (this is what DeviceScalar does). This is probably not good for the goal of getting pyarrow out of the Cython.

I could also try to delete the datetime/timedelta handling code in this PR.
(I don't think that gets used in cuDF Python)

The more correct way is to use the interchange mechanisms on the array object/scalar object we take in which I talked about with Vyas.

IMO, the best way to do this is to use DLPack, so we only have to support one thing.
(Not sure if we need C++ changes here, though )

2024-07-16 14:24 UTC, wence- commented
> (but eventually, I would like this to take a pylibcudf Scalar)

Why is this one so hard? I think you just need to have a big switch statement in the constructor that takes the type-erased `Scalar` object and constructs (via casting) the correct `numeric_scalar`/`timestamp_scalar`/`duration_scalar`.

Effectively you would just replace the current switch statement that dispatches on numpy-like types with one that dispatches on `scalar.type().id()`, I think.

What am I missing?

2024-07-16 14:25 UTC, wence- commented
> I could also try to delete the datetime/timedelta handling code in this PR. (I don't think that gets used in cuDF Python)

This is kind of critical for predicate pushdown in cudf-polars.

2024-07-16 16:07 UTC, wence- commented
> I think your proposed approach would work after we fixed the Scalar constructor.

Yeah, I think from the pylibcudf point of view in some sense, for the expression API, it is not (or should not be) the job of pylibcudf to help with the construction of a `Scalar` in the first place.

2024-07-16 17:08 UTC, wence- approved these changes
Thanks! Trivial grammar.

2024-07-16 17:08 UTC, wence- commented on python/cudf/cudf/_lib/pylibcudf/expressions.pyx
> +    A expression referring to data from a column in a table.
```suggestion
    An expression referring to data from a column in a table.
```

2024-07-16 17:08 UTC, wence- commented on python/cudf/cudf/_lib/pylibcudf/expressions.pyx
> +    A expression referring to data from a column in a table.
```suggestion
    An expression referring to data from a column in a table.
```

2024-07-16 20:09 UTC, lithomas1 commented
/merge

2024-07-16 22:02 UTC, merged