cudf::merge public API now support passing a user stream
rapidsai/cudf pull request #16124
Opened 2024-06-28 16:15 UTC by robertmaynard

## Description
Expands the `cudf::merge` function to support a user stream

Found as part of https://github.com/rapidsai/cudf/pull/15982 when building benchmarks

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-06-29 00:20 UTC, mhaseeb123 approved these changes

2024-06-29 00:21 UTC, mhaseeb123 commented
I think the new `STREAM_MERGE_TEST` are failing.

2024-06-29 00:32 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +  auto result = cudf::merge({left_view, right_view}, key_cols, column_order, null_precedence);
Same change at other places as well.
```suggestion
  auto result = cudf::merge({left_view, right_view}, key_cols, column_order, null_precedence);
  auto result = cudf::merge({left_view, right_view}, key_cols, column_order, null_precedence, cudf::test::get_default_stream());
```

2024-06-29 00:34 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +#include <cudf_test/column_wrapper.hpp>
```suggestion
#include <cudf_test/column_wrapper.hpp>
#include <cudf_test/default_stream.hpp>
```

2024-06-29 00:37 UTC, mhaseeb123 requested changes

2024-06-29 00:37 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +        cudf::sort(cudf::table_view({data1}), column_order, null_precedence)->release();
```suggestion
        cudf::sort(cudf::table_view({data1}), column_order, null_precedence, cudf::test::get_default_stream())->release();
```

2024-06-29 00:37 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +        {cudf::table_view({col1}), cudf::table_view({col2})}, {0}, column_order, null_precedence);
```suggestion
        {cudf::table_view({col1}), cudf::table_view({col2})}, {0}, column_order, null_precedence, cudf::test::get_default_stream());
```

2024-06-29 00:37 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +        cudf::sort(cudf::table_view({all_data->view()}), column_order, null_precedence);
```suggestion
        cudf::sort(cudf::table_view({all_data->view()}), column_order, null_precedence, cudf::test::get_default_stream());
```

2024-06-29 00:37 UTC, mhaseeb123 commented on cpp/tests/streams/merge_test.cpp
> +        cudf::sort(cudf::table_view({data2}), column_order, null_precedence)->release();
```suggestion
        cudf::sort(cudf::table_view({data2}), column_order, null_precedence, cudf::test::get_default_stream())->release();
```

2024-07-01 18:32 UTC, mhaseeb123 reviewed
Thanks for the effort. Waiting for CI tests to pass. Looks good otherwise!

2024-07-02 17:47 UTC, mhaseeb123 approved these changes

2024-07-02 19:58 UTC, vuule approved these changes

2024-07-02 20:19 UTC, robertmaynard commented
/merge

2024-07-02 20:20 UTC, merged