Align IntervalIndex APIs with pandas 2.x
rapidsai/cudf pull request #16371
Opened 2024-07-23 23:16 UTC by mroeschke

## Description
Implemented the relatively straightforward, missing APIs and raised `NotImplementedError` for the others

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-07-25 17:51 UTC, galipremsagar requested changes
Can we add pytests covering the newly implemented APIs?

2024-07-26 21:51 UTC, mroeschke commented
> Can we add pytests covering the newly implemented APIs?

Sure added in [3000f6e](https://github.com/rapidsai/cudf/pull/16371/commits/3000f6efd5cc0872e8ea93f510f705a24fb46d6c)

2024-07-31 18:49 UTC, galipremsagar approved these changes

2024-07-31 20:37 UTC, mroeschke commented
/merge

2024-07-31 20:37 UTC, merged