Update chunked parquet reader benchmarks
rapidsai/cudf pull request #16543
Opened 2024-08-13 14:39 UTC by sdrp713

## Description
This PR addresses issue #15057 by contributing the following:
- Adds a new benchmark that provides nvbench axes for both chunk_read_limit and pass_read_limit 
- Renames byte_limit to chunk_read_limit in BM_parquet_read_chunks
- Adds an nvbench axis for data_size to allow the benchmarks to operate on tables larger than 536 MB.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-08-15 17:48 UTC, ttnghia commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> +  auto const chunk_read_limit  = static_cast<cudf::size_type>(state.get_int64("byte_limit"));
It is still `byte_limit`.

2024-08-15 17:50 UTC, ttnghia commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> +  auto const data_size = static_cast<size_t>(state.get_int64("data_size"));
`data_size` was hard-coded for all benchmarks. If you want to customize data size then let's do it consistently.

2024-09-16 22:42 UTC, ttnghia commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> -constexpr size_t data_size         = 512 << 20;
Stale comment above.

2024-10-07 20:03 UTC, ttnghia approved these changes

2024-10-09 17:43 UTC, vyasr commented
/ok to test

2024-10-09 17:53 UTC, zpuller requested changes
one small nit

2024-10-09 17:53 UTC, zpuller commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> +  .set_name("parquet_read_chunks")
should this be `.set_name("parquet_read_subrowgroup_chunks")`

2025-01-28 07:31 UTC, vyasr commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> +  .set_name("parquet_read_chunks")
@sdrp713 would you mind taking another look at this?

2025-05-19 17:28 UTC, vyasr commented on cpp/benchmarks/io/parquet/parquet_reader_input.cpp
> +  .set_name("parquet_read_chunks")
Fixed.

2025-05-19 17:29 UTC, vyasr commented
/ok to test 8a38032a9359a52548867894b02f12cdee15859d

2025-05-19 17:32 UTC, zpuller approved these changes

2025-05-19 17:42 UTC, vyasr approved these changes

2025-05-19 23:34 UTC, vyasr commented
/ok to test 5932165b60ae2fba9e5da3e27412c527be56b7e3

2025-05-20 02:09 UTC, vyasr commented
/merge

2025-05-20 02:09 UTC, merged