Remove arrow dependency
rapidsai/cudf pull request #16640
Opened 2024-08-22 04:30 UTC by vyasr

## Description

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-08-22 19:54 UTC, bdice approved these changes
Looks good to me.

@vyasr Can we order this after https://github.com/rapidsai/cudf/pull/15483? I think the conflicts will be hard to understand otherwise and I don't want this change to delay #15483.

2024-08-23 18:03 UTC, jameslamb approved these changes
🎉

2024-08-26 16:10 UTC, vyasr commented on cpp/cmake/thirdparty/get_arrow.cmake
>              "ARROW_JEMALLOC OFF"
Yes that is now on line 191 in this file: https://github.com/rapidsai/cudf/pull/16640/files#diff-37169a2940bf7bc08ba411474ff544309f1baadbb3c0c3713efbb6d82c0b594fR191

2024-08-26 16:14 UTC, robertmaynard commented on cpp/cmake/thirdparty/get_arrow.cmake
>              "ARROW_JEMALLOC OFF"
Thanks! That was hard to see in the diff view

2024-08-26 16:15 UTC, robertmaynard approved these changes
CMake changes LGTM

2024-08-26 16:17 UTC, vyasr commented on cpp/cmake/thirdparty/get_arrow.cmake
>              "ARROW_JEMALLOC OFF"
Yup no worries, I can tell.

2024-08-26 17:30 UTC, jakirkham requested changes
Have noted a few changes that were missed below

2024-08-26 17:30 UTC, jakirkham commented on conda/recipes/cudf/meta.yaml
> +    - numpy >=1.23,<2.0a0
This should still be NumPy 3 as the upper bound

```suggestion
    - numpy >=1.23,<3.0a0
```

2024-08-26 17:30 UTC, jakirkham commented on conda/recipes/pylibcudf/meta.yaml
> +    - numpy >=1.23,<2.0a0
```suggestion
    - numpy >=1.23,<3.0a0
```

2024-08-26 17:34 UTC, vyasr commented
Fixed numpy pinnings.

2024-08-26 19:37 UTC, jakirkham approved these changes
Looks good. Thanks Vyas! 🙏

2024-08-27 18:03 UTC, vyasr commented
Waiting on some final confirmation that https://github.com/NVIDIA/spark-rapids-jni/pull/2357 works for the plugin and then this should be good to go.

2024-08-27 20:30 UTC, vyasr commented
/merge

2024-08-27 20:33 UTC, mythrocks commented on java/src/main/native/CMakeLists.txt
> +
👍

2024-08-27 20:33 UTC, mythrocks approved these changes
Thanks for working on this, @vyasr.  Approving, on behalf of CUDF JNI.

2024-08-27 20:33 UTC, merged

2024-09-04 20:18 UTC, ttnghia commented
I still see `cudf/cpp/cmake/thirdparty/get_arrow.cmake`. Is this needs to be removed too?

2024-09-04 22:40 UTC, vyasr commented
No. We still use arrow in tests, examples, and the JNI, and that CMake code is used in all three. In all three cases we now build and statically link to Arrow as part of the build, though, so there is no longer any library dependency in those cases. The critical change in this PR is removing the dependency from libcudf and the cudf Python modules.