Add partitioning APIs to pylibcudf
rapidsai/cudf pull request #16781
Opened 2024-09-09 22:56 UTC by mroeschke

## Description
Contributes to https://github.com/rapidsai/cudf/issues/15162

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-09-20 23:18 UTC, vyasr requested changes
Some suggestions to improve the tests and align them with existing testing patterns. They may also apply to other PRs that you have open.

2024-09-20 23:18 UTC, vyasr commented on python/pylibcudf/pylibcudf/tests/test_partitioning.py
> +    assert pa_result.equals(pa_expected)
Is there a reason you aren't using the utilities we have for this like [`assert_column_eq`](https://github.com/rapidsai/cudf/blob/branch-24.10/python/pylibcudf/pylibcudf/tests/common/utils.py#L44)? You shouldn't need to do the arrow conversions manually. Not sure if this applies to other PRs that you currently have open as well. If it does, could you update the others as well.

2024-09-20 23:18 UTC, vyasr commented on python/pylibcudf/pylibcudf/tests/test_partitioning.py
> +        plc.interop.from_arrow(pa_table),
We generally prefer putting both the arrow object and the corresponding cudf object into a combined fixture and making it have module scope. That minimizes the number of distinct GPU allocations required to run the test suite. [Here's an example](https://github.com/rapidsai/cudf/blob/branch-24.10/python/pylibcudf/pylibcudf/tests/test_reshape.py#L9). [Some older tests](https://github.com/rapidsai/cudf/blob/branch-24.10/python/pylibcudf/pylibcudf/tests/test_binaryops.py) will set those up as two separate fixtures, with the [pylibcudf fixture](https://github.com/rapidsai/cudf/blob/branch-24.10/python/pylibcudf/pylibcudf/tests/test_binaryops.py#L71) depending on the [pyarrow fixture](https://github.com/rapidsai/cudf/blob/branch-24.10/python/pylibcudf/pylibcudf/tests/test_binaryops.py#L64). That is also OK, but overall the combined fixture is a bit cleaner.

2024-09-25 17:07 UTC, Matt711 approved these changes

2024-09-25 22:58 UTC, vyasr approved these changes

2024-09-25 22:58 UTC, vyasr commented
/merge

2024-09-26 02:51 UTC, merged