Pylibcudf nvtext normalize
rapidsai/cudf pull request #17072
Opened 2024-10-12 03:59 UTC by Matt711

## Description

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-10-13 15:56 UTC, Matt711 commented
/ok to test

2024-10-13 19:18 UTC, Matt711 commented
/ok to test

2024-10-17 00:30 UTC, Matt711 commented
/ok to test

2024-10-17 19:59 UTC, bdice requested changes
Just one blocking request on the tests.

2024-10-17 19:59 UTC, bdice commented on python/pylibcudf/pylibcudf/tests/test_nvtext_normalize.py
> +    _, input_col = input_data
This is a weird pattern to have two data inputs and only use one of them. Can we make two fixtures instead?

2024-10-17 20:11 UTC, Matt711 commented
/ok to test

2024-10-17 21:06 UTC, bdice approved these changes
Please write a PR description before merging!

2024-10-17 22:06 UTC, Matt711 commented
> Please write a PR description before merging!

Thanks!

2024-10-17 22:06 UTC, Matt711 commented
/merge

2024-10-17 23:12 UTC, merged