Pylibcudf nvtext subword tokenize
rapidsai/cudf pull request #17096
Opened 2024-10-15 21:07 UTC by Matt711

## Description

Apart of #15162
## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-10-16 19:14 UTC, vyasr commented
This PR needs some conflict resolution.

2024-10-28 22:41 UTC, vyasr requested changes

2024-10-28 22:41 UTC, vyasr commented on python/cudf/cudf/core/subword_tokenizer.py
> +from pylibcudf.nvtext.subword_tokenize import (
Everywhere else I think we're just importing pylibcudf, right? Not a big deal but stylistically it would be best to match.

2024-10-30 21:53 UTC, Matt711 commented on python/pylibcudf/pylibcudf/nvtext/subword_tokenize.pyx
> +cpdef Hashed_Vocabulary load_vocabulary_file(str input):
Agreed, deleted.

2024-10-31 00:58 UTC, vyasr approved these changes

2024-10-31 03:29 UTC, Matt711 commented
/merge

2024-10-31 05:18 UTC, merged