Mukernels strings
rapidsai/cudf pull request #17286
Opened 2024-11-08 20:50 UTC by pmattione-nvidia

## Description

## Checklist
- [ ] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.

2024-12-12 18:51 UTC, vuule commented
FYI @etseidl

2024-12-13 21:55 UTC, nvdbaranec reviewed
I think one thing to do here right off the bat is to move the string stuff out of `decode_fixed.cu` and into something new like `decode_strings.cu` or the like.  

Outside the scope of this PR, I think we should spend some time cleaning up this whole folder. Things have gotten haphazard with respect to where the various decoders and support functions live.   @vuule, @etseidl   we should set up a little discussion after the new year to see if we can make things a little more uniform.

2024-12-13 23:10 UTC, nvdbaranec requested changes
More to come. Absorbing the thread/string subdivision strategy.

2024-12-13 23:10 UTC, nvdbaranec commented on cpp/src/io/parquet/decode_fixed.cu
> +      // N strings are copied at a time, with M = T / N threads per string
Very cool :)

2024-12-13 23:11 UTC, etseidl reviewed
Wow, this seems nice. Didn't find anything glaring on a fast first pass. I want to play with this some with some troublesome files and see how it goes.

2024-12-16 18:11 UTC, pmattione-nvidia commented on cpp/src/io/parquet/page_string_utils.cuh
> +    if (tidx < length) { arr[tidx] = new_tval + initial_value; }
There is no bug in the system that I know of for this, but it crashed for me locally without this sync and it debugged it to this being missing.

2024-12-16 18:13 UTC, pmattione-nvidia commented on cpp/src/io/parquet/parquet_gpu.hpp
> +  STRING_STREAM_SPLIT_LIST = (1 << 25)  // Run decode kernel for list BYTE_STREAM_SPLIT string data
Yeah we should discuss these overlaps for sure

2024-12-16 18:15 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +  page_state_s* s, state_buf* const sb, int start, int end, int t, size_t& string_output_offset)
OK, will change

2024-12-20 19:53 UTC, nvdbaranec commented on cpp/src/io/parquet/decode_fixed.cu
> +      __syncthreads();
Mild optimization:  looks like you could move the __syncthreads() down to just before the "loop over all strings in this batch" for loop below.

2024-12-20 19:53 UTC, nvdbaranec commented on cpp/src/io/parquet/decode_fixed.cu
> +    (static_cast<uint32_t>(kernel_mask_t) & STRINGS_MASK_NON_DELTA) != 0;
Couldn't hurt to move this to a helper.

2024-12-20 19:53 UTC, nvdbaranec commented on cpp/src/io/parquet/decode_fixed.cu
>      if constexpr (has_dict_t) {
Suggest just doing a single __syncthreads() after the block of ifs.

2024-12-20 19:53 UTC, nvdbaranec commented on cpp/src/io/parquet/page_decode.cuh
> +  cudf::size_type len = 0;
For the eventuality that string_index_pair becomes long-string aware, maybe:
```
using len_type = std::tuple_element<1, string_index_pair>::type;
len_type len = 0;
```

2025-01-03 22:42 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
>      if constexpr (has_dict_t) {
Well, if all of those if's are false, that would result in an extra __syncthreads() call.  Hopefully the compiler would eliminate it as redundant, but I'd rather not count on that.

2025-01-03 23:55 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +template <int block_size, bool has_lists_t, bool split_decode_t, typename state_buf>
Done

2025-01-03 23:55 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +  page_state_s* s, state_buf* const sb, int start, int end, int t, size_t& string_output_offset)
Done

2025-01-03 23:55 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +      __syncthreads();
Done

2025-01-03 23:55 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +    (static_cast<uint32_t>(kernel_mask_t) & STRINGS_MASK_NON_DELTA) != 0;
Done

2025-01-03 23:56 UTC, pmattione-nvidia commented on cpp/src/io/parquet/page_decode.cuh
> +  cudf::size_type len = 0;
Done

2025-01-07 20:28 UTC, pmattione-nvidia commented
> I think one thing to do here right off the bat is to move the string stuff out of `decode_fixed.cu` and into something new like `decode_strings.cu` or the like.
> 
> Outside the scope of this PR, I think we should spend some time cleaning up this whole folder. Things have gotten haphazard with respect to where the various decoders and support functions live. @vuule, @etseidl we should set up a little discussion after the new year to see if we can make things a little more uniform.

I've moved the strings-specific decode functions into page_string_utils.cuh

2025-01-07 21:54 UTC, etseidl commented
I'm slowly getting back up to speed after the break (and am fighting security own-goals on my workstation), but I've managed to test this with some of my existing files. For the most part it seems great and has decreased decode times 👍.

But for one file I'm having issues that need to be tracked down. @nvdbaranec do you still have the "curand" file I sent you some time ago? That's the horribly nested one with rows that span pages. I'm finding that I'm not able to read that one correctly (might be user error, so need to pin this down better on my end). If you don't have it any more I can send it again via slack so you all can test it out.

2025-01-07 21:59 UTC, pmattione-nvidia commented
> One last comment. Are there any additional benchmarks worth adding here? Something related to Ed's long-strings examples?

The main thing missing from the current benchmarks is a test for long strings; by default it's generating strings that are all < 32 chars in length.  I can add a test that increases the limit up to 128 or something.

2025-01-08 00:37 UTC, pmattione-nvidia commented
> > One last comment. Are there any additional benchmarks worth adding here? Something related to Ed's long-strings examples?
> 
> The main thing missing from the current benchmarks is a test for long strings; by default it's generating strings that are all < 32 chars in length. I can add a test that increases the limit up to 128 or something.

This is now added.

2025-01-08 01:14 UTC, etseidl commented
Still running this to ground...I've found that the string offsets for the pages that I believe contain part of a single row are all 0. I'm not sure if the string data is copied for those pages yet or not.

2025-01-08 17:11 UTC, etseidl commented on cpp/src/io/parquet/decode_fixed.cu
>    if (s->num_rows == 0) { return; }
```suggestion
```

This. The check for whether to process the page is already done in `setupLocalPageInfo`. This check is at best redundant, and at worst (in the case of rows that span pages) causing entire pages to be skipped that should be processed.

2025-01-08 17:32 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
>    if (s->num_rows == 0) { return; }
Ooh yikes

2025-01-08 17:33 UTC, etseidl commented on cpp/src/io/parquet/decode_fixed.cu
>    if (s->num_rows == 0) { return; }
yep :smile:

2025-01-08 21:54 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
>    if (s->num_rows == 0) { return; }
[Fix PR. ](https://github.com/rapidsai/cudf/pull/17699)

2025-01-09 19:23 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
>    if (s->num_rows == 0) { return; }
This is now merged in to cudf 25.02 and this branch.

2025-01-09 21:56 UTC, nvdbaranec approved these changes

2025-01-13 17:37 UTC, ttnghia commented on cpp/src/io/parquet/decode_fixed.cu
> +#include <cooperative_groups.h>
Why do we need this? I don't see any new code using it.

2025-01-13 17:39 UTC, pmattione-nvidia commented on cpp/src/io/parquet/decode_fixed.cu
> +#include <cooperative_groups.h>
The call to gpuInitStringDescriptors() needs cooperative_groups::this_thread_block().

2025-01-13 19:55 UTC, vuule reviewed
looks great, just one possible suggestion

2025-01-13 19:55 UTC, vuule commented on cpp/src/io/parquet/page_string_utils.cuh
> +      __shared__ int lengths[block_size];
would it make sense to place these in a union with `scan_storage`? Looks like they're not used at the same time.

2025-01-13 20:18 UTC, pmattione-nvidia commented on cpp/src/io/parquet/page_string_utils.cuh
> +      __shared__ int lengths[block_size];
Hmm, you're right, but I try to avoid using unions when I can.  Instead I've scoped scan_storage so that the compiler can more easily see that they don't overlap and the memory can be reused.

2025-01-13 20:53 UTC, kingcrimsontianyu commented on cpp/src/io/parquet/page_decode.cuh
> +inline __device__ string_index_pair gpuGetStringData(page_state_s* s, state_buf* sb, int src_pos)
Is there a reason `inline` is used here? The function is template, so I'm not sure how ODR can be violated.

2025-01-13 22:09 UTC, pmattione-nvidia commented on cpp/src/io/parquet/page_decode.cuh
> +inline __device__ string_index_pair gpuGetStringData(page_state_s* s, state_buf* sb, int src_pos)
It makes no difference one way or the other, but I'll remove it.

2025-01-13 23:06 UTC, vuule commented on cpp/src/io/parquet/page_string_utils.cuh
> +      __shared__ int lengths[block_size];
Not a big deal. Just making sure we're not leaving perf on the table after all the effort to optimize this.

2025-01-13 23:06 UTC, vuule approved these changes

2025-01-15 16:09 UTC, pmattione-nvidia commented
/merge

2025-01-15 16:09 UTC, merged