Expose stream-ordering in copying APIs
rapidsai/cudf pull request #17435
Opened 2024-11-25 12:19 UTC by shrshi

## Description
Adds stream parameter to
```
cudf::contiguous_split
cudf::chunked_pack::chunked_pack
cudf::chunked_pack::create
cudf::pack
```
Added stream gtests to verify correct stream forwarding.

Reference: https://github.com/rapidsai/cudf/issues/13744

## Checklist
- [X] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [X] New or existing tests cover these changes.
- [X] The documentation is up to date with these changes.

2024-11-26 15:23 UTC, davidwendt approved these changes

2024-11-26 17:14 UTC, ttnghia commented on java/src/main/native/src/TableJni.cpp
> +                     : cudf::get_current_device_resource_ref();
How can this variable be assigned to values of different types?

2025-01-14 16:57 UTC, shrshi commented on java/src/main/native/src/TableJni.cpp
> +                     : cudf::get_current_device_resource_ref();
Thanks for pointing this out - we can directly pass the current device resource ref to chunked pack.

2025-01-14 17:02 UTC, abellina requested changes

2025-01-14 17:02 UTC, abellina commented on java/src/main/native/src/TableJni.cpp
> +    auto chunked_pack         = cudf::chunked_pack::create(*n_table, bounce_buffer_size);
We, in spark, rely on the custom resource passed here. We would like to be able to pass a custom memory resource that guarantees we won't allocate memory at runtime during spill (where we use chunked pack)

2025-01-14 17:02 UTC, abellina commented on java/src/main/native/src/TableJni.cpp
> +                     : cudf::get_current_device_resource_ref();
we need to be able to pass this memory resource to chunked pack to be different than the default MR.

2025-01-14 17:15 UTC, shrshi commented on java/src/main/native/src/TableJni.cpp
> +    auto chunked_pack         = cudf::chunked_pack::create(*n_table, bounce_buffer_size);
Okay thank you for clarifying. I've reverted the changes and retained the memory resource pointer passed.

2025-01-14 17:28 UTC, abellina commented on java/src/main/native/src/TableJni.cpp
> +    auto chunked_pack         = cudf::chunked_pack::create(*n_table, bounce_buffer_size);
this used `rmm::mr::device_memory_resource`, and we know that's what we are passing to it because we create it. Is that OK here? Will the type of `temp_mr` be `device_async_resource_ref` and use the stream apis for alloc/free?

2025-01-14 17:47 UTC, abellina commented on java/src/main/native/src/TableJni.cpp
> +    auto chunked_pack         = cudf::chunked_pack::create(*n_table, bounce_buffer_size);
thinking about this more, and discussing with others, what is likely happening then is that the `device_memory_resource*` is getting passed to a ctr in `device_async_resource_ref`. If it compiles, then it should be OK (until this ctr is marked as `explicit`). This seems fine, so it's more of a stylistic thing.

2025-01-14 17:49 UTC, abellina approved these changes

2025-01-14 19:40 UTC, shrshi commented on java/src/main/native/src/TableJni.cpp
> +    auto chunked_pack         = cudf::chunked_pack::create(*n_table, bounce_buffer_size);
Yes, you're right. The device memory resource pointer is being implicitly cast here to device async resource ref by the basic resource ref constructor. 
I think I misunderstood @ttnghia 's comment above for `temp_mr` since the ternary operator returns either a resource ref or a device memory resource pointer. We can call the `cudf::get_current_device_resource()` instead so that the types are consistent.

2025-01-14 20:19 UTC, abellina commented on java/src/main/native/src/TableJni.cpp
> +                     : cudf::get_current_device_resource();
why do we need this change?

2025-01-14 21:01 UTC, shrshi commented on java/src/main/native/src/TableJni.cpp
> +                     : cudf::get_current_device_resource();
`cudf::get_current_device_resource()` returns a device memory resource pointer (`rmm::mr::device_memory_resource*`) while `cudf::get_current_device_resource_ref()` returns a `device_async_resource_ref`.
This change is to address Nghia's comment about assigning a variable to values of different types (https://github.com/rapidsai/cudf/pull/17435#discussion_r1858945529). `temp_mr` is now of type `rmm::mr::device_memory_resource*`, and when it is passed to `chunked_pack::create`, it is implicitly cast to a resource ref by the `basic_resource_ref` constructor.

2025-01-15 07:11 UTC, shrshi commented
/merge

2025-01-15 07:11 UTC, merged