Pylibcudf aggregation serialization
rapidsai/cudf pull request #17469
Opened 2024-11-28 21:14 UTC by pentschev

## Description
Support `Aggregation` serialization in pylibcudf. This is required to provide distributed support for cudf-polars.

Unfortunately, serialization of the `Aggregation` class requires access to implementation details in libcudf, so those needed to be exposed to Cython. Fortunately, all the attributes required are already public so there are no changes required in libcudf.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-11-29 19:56 UTC, pentschev commented
The CI errors look related to this PR but I don't think they are in fact. I can locally reproduce them _only_ with upstream Dask/Distributed, but not with `dask=2024.11.2 distributed=2024.11.2 dask-expr=1.1.19`, it is also reproducible with `branch-25.02` without changes from this PR.

2024-12-19 02:11 UTC, vyasr requested changes

2024-12-19 02:11 UTC, vyasr commented on python/pylibcudf/pylibcudf/aggregation.pyx
> +        if self.kind() is Kind.SUM:
Can we replace this cascade with a singledispatch helper function? It's a lot of clauses to fail through in the worst case.

2024-12-19 02:11 UTC, vyasr commented on python/pylibcudf/pylibcudf/libcudf/aggregation.pxd
> +        namespace "cudf::detail" nogil:
Hmm we don't expose pretty much any cudf detail APIs to pylibcudf, and I don't want to start here. Can we open an issue about these? If these are attributes that are absolutely necessary to reconstruct the serialized types, then we should discuss exposing them publicly in libcudf.

2025-02-13 19:09 UTC, rjzamora commented
@pentschev - I think we can close this now that our current strategy is to avoid serializing these kinds of objects. (Just want to confirm before closing myself)

2025-02-14 11:00 UTC, closed without merging

2025-02-14 11:00 UTC, pentschev commented
@rjzamora agreed. Closing.