update telemetry actions to fluent-bit friendly style
rapidsai/cudf pull request #17615
Opened 2024-12-17 19:09 UTC by msarahan

Simplifies telemetry a bit. More details at https://github.com/rapidsai/shared-actions/pull/28.

Telemetry will still not be collected until @ajschmidt8 enables the TELEMETRY_ENABLED environment variable for this repo.

2024-12-17 22:14 UTC, msarahan commented
re-running CI now that TELEMETRY_ENABLED=true (this is an org-level env var that @ajschmidt8 enabled here)

2024-12-17 22:21 UTC, bdice approved these changes

2024-12-17 22:23 UTC, bdice requested changes
Is this missing `runs-on: linux-amd64-cpu4`?

2024-12-18 00:29 UTC, bdice approved these changes

2024-12-18 03:17 UTC, merged