Use Numba Config to turn on Pynvjitlink Features
rapidsai/cudf pull request #17628
Opened 2024-12-19 08:28 UTC by isVoid

## Description
Numba-cuda 0.0.18+ merged in a new feature and made the old way of patching linker with pynvjitlink's `patch_numba_linker` no longer usable by downstream libraries. The current state of Numba-cuda requires that downstream libraries to enable pynvjitlink features only via `CUDA_ENABLE_PYNVJITLINK` environment variable. A recent PR https://github.com/NVIDIA/numba-cuda/pull/91 makes it so that the features can be turned on by a config variable at runtime. 

This PR is an integration test with that PR and changing the way how pynvjitlink is enabled in cuDF. It enables cuDF to use Numba-cuda since 0.2.0+ (which contains the config change).

Supercedes https://github.com/rapidsai/cudf/pull/17359/
## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.

2024-12-23 15:51 UTC, bdice commented on dependencies.yaml
> +          - &numba-cuda-dep numba-cuda>=0.2.0
We may want to keep an upper bound here. Numba-cuda is not stable yet, afaik.

2024-12-23 21:01 UTC, pentschev approved these changes
There's a suggestion from Bradley, but otherwise LGTM. Thanks @isVoid .

2024-12-30 18:14 UTC, vyasr requested changes
#17359 also has some changes in aggregation.pyx, do we not need those?

2024-12-31 03:19 UTC, isVoid commented
> #17359 also has some changes in aggregation.pyx, do we not need those?

I think those changes are to avoid importing any of `cudf.utils.cudautils` (which transitively imports numba.cuda) in the cudf startup phase. We don't want that because before https://github.com/NVIDIA/numba-cuda/pull/91, MVC mode is enabled via setting the `ENABLE_PYNVJITLINK` numba config before importing numba-cuda. With that PR merged, we removed such ordering requirement, aka, we can either import numba-cuda first, then change the config to enable/disable nvjitlinker when needed; Or change the setting, then import numba-cuda.

2024-12-31 07:53 UTC, isVoid commented
The `doc-build` CI job is failing:
```
dumping search index in English (code: en)... done
dumping object inventory... done
build finished with problems, 21 warnings (with warnings treated as errors).
make: *** [Makefile:20: dirhtml] Error 1
/__w/cudf/cudf
```

2024-12-31 16:43 UTC, vyasr commented
> But I don't see any warnings output in the CI. Are there any warning suppression in the CI?

No, you probably just need to scroll up further. There are a set of warnings printed after all the "reading sources" lines in before all of the "writing output" lines. 

I see them [here](https://github.com/rapidsai/cudf/actions/runs/12555455166/job/35006434945?pr=17628#step:10:3418), but they look odd and completely unrelated to the changes in this PR so I am skeptical of how meaningful they are. I've kicked off a rerun to see if they show up again.

2025-01-04 19:11 UTC, bdice requested changes

2025-01-04 19:11 UTC, bdice commented on dependencies.yaml
> +              - numba-cuda==0.2.0
This is backwards. The "latest" configuration should use `*numba-cuda-dep`, and the "oldest" configuration should use `numba-cuda==0.2.0`.

2025-01-06 02:47 UTC, isVoid commented on dependencies.yaml
> +              - numba-cuda==0.2.0
Fixed in https://github.com/rapidsai/cudf/pull/17628/commits/617ad0c03d1f6f396b84cdf615f144760a3910a1

2025-01-06 06:42 UTC, isVoid commented
> > But I don't see any warnings output in the CI. Are there any warning suppression in the CI?
> 
> No, you probably just need to scroll up further. There are a set of warnings printed after all the "reading sources" lines in before all of the "writing output" lines.
> 
> I see them [here](https://github.com/rapidsai/cudf/actions/runs/12555455166/job/35006434945?pr=17628#step:10:3418), but they look odd and completely unrelated to the changes in this PR so I am skeptical of how meaningful they are. I've kicked off a rerun to see if they show up again.

I think this is a related issue: https://github.com/sphinx-doc/sphinx/issues/12589. This suggest there maybe 2 sources of cause for this warning, one is using `automodule` inside the `autosummary` directive, the other is using `default_role=autolink` for sphinx configuration. I'm not sure either is applicable to cuDF though.

2025-01-09 17:11 UTC, bdice approved these changes

2025-01-09 18:07 UTC, vyasr approved these changes

2025-01-09 18:07 UTC, vyasr commented
/merge

2025-01-09 18:08 UTC, merged