Implement `HOST_UDF` aggregation for reduction and segmented reduction
rapidsai/cudf pull request #17645
Opened 2024-12-20 19:25 UTC by ttnghia

Following https://github.com/rapidsai/cudf/pull/17592, this enables `HOST_UDF` aggregation in reduction and segmented reduction, allowing to execute a host-side user-defined function (UDF) through libcudf aggregation framework.

Closes https://github.com/rapidsai/cudf/issues/16633.

2024-12-20 23:48 UTC, ttnghia commented on cpp/include/cudf/aggregation/host_udf.hpp
> +                                    device_span<size_type const>>;
How about making two tiers of base classes?
```
// For type erasure: storing `std::unique_ptr<host_udf_base>` by the same way in the internal class
struct host_udf_base {};

// define the required functions
struct reduction_host_udf_base: host_udf_base { };
struct segmented_reduction_host_udf_base: host_udf_base { };
struct groupby_host_udf_base: host_udf_base { };
```

The users will subclass from each of these 3 base classes separately. These base class will not mix their data at all.

2024-12-28 17:20 UTC, ttnghia commented on cpp/include/cudf/aggregation/host_udf.hpp
> +                                    device_span<size_type const>>;
Done. The interfaces for reduction and segmented reduction now are very simple since they do not have any optional input data.

2024-12-29 17:50 UTC, ttnghia commented
The logic for `host_udf_base` interface is changed in this PR. Instead of one universal interface for aggregation contexts (groupby/reduction/segmented reduction) as designed in the previous work, now there are three separate interfaces for them. Implementation for each context needs to derive from the corresponding interface.

Because the interfaces are no longer designed to be universal for all contexts, they are much simpler, avoiding potential bugs due to universal usage of one interface for different contexts etc.

2025-01-07 17:44 UTC, nvdbaranec requested changes
Quick first pass.

2025-01-07 17:44 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> +   * @brief Perform computing a built-in groupby aggregation and access its result.
```suggestion
   * @brief Compute a built-in groupby aggregation and access its result.
```

2025-01-07 17:44 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> +  std::unordered_map<groupby_data, std::function<groupby_data_t(void)>> data_assessor_callbacks;
Seems like this should probably be `data_accessor_callbacks`

2025-01-07 17:44 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> +  std::function<column_view(std::unique_ptr<aggregation>)> aggregation_assessor_callback;
Same as above. `accessor` seems to be more correct.

2025-01-07 18:18 UTC, ttnghia commented on cpp/include/cudf/aggregation/host_udf.hpp
> +  std::unordered_map<groupby_data, std::function<groupby_data_t(void)>> data_assessor_callbacks;
Oh yes :smile:

2025-01-07 18:40 UTC, ttnghia commented on java/src/main/java/ai/rapids/cudf/Aggregation.java
> + *  Copyright (c) 2020-2025, NVIDIA CORPORATION.
Change the copyright header for the files that were forgotten in the previous PR. Github CI seems does not check on Java files.

2025-01-08 19:57 UTC, nvdbaranec requested changes

2025-01-08 19:57 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> + * the users' UDF implementation. These function are required for libcudf aggregation framework
```suggestion
 * the users' UDF implementation. These functions are required for libcudf aggregation framework
```

2025-01-08 19:57 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> +  friend struct host_udf_groupby_base;
Why have this restriction? In the admittedly unlikely case where we have some new udf aggregation base type, they're just going to come in here and add the `friend` declaration anyway.

2025-01-08 19:57 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> + * operations.
```suggestion
 * @brief The interface for host-based UDF implementation for reduction contexts.
 *
 * An implementation of host-based UDF for reduction needs to be derived from this class.
 * In addition to implementing the virtual functions declared in the base class `host_udf_base`,
 * such derived classes must also define the `operator()` function to perform reduction
 * operations.
```

2025-01-08 19:57 UTC, nvdbaranec commented on cpp/include/cudf/aggregation/host_udf.hpp
> +   *        element in the segment is valid
Param ordering is backwards.

2025-01-08 23:22 UTC, ttnghia commented on cpp/include/cudf/aggregation/host_udf.hpp
> +  friend struct host_udf_groupby_base;
This restriction is to prevent the users from deriving from `host_cudf_base`. They must derive from one of these 3 base structs above.

2025-01-10 09:52 UTC, sperlingxx commented on java/src/main/java/ai/rapids/cudf/ReductionAggregation.java
> +                                                NullEquality nullEquality, NaNEquality nanEquality) {
Is this style adjustment necessary?

2025-01-10 15:22 UTC, KyleFromNVIDIA approved these changes
Approved trivial CMake changes

2025-01-10 15:39 UTC, ttnghia commented on java/src/main/java/ai/rapids/cudf/ReductionAggregation.java
> +                                                NullEquality nullEquality, NaNEquality nanEquality) {
I think so. This is what the IDE automatically reformat. I checked other files and this seems consistent. For example: https://github.com/rapidsai/cudf/blob/a6b969993fe7afc6db21c626a0b9d241e55afb95/java/src/main/java/ai/rapids/cudf/ColumnVector.java#L151-L153

2025-01-10 18:24 UTC, PointKernel approved these changes
I'm really happy with the final outcome of this PR. The finalized APIs are much more accessible and user-friendly. I appreciate your prompt responses to the review comments and the time you took for offline discussions to address all my concerns and answer my questions.

Looks good to me!

2025-01-10 18:24 UTC, PointKernel commented on cpp/include/cudf/aggregation/host_udf.hpp
> + *     auto const offsets = get_data<groupby_data::GROUP_OFFSETS>();
```suggestion
 *     auto const values = get_grouped_values();
 *     auto const offsets = get_group_offsets();
```
nit: update docs

2025-01-13 16:24 UTC, nvdbaranec approved these changes

2025-01-13 17:27 UTC, merged