Update page_data.cu
rapidsai/cudf pull request #6066
Opened 2020-08-21 06:35 UTC by goodengineer

batch size multiple definitions extracted to 1 macro; a few small typo fixes; attempt to shrink memory consumption by definint part of intermediate variables as short; ...proposal...

2020-08-21 06:35 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-08-21 06:35 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-08-21 06:35 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-08-24 16:00 UTC, karthikeyann requested changes
Compare register usage.

2020-08-24 16:00 UTC, karthikeyann commented on cpp/src/io/parquet/page_data.cu
> +    batch_len = min(num_input_values - value_count, BATCH_SZ); //defined in parquet_common.h
`BATCH_SZ` can't be found in https://github.com/goodengineer/cudf/blob/patch-4/cpp/src/io/parquet/parquet_common.h

2020-08-24 16:00 UTC, karthikeyann commented on cpp/src/io/parquet/page_data.cu
> +  short input_row_count = s->input_row_count;
Does this shrink memory consumption?
For resource usage, after compilation 
`cuobjdump  --dump-resource-usage ./CMakeFiles/cudf.dir/src/io/parquet/page_data.cu.o | c++filt`
Compare.

2020-09-09 02:37 UTC, harrism commented
We have a major overhaul of all of cuIO underway. Since one of the tasks in that overhaul is to eliminate magic numbers and macros, I think we should close this.

2020-09-09 02:37 UTC, closed without merging