[WIP] Refactor `read_json_args` and `read_avro_args`
rapidsai/cudf pull request #6099
Opened 2020-08-26 20:53 UTC by rgsl888prabhu

#5962

2020-08-26 20:54 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-08 13:35 UTC, mike-wendt approved these changes

2020-09-09 15:38 UTC, davidwendt approved these changes
This looks good.

2020-09-09 20:39 UTC, rgsl888prabhu commented
rerun tests

2020-09-09 21:49 UTC, kkraus14 requested changes

2020-09-09 21:49 UTC, kkraus14 commented on python/cudf/cudf/_lib/avro.pyx
> +        build()
```suggestion
        avro_reader_options.builder(make_source_info([datasource]))
        .columns(c_columns)
        .skip_rows(<size_type> skip_rows)
        .num_rows(<size_type> num_rows)
        .build()
```

2020-09-09 21:49 UTC, kkraus14 commented on python/cudf/cudf/_lib/json.pyx
> +        build()
```suggestion
        json_reader_options.builder(make_source_info([path_or_data]))
        .dtypes(c_dtypes)
        .compression(c_compression)
        .lines(c_lines)
        .byte_range_offset(c_range_offset)
        .byte_range_size(c_range_size)
        .build()
```

2020-09-09 22:51 UTC, nvdbaranec requested changes

2020-09-10 01:26 UTC, kkraus14 approved these changes

2020-09-10 14:14 UTC, rgsl888prabhu commented on cpp/include/cudf/io/readers.hpp
>  namespace detail {
These files will be removed at the end of refactoring, so doesn't matter.

2020-09-10 14:59 UTC, nvdbaranec approved these changes

2020-09-10 20:05 UTC, merged