[WIP] Replace cuio macros
rapidsai/cudf pull request #6181
Opened 2020-09-09 13:08 UTC by kaatish

Addresses #5211. Remove as many macros from cuio as possible. This is done by replacing them with constexpr, inline functions, classes or recursive templated classes.

2020-09-09 13:08 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-09 13:23 UTC, jrhemstad requested changes
Can this be broken up at least based on the file format? This is a lot to review otherwise.

2020-09-09 15:52 UTC, vuule commented
> Can this be broken up at least based on the file format? This is a lot to review otherwise.

Jake, is this necessary? The vast majority of changes is trivial to review (renaming, adding enum scope, etc.).
There's a couple hundred lines of complex code replacing XYZ_BEGIN_STRUCT() and related macros, everything else looks like it can be reviewed very quickly.

2020-09-09 16:01 UTC, jrhemstad commented on cpp/src/io/avro/avro_gpu.cu
> +constexpr uint32_t max_shared_schema_len = 1000;
Instead of making these global variables, they should be non-type template parameters to the `gpuDecodeAvroColumnData` kernel.

2020-09-09 16:02 UTC, jrhemstad commented
> Jake, is this necessary? The vast majority of changes is trivial to review (renaming, adding enum scope, etc.).
> There's a couple hundred lines of complex code replacing XYZ_BEGIN_STRUCT() and related macros, everything else looks like it can be reviewed very quickly.

Depends on what the goal is. If you just want to do a simple find/replace of macros with global `constexpr` variables, then I guess not. But I don't think that's really very valuable. We should be looking at how the macros were being used and evaluate if it should be done better. Here's a tiny example: https://github.com/rapidsai/cudf/pull/6181/files#r485726411

I think the PR as it is now is too large for this kind of more thoughtful review and refactoring.

2020-09-09 16:06 UTC, jrhemstad commented on cpp/src/io/comp/cpu_unbz2.cpp
> +}
How about this instead. 
```suggestion
template <typename T>
inline std::enable_if_t< sizeof(T) = 4, T> byte_swap(T val)
{
  return __builtin_bswap32(val);
}

template <typename T>
inline std::enable_if_t<sizeof(T) = 8, T>  byte_swap(T val)
{
  return __builtin_bswap64(val);
}
```

2020-09-09 16:14 UTC, vuule commented on cpp/src/io/utilities/block_utils.cuh
>  #if (__CUDACC_VER_MAJOR__ >= 9)
We don't support versions below 10.1, so this condition and the else branch can be removed.

2020-09-09 16:26 UTC, kaatish commented
> Can this be broken up at least based on the file format? This is a lot to review otherwise.

@jrhemstad I could also split it into two PRs. One that converts macros into constexpr and inline functions. The other would handle the complex macros.

2020-09-21 23:19 UTC, karthikeyann requested changes

2020-09-23 16:23 UTC, closed without merging