[WIP] Remove cxx11 abi handling from CMake
rapidsai/cudf pull request #6209
Opened 2020-09-11 17:19 UTC by kkraus14

We historically had a CMake variable to control the cxx11 ABI as we used to build against old ABI projects in Ubuntu, which by default uses the new ABI. This removes this option from the CMake as its no longer used.

If someone absolutely needs the old ABI they can still manually pass in compilers flags via variables like `CMAKE_C_FLAGS`, `CMAKE_CXX_FLAGS`, `CMAKE_CUDA_FLAGS`, etc.

2020-09-11 17:20 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-11 21:18 UTC, kkraus14 commented
CI failure is from a flaky jit multiprocess test.

2020-09-14 13:25 UTC, jlowe approved these changes

2020-09-14 14:50 UTC, jlowe requested changes
I just noticed `CONTRIBUTING.md` references the `CMAKE_CXX11_ABI` flag that is being removed, that should be updated as well.

2020-09-14 15:29 UTC, kkraus14 commented
> I just noticed `CONTRIBUTING.md` references the `CMAKE_CXX11_ABI` flag that is being removed, that should be updated as well.

Fixed as well as handling some `libcudf_kafka` stuff I missed as well.

2020-09-14 15:31 UTC, jlowe approved these changes

2020-09-14 16:36 UTC, kkraus14 commented
cc @harrism to review

2020-09-14 18:22 UTC, jakirkham commented on conda/recipes/libcudf/meta.yaml
> +    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
Would suggest pinning to the patch release as they include the patch release in the SONAME as well.

```suggestion
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
```

https://abi-laboratory.pro/index.php?view=timeline&l=boost

2020-09-14 18:22 UTC, jakirkham commented on conda/recipes/libcudf/meta.yaml
> +    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
Lol fixed after clicking submit. Marking as resolved

2020-09-14 18:22 UTC, jakirkham approved these changes

2020-09-14 18:39 UTC, jakirkham commented on conda/recipes/libcudf/meta.yaml
> +    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
Note this is needed as `boost-cpp` doesn't currently have `run_exports` ( https://github.com/conda-forge/boost-cpp-feedstock/pull/82 ).

2020-09-14 18:47 UTC, raydouglass approved these changes

2020-09-14 21:42 UTC, jrhemstad approved these changes

2020-09-14 22:24 UTC, harrism approved these changes

2020-09-14 22:25 UTC, merged