Renamed skip_rows parameter to skiprows
rapidsai/cudf pull request #6353
Opened 2020-09-29 22:17 UTC by skirui-source

2020-09-29 22:18 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-09-29 22:46 UTC, galipremsagar requested changes
We would have to make a docstring(present in `ioutils`) changes too now that this param has been renamed.

https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=read_avro#cudf.io.avro.read_avro
https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=read_avro#cudf.io.orc.read_orc
https://docs.rapids.ai/api/cudf/nightly/api.html?highlight=read_avro#cudf.io.parquet.read_parquet

2020-10-01 20:48 UTC, isVoid approved these changes
Make sure all related docstrings are updated. Can utilize the `find_in_files` function in VSCode to identify if there are any lines of `skip_rows` got left out. Otherwise lgtm. Great work digging into all the details!

2020-10-01 22:08 UTC, skirui-source commented
> Make sure all related docstrings are updated. Can utilize the `find_in_files` function in VSCode to identify if there are any lines of `skip_rows` got left out. Otherwise lgtm. Great work digging into all the details!

So i just fidn the find-in-files and there's no search results for "skip_rows"... Does that mean that all docstrings have been updated?

2020-10-01 22:49 UTC, isVoid commented
That would at least make sure the scope you searched has no strings that writes `skip_rows`. But yeah, would be a good indicator the strings are replaced.

2020-10-01 22:53 UTC, galipremsagar commented
The current changes in the PR don't indicate doc changes. It could be possible that you did not commit and push the changes to your branch.

The doc changes I'm referring to are there following lines for the respective public API changes you made:

https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L33
https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L272
https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L133

2020-10-01 23:43 UTC, skirui-source commented
> The current changes in the PR don't indicate doc changes. It could be possible that you did not commit and push the changes to your branch.
> 
> The doc changes I'm referring to are there following lines for the respective public API changes you made:
> 
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L33
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L272
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L133

I am just stuck on the builin

> The current changes in the PR don't indicate doc changes. It could be possible that you did not commit and push the changes to your branch.
> 
> The doc changes I'm referring to are there following lines for the respective public API changes you made:
> 
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L33
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L272
> https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/utils/ioutils.py#L133

My issue is that I don't understand the "set up building environment" instructions to actually build the docs ...

2020-10-02 15:21 UTC, galipremsagar commented on CHANGELOG.md
> +- PR #6353 Renamed skip_rows parameter to skiprows
```suggestion
- PR #6353 Rename `skip_rows` parameter to `skiprows` in `read_parquet`, `read_avro` and `read_orc`
```

2020-10-02 15:22 UTC, galipremsagar approved these changes
This is now good to go!

2020-10-02 20:53 UTC, merged