6356
rapidsai/cudf pull request #6372
Opened 2020-09-30 17:03 UTC by galipremsagar

Fixes: #6356 

This PR fixes issue where pyarrow table schema has `boolean` instead of `bool` in `np_dtypes`. With this fix we are instead relying to `pandas_dtypes` when there is a `bool`.

2020-09-30 17:03 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-01 00:00 UTC, galipremsagar commented
rerun tests

2020-10-01 13:37 UTC, brandon-b-miller commented on python/cudf/cudf/tests/test_parquet.py
> +    actaul_gdf = cudf.read_parquet(pandas_path, engine=engine)
```suggestion
    actual_gdf = cudf.read_parquet(pandas_path, engine=engine)
```

2020-10-01 13:37 UTC, brandon-b-miller commented on python/cudf/cudf/tests/test_parquet.py
> +    assert_eq(actaul_gdf, expected_gdf)
```suggestion
    assert_eq(actual_gdf, expected_gdf)
```

2020-10-01 13:38 UTC, brandon-b-miller requested changes
Very minor misspelling otherwise LGTM.

As an aside, do we have this same issue for the other pandas nullable types, eg `string`, `Int64`, etc?

2020-10-01 15:49 UTC, galipremsagar commented
> As an aside, do we have this same issue for the other pandas nullable types, eg `string`, `Int64`, etc?

Nope, this is only with `boolean` nullable types. Rest of the types work well.

2020-10-01 20:36 UTC, isVoid approved these changes

2020-10-04 00:08 UTC, galipremsagar commented
rerun tests

2020-10-05 13:49 UTC, brandon-b-miller approved these changes

2020-10-05 14:16 UTC, galipremsagar commented
rerun tests

2020-10-05 17:35 UTC, merged