fix typo
rapidsai/cudf pull request #6393
Opened 2020-10-01 15:13 UTC by garanews

fix typo

2020-10-01 15:15 UTC, kkraus14 approved these changes

2020-10-01 15:16 UTC, galipremsagar approved these changes
@garanews Thanks for this!

I think we are okay with fixing typos in PR names in `CHANGELOG.md` as we are not altering PR numbers, but will let @kkraus14 weigh in on this.

2020-10-01 15:17 UTC, kkraus14 commented
> @garanews Thanks for this!
> 
> I think we are okay with fixing typos in PR names in `CHANGELOG.md` as we are not altering PR numbers, but will let @kkraus14 weigh in on this.

Fixing typos in the CHANGELOG is more than encouraged!

2020-10-01 15:21 UTC, kkraus14 commented
> A little sad that we are going to have to rebuild so much just because of typos, but it is good to fix them.

I can just admin merge once things are reviewed by relevant parties 😄

2020-10-01 15:23 UTC, kkraus14 commented
ok to test

2020-10-01 16:39 UTC, ajschmidt8 approved these changes

2020-10-01 16:40 UTC, dillon-cullinan approved these changes

2020-10-01 16:45 UTC, kkraus14 commented
@garanews you need to add a line to `CHANGELOG.md` in order to kick off CI.

2020-10-01 18:57 UTC, garanews commented
@kkraus14 I can do, is enough a blank line or what?

2020-10-01 18:58 UTC, kkraus14 commented
> @kkraus14 I can do, is enough a blank line or what?

If you look at the file you'll see there's a pattern of adding a line with the pull request number and a brief description of what was done in it. So for this PR the number is 6393.

2020-10-01 18:59 UTC, garanews commented
okay, I can add it, like under improvements of current 0.16,0 right?

2020-10-01 19:01 UTC, kkraus14 commented
> okay, I can add it, like under improvements of current 0.16,0 right?

Yup, improvements section sounds perfect, thanks!

2020-10-01 19:04 UTC, garanews commented
@kkraus14 done!

2020-10-01 20:29 UTC, kkraus14 approved these changes

2020-10-01 21:13 UTC, revans2 approved these changes

2020-10-02 01:07 UTC, harrism requested changes
Thank you. I try to encourage all RAPIDS developers to install a spell checker in their IDE, but misspellings do slip through.  Just a couple more corrections.

2020-10-02 01:07 UTC, harrism commented on cpp/include/cudf/io/csv.hpp
>          "non-zero value");
While we are at it...

```suggestion
        "If the value of any of skiprows, skipfooter or nrows is valid, range size cannot be non-zero.");
```

2020-10-02 01:07 UTC, harrism commented on cpp/tests/utilities_tests/type_list_tests.cpp
> +// Work around to remove parenthesis surrounding a type
Plural.

```suggestion
// Work around to remove parentheses surrounding a type
```

2020-10-02 01:07 UTC, harrism commented on cpp/tests/utilities_tests/type_list_tests.cpp
> + * should be wrapped in parenthesis.
```suggestion
 * should be wrapped in parentheses.
```

2020-10-02 01:07 UTC, harrism commented on cpp/tests/utilities_tests/type_list_tests.cpp
> + * // Parenthesis around types with commas
```suggestion
 * // Parentheses around types with commas
```

2020-10-02 04:30 UTC, harrism approved these changes

2020-10-02 04:32 UTC, harrism commented on cpp/include/cudf/io/csv.hpp
> +        "If the value of any of skiprows, skipfooter or nrows is valid, range size cannot be non-zero.");
This caused the line to be too long. Run the clang-format script to fix it, or just accept this change...
```suggestion
        "If the value of any of skiprows, skipfooter or nrows is valid, range size cannot be "
        "non-zero.");
```

2020-10-02 11:07 UTC, merged