[REVIEW] Fix ORC reader issue with decimal type
rapidsai/cudf pull request #6466
Opened 2020-10-07 23:45 UTC by rgsl888prabhu

closes #5892

2020-10-07 23:46 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-07 23:54 UTC, rgsl888prabhu commented
@harrism should we push this 0.16 as this is priority-0 and and change is just one line.

2020-10-08 00:24 UTC, kkraus14 commented
@rgsl888prabhu is there a small test file we could add to cover the error case here?

2020-10-08 00:27 UTC, rgsl888prabhu commented
> @rgsl888prabhu is there a small test file we could add to cover the error case here?

It is a 64KB file with which we can reproduce, would it be fine to add it ?

2020-10-08 00:54 UTC, vuule commented
> It is a 64KB file with which we can reproduce, would it be fine to add it ?

Is it possible to make a smaller repro?

2020-10-08 01:04 UTC, rgsl888prabhu commented
> > It is a 64KB file with which we can reproduce, would it be fine to add it ?
> 
> Is it possible to make a smaller repro?
> Edit: 64K not that large, but it looks like this issue should be reproducible with a much smaller file.

I am trying to create smaller file to test it.

2020-10-08 04:27 UTC, harrism approved these changes

2020-10-08 06:21 UTC, OlivierNV commented
Hmm. That doesn't look right: n is the number of valid runs. It breaks out of the loop without incrementing it if the payload for this run would exceed the amount of data available in the buffer. What are the values in the failure case ?

2020-10-08 12:35 UTC, rgsl888prabhu commented
> Hmm. That doesn't look right: n is the number of valid runs. It breaks out of the loop without incrementing it if the payload for this run would exceed the amount of data available in the buffer. What are the values in the failure case ?
> [Edit] I think we might need to limit the max # of scale values in RLE stream1 such that it can't overflow when decoding the secondary base128 stream, eg: 512-limit for max run = NTHREADS/2 at line 1551 (might exceed the max internal buffer size, and I don't think that's a case where overflow can be properly handled because of cross-stream dependency).
> Long-term, this kernel should really be rewritten with 512-threads with separate queues for primary & secondary stream as it would simplify things a lot and likely better for perf when index is available (it's a big change though).

```
if (t == 0) {
    uint32_t maxpos  = min(bs->len, bs->pos + (BYTESTREAM_BFRSZ - 8u));
    uint32_t lastpos = bs->pos;
    uint32_t n;
    for (n = 0; n < numvals; n++) {
      uint32_t pos                  = lastpos;
      *(volatile int32_t *)&vals[n] = lastpos;
      pos += varint_length<uint4>(bs, pos);
      if (pos > maxpos) break;
      lastpos = pos;
    }
    scratch->num_vals = n;
    bytestream_flush_bytes(bs, lastpos - bs->pos);
  }
```

This issue occurs when numvals=1024, so for n=1023,  pos > max_pos and it would break. But at n=1023, we have already update the value val[n] with last_pos, and as this is using zero indexing, number of run would always be `n+1` if I am not wrong.

2020-10-08 13:52 UTC, rgsl888prabhu commented
> Hmm. That doesn't look right: n is the number of valid runs. It breaks out of the loop without incrementing it if the payload for this run would exceed the amount of data available in the buffer. What are the values in the failure case ?
> [Edit] I think we might need to limit the max # of scale values in RLE stream1 such that it can't overflow when decoding the secondary base128 stream, eg: 512-limit for max run = NTHREADS/2 at line 1551 (might exceed the max internal buffer size, and I don't think that's a case where overflow can be properly handled because of cross-stream dependency).
> Long-term, this kernel should really be rewritten with 512-threads with separate queues for primary & secondary stream as it would simplify things a lot and likely better for perf when index is available (it's a big change though).

@OlivierNV  And as you suggested, changing the `max run = NTHREADS/2 ` also fixes the issue, but that creates issue in other scenarios as you have already mentioned.

2020-10-08 14:50 UTC, nvdbaranec approved these changes

2020-10-08 16:50 UTC, OlivierNV commented
> This issue occurs when numvals=1024, so for n=1023, pos > max_pos and it would break. But at n=1023, we have already updated the value val[n] with lastpos, and as this is using zero indexing, number of run would always be `n+1` if I am not wrong.

It's storing the last offset but not using it (which is likely problem since that same location is initially used to store the scale).
What about moving the line `*(volatile int32_t *)&vals[n] = lastpos;` after `if (pos > maxpos) break;` ?

2020-10-08 16:58 UTC, rgsl888prabhu commented
> > Hmm. That doesn't look right: n is the number of valid runs. It breaks out of the loop without incrementing it if the payload for this run would exceed the amount of data available in the buffer. What are the values in the failure case ?
> > [Edit] I think we might need to limit the max # of scale values in RLE stream1 such that it can't overflow when decoding the secondary base128 stream, eg: 512-limit for max run = NTHREADS/2 at line 1551 (might exceed the max internal buffer size, and I don't think that's a case where overflow can be properly handled because of cross-stream dependency).
> > Long-term, this kernel should really be rewritten with 512-threads with separate queues for primary & secondary stream as it would simplify things a lot and likely better for perf when index is available (it's a big change though).
> 
> @OlivierNV
> 
> ```
> if (t == 0) {
>     uint32_t maxpos  = min(bs->len, bs->pos + (BYTESTREAM_BFRSZ - 8u));
>     uint32_t lastpos = bs->pos;
>     uint32_t n;
>     for (n = 0; n < numvals; n++) {
>       uint32_t pos                  = lastpos;
>       *(volatile int32_t *)&vals[n] = lastpos;
>       pos += varint_length<uint4>(bs, pos);
>       if (pos > maxpos) break;
>       lastpos = pos;
>     }
>     scratch->num_vals = n;
>     bytestream_flush_bytes(bs, lastpos - bs->pos);
>   }
> ```
> 
> This issue occurs when numvals=1024, so for n=1023, pos > max_pos and it would break. But at n=1023, we have already updated the value val[n] with lastpos, and as this is using zero indexing, number of run would always be `n+1` if I am not wrong.



> > This issue occurs when numvals=1024, so for n=1023, pos > max_pos and it would break. But at n=1023, we have already updated the value val[n] with lastpos, and as this is using zero indexing, number of run would always be `n+1` if I am not wrong.
> 
> It's storing the last offset but not using it (which is likely problem since that same location is initially used to store the scale).
> What about moving the line `*(volatile int32_t *)&vals[n] = lastpos;` after `if (pos > maxpos) break;` ?

It still causes same issue if I move the line after break.

2020-10-08 17:11 UTC, OlivierNV commented
Yeah, it's not handling the buffering of scale values for decimals, and the buffer capacity is only sized for 512x64bit values, so will not handle 512 worst-case 128b decimals in one-shot consumption.
Along with moving that line after the break, it's missing code at around line 1811 (with the comment "buffer secondary stream values") to deal with buffering the leftover decimal scale values for the next pass (only done for BOOLEAN and TIMESTAMP types). The leftover values need to be stored back to the beginning of the buffer and buffered_count adjusted accordingly.
Also, it needs some added logic around line 1650 to deal with the buffered values, since in the case of decimals, we're really buffering data from the primary data stream (not a trivial change).
As a short-term WAR, we could limit the initial value of max_vals to 512 for DECIMAL type (would work here), but it's not a good long-term solution since even 512 decimal values could overflow the stream buffer (worst case is (128+6)/7 bytes per value)

2020-10-08 17:25 UTC, OlivierNV commented
Or alternatively to the cross-iteration buffering, a simpler solution might be to add a loop within Decode_Decimals and refill the buffer on the fly (likely less ugly than the buffering).

2020-10-08 22:58 UTC, rgsl888prabhu commented
Don't merge this, still under progress !!!!!!!!!!!!!!!!!!!!!!!!!

2020-10-08 23:02 UTC, kkraus14 requested changes
blocking merging

2020-10-09 21:54 UTC, rgsl888prabhu commented
github is experiencing issues, and that's why my commit is not yet being shown in this PR.

2020-10-09 22:29 UTC, OlivierNV commented on cpp/src/io/orc/stripe_data.cu
> +      if (t == 0) {
Needs a `__syncthreads()` between `bytestream_fill()` and `if (t == 0) {` (race condition with `bs->fill_count`)

2020-10-09 22:43 UTC, OlivierNV approved these changes
LGTM

2020-10-09 22:48 UTC, rgsl888prabhu commented
Please select `Hide whitespace changes` option as normal diff shows lot of unrelated things.

2020-10-09 23:01 UTC, kkraus14 commented
@rgsl888prabhu did you forget to check in the test files?

2020-10-09 23:06 UTC, vuule commented
> @rgsl888prabhu did you forget to check in the test files?

I see the Python test file change

2020-10-09 23:08 UTC, kkraus14 commented
The Python test file refers to: `TestOrcFile.decimal.same.values.orc` and `TestOrcFile.decimal.multiple.values.orc` which aren't checked into CI as far as I could tell

2020-10-09 23:09 UTC, kkraus14 approved these changes

2020-10-09 23:09 UTC, rgsl888prabhu commented
> @rgsl888prabhu did you forget to check in the test files?

@vuule He meant orc format files for tests.

@kkraus14  I just uploaded them.

2020-10-09 23:11 UTC, kkraus14 commented
@vuule do you want to review before we mark this as ready to merge?

2020-10-09 23:30 UTC, vuule commented
@rgsl888prabhu Do you think we should check for perf regression before merging this? Looks unlikely to me, but I don't know the context well.

2020-10-09 23:30 UTC, vuule approved these changes
Good stuff. Thanks for finding smaller repro files.

2020-10-09 23:39 UTC, rgsl888prabhu commented
> Good stuff. Thanks for finding smaller repro files.

Thanks to @OlivierNV.

2020-10-09 23:43 UTC, rgsl888prabhu commented
> @rgsl888prabhu Do you think we should check for perf regression before merging this? Looks unlikely to me, but I don't know the context well.

Will try it and let you know.

2020-10-10 00:44 UTC, rgsl888prabhu commented
Tried with a ORC dataset with just one column with `440000000`, orc file size is 250 MB.

There is not much change in spped.
older
```
In [2]: %timeit cudf.read_orc("/home/rgsl888/orc_8GB_250MB.orc")
1.7 s ± 6.05 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

```
In [2]: %timeit cudf.read_orc("/home/rgsl888/orc_8GB_250MB.orc")
1.64 s ± 260 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

2020-10-10 03:59 UTC, karthikeyann approved these changes

2020-10-10 18:51 UTC, merged