[WIP] Replace index type-dispatch call with indexalator in cudf::strings::substring
rapidsai/cudf pull request #6471
Opened 2020-10-08 21:48 UTC by davidwendt

One of the `cudf::strings::substring` APIs accepts a list of character positions (i.e. indices) for slicing individual strings. The type-dispatcher is used to accept any integer type as the positions column parameters. Since these are indices, the indexalator can be used in place of the type-dispatcher. This will simplify the code and make it build faster. The compile time for `substrings.cu.o` reduced from 70s to 46s.

2020-10-12 15:59 UTC, rgsl888prabhu approved these changes
LGTM

2020-10-12 15:59 UTC, rgsl888prabhu commented on cpp/src/strings/substring.cu
> +std::unique_ptr<column> compute_substrings_from_fn(column_device_view const& d_column,
It would be nice to have @brief here

2020-10-12 21:14 UTC, nvdbaranec requested changes
One tiny wording thing.

2020-10-16 12:37 UTC, davidwendt commented
rerun tests

2020-10-19 22:34 UTC, nvdbaranec approved these changes
lgtm

2020-10-20 13:52 UTC, merged