[WIP] Add File IO to cuIO benchmarks
rapidsai/cudf pull request #6485
Opened 2020-10-09 23:53 UTC by vuule

2020-10-09 23:53 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-12 23:57 UTC, kkraus14 approved these changes
cmake lgtm

2020-10-13 15:33 UTC, vuule commented
rerun tests

2020-10-13 15:36 UTC, devavret commented on cpp/include/cudf_test/base_fixture.hpp
> +#include <tests/utilities/file_utilities.hpp>
Why is this file not in cudf_test

2020-10-13 15:44 UTC, davidwendt approved these changes
Looks good to me.

2020-10-13 15:44 UTC, davidwendt commented on cpp/tests/utilities/file_utilities.hpp
> +    return remove(pathname);
```suggestion
    return std::remove(pathname);
```

2020-10-13 15:45 UTC, vuule commented on cpp/include/cudf_test/base_fixture.hpp
> +#include <tests/utilities/file_utilities.hpp>
Messed the pattern. I'll move it.

2020-10-13 18:36 UTC, karthikeyann requested changes
includes cleanup only.

2020-10-13 18:36 UTC, karthikeyann commented on cpp/benchmarks/io/cuio_benchmark_common.cpp
> +#include <iostream>
clean up includes once.
some includes may not be needed anymore.

2020-10-13 18:36 UTC, karthikeyann commented on cpp/include/cudf_test/file_utilities.hpp
> +    return std::remove(pathname);
`#include <cstdio>`
required include is included in another file. check all std include once.

2020-10-13 18:36 UTC, karthikeyann commented on cpp/include/cudf_test/file_utilities.hpp
> +    if (const char *env_p = std::getenv("WORKSPACE")) dir_template = env_p;
`#include <cstdlib>` for `std::getenv`

2020-10-13 19:44 UTC, vuule commented on cpp/benchmarks/io/cuio_benchmark_common.cpp
> +#include <unistd.h>
needed for `close`.

2020-10-14 14:31 UTC, karthikeyann approved these changes
LGTM

2020-10-14 14:41 UTC, mike-wendt approved these changes
Approved changes for our `CODEOWNERS` files; will rely on team to verify other changes

2020-10-14 18:05 UTC, merged