[WIP] Enable `fixed_point` binary operations
rapidsai/cudf pull request #6528
Opened 2020-10-14 15:53 UTC by codereport

This addresses are part of https://github.com/rapidsai/cudf/issues/3556. It is a follow up to https://github.com/rapidsai/cudf/pull/5861 where most of the work was done. However, there was an issue with `binary_operator::DIV` that needs to be resolved. This PR will fix that.

Starting point is to comment in the commented out unit tests in `binop-integration-tests.cpp` and go from there.

2020-10-14 15:53 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-10-14 21:08 UTC, harrism commented
Please target branch-0.17.

2020-10-15 03:16 UTC, sperlingxx commented
For current implementation,  it seems that fixed_point types are not able to perform binary opeartion with other numeric types. Will we enable it in this ongoing PR?

2020-10-15 03:50 UTC, codereport commented
> For current implementation, it seems that fixed_point types are not able to perform binary opeartion with other numeric types. Will we enable it in this ongoing PR?

No, that is not a part of this PR.

2020-10-15 05:52 UTC, harrism commented
@sperlingxx Once (unary) casts are implemented the approach would be to cast to fixed point and then do the binary operation.

2020-10-15 05:57 UTC, sperlingxx commented
> @sperlingxx Once (unary) casts are implemented the approach would be to cast to fixed point and then do the binary operation.

I got it. Thanks, Mark!

2020-10-19 03:21 UTC, devavret requested changes
This is from a previous PR but during the creation of temporary result in `fixed_point_binary_operation`, `cudf::binary_operation` is being used to create a temporary column of the same scale. This does not take a stream. Try using the `detail` version.

2020-10-20 01:48 UTC, codereport commented on cpp/src/binaryop/binaryop.cpp
> +  return is_basic_arithmetic_binop(op) or is_comparison_binop(op);
You are right. That is an oversight on my part. I will add to https://github.com/rapidsai/cudf/pull/6544 as it is getting merged sooner.

2020-10-20 13:10 UTC, codereport commented
This job is currently waiting on https://github.com/rapidsai/cudf/pull/6544 to be merged.

2020-10-21 00:46 UTC, trxcllnt approved these changes

2020-10-21 00:57 UTC, harrism approved these changes

2020-10-21 01:06 UTC, devavret approved these changes

2020-10-24 03:40 UTC, merged