[REVIEW] Create cudf::detail::byte_cast for cudf::byte_cast
rapidsai/cudf pull request #6573
Opened 2020-10-21 13:01 UTC by davidwendt

Found this when I noticed a doxygen error in `reshape.hpp`
https://github.com/rapidsai/cudf/blob/47a3d32cc343293c5240c1c60f0dcd3ef7e26691/cpp/include/cudf/reshape.hpp#L75
This line should be right before the end bracket for the `namespace cudf` line so the `cudf::byte_cast` appears in the correct doxygen group.

Noticed that `cudf::byte_cast` includes a `cudaStream_t` parameter unlike all the other APIs in this header file. This PR creates the appropriate `cudf::detail::byte_cast` and move the `cudaStream_t` parameter to that call per the coding guidelines here:
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/docs/TRANSITIONGUIDE.md#streams

2020-10-21 23:22 UTC, codereport approved these changes
LGMT :+1:

2020-10-22 00:01 UTC, harrism requested changes
Couple of doc improvements and a parameter name improvement.

2020-10-22 00:01 UTC, harrism commented on cpp/src/reshape/byte_cast.cu
> + * @param stream CUDA stream used for device memory operations and kernel launches.
No stream here.

```suggestion
```

2020-10-22 00:01 UTC, harrism commented on cpp/src/reshape/byte_cast.cu
> +  return detail::byte_cast(input_column, configuration, mr, 0);
```suggestion
  return detail::byte_cast(input_column, configuration, mr, cudaStreamDefault);
```

2020-10-22 20:19 UTC, harrism approved these changes

2020-10-24 01:32 UTC, galipremsagar commented
rerun tests

2020-10-24 13:30 UTC, merged