[REVIEW] Fix csv writer handling embedded comma delimiter
rapidsai/cudf pull request #6643
Opened 2020-11-02 19:16 UTC by davidwendt

Closes #6641 

The csv writer_impl logic is checking for the ',' delimiter using already freed temporary device memory.
The ctor for `predicate_special_chars` accepts a `string_scalar` object but is passed a `std::string`.
The implicit conversion creates a temporary `string_scalar` correctly.
The ctor then saves a `string_view` to the `string_scalar` data as a member variable.
This means that once the ctor returns, the temporary is destroyed and the `string_view` is now pointing to freed memory.

The PR creates a `string_scalar` before the ctor and then passes a `string_view` instance to the `predicate_special_chars` ctor instead. This also removes the need to pass a stream parameter to the ctor. Now the `string_scalar` object has the same lifespan as the `predicate_special_chars` instance.

2020-11-03 06:35 UTC, devavret requested changes

2020-11-03 06:35 UTC, devavret commented on cpp/tests/io/csv_test.cpp
> +  for (auto h : h_rhs) printf("%s\n", h.c_str());
debug prints?

2020-11-03 06:35 UTC, devavret commented on cpp/src/io/csv/writer_impl.cu
> +    string_scalar delimiter{std::string{options_.get_inter_column_delimiter()}};
As an additional benefit, the string scalar can now be constructed with a stream.

2020-11-03 18:08 UTC, vuule approved these changes

2020-11-05 01:55 UTC, harrism approved these changes
Good fix.

2020-11-05 01:55 UTC, merged