[REVIEW] Remove macros from ORC reader and writer
rapidsai/cudf pull request #6698
Opened 2020-11-06 18:43 UTC by kaatish

Partially addresses #5211

2020-11-06 18:44 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-06 20:19 UTC, vuule requested changes
Looks good, some additional suggestions to improve readability posted below.

2020-11-06 20:19 UTC, vuule commented on cpp/src/io/orc/orc_field_writer.hpp
> +  void field_string(int id, const std::string &v)
Try to make the naming consistent with Parquet::CompactProtocolWriter where it makes sense (e.g. I believe we avoided the single letter names there).

2020-11-06 21:14 UTC, kaatish commented on cpp/src/io/orc/orc_field_writer.hpp
> +    for (size_t i = 0; i < cnt; i++) sz += p->put_uint(v[i]);
sz is being manipulated later on in the function. I do not think it can be const unless we make another copy.

2020-11-09 17:53 UTC, vuule approved these changes

2020-11-09 22:04 UTC, davidwendt requested changes
Looks good. There are no doxygen comments in the 2 new  header files.

2020-11-09 22:04 UTC, davidwendt commented on cpp/src/io/orc/orc_field_reader.hpp
> +#include <string.h>
```suggestion
#include <string>
```

2020-11-09 22:04 UTC, davidwendt commented on cpp/src/io/orc/orc_field_reader.hpp
> +#include "orc.h"
```suggestion
#include <io/orc/orc.h>
```

2020-11-09 22:04 UTC, davidwendt commented on cpp/src/io/orc/orc_field_writer.hpp
> +#include <string.h>
```suggestion
#include <string>
```

2020-11-09 22:04 UTC, davidwendt commented on cpp/src/io/orc/orc_field_writer.hpp
> +#include "orc.h"
```suggestion
#include <io/orc/orc.h>
```

2020-11-11 16:03 UTC, davidwendt requested changes
Just a few doxygen comments. There a some `@return` tags in doxygen comments for `struct` declarations.

2020-11-11 16:03 UTC, davidwendt commented on cpp/src/io/orc/orc_field_writer.hpp
> + * ProtobufWriter::write(...) functions
```suggestion
 * `ProtobufWriter::write(...)` functions
```

2020-11-11 16:32 UTC, davidwendt approved these changes
Looks good to me.

2020-11-12 16:08 UTC, kkraus14 commented
rerun tests

2020-11-12 21:59 UTC, merged