[REVIEW] Add missing call to cudaStreamSynchronize() in ::get_value()
rapidsai/cudf pull request #6713
Opened 2020-11-09 19:18 UTC by nvdbaranec

Fixes  https://github.com/rapidsai/cudf/issues/6700

Asynchronous memcpy was returning a stack variable before synchronizing.

2020-11-09 19:19 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-09 23:17 UTC, jrhemstad commented on cpp/include/cudf/detail/get_value.cuh
> +  CUDA_TRY(cudaStreamSynchronize(stream));
Can you add a note to the documentation that this function synchronizes the stream?

2020-11-10 04:15 UTC, harrism approved these changes

2020-11-10 19:30 UTC, davidwendt approved these changes

2020-11-10 19:52 UTC, jrhemstad approved these changes

2020-11-11 01:09 UTC, harrism requested changes

2020-11-11 01:09 UTC, harrism commented on cpp/include/cudf/detail/get_value.cuh
> + * This will retrieve the specified value from device memory. This function
One of my pet peeves is using future tense in documentation. Let's switch this to present tense, it is nearly always clearer. Plus, with your addition the tenses are mixed.

I know, I know, this is very nit-picky.

```suggestion
 * Retrieves the specified value from device memory. This function
```

2020-11-11 22:47 UTC, nvdbaranec commented
rerun tests

2020-11-12 00:37 UTC, harrism approved these changes

2020-11-12 15:45 UTC, nvdbaranec commented
rerun tests

2020-11-12 19:23 UTC, nvdbaranec commented
rerun tests

2020-11-12 22:54 UTC, nvdbaranec commented
rerun tests

2020-11-13 14:01 UTC, merged