Replace raw streams with rmm::cuda_stream_view (part 3)
rapidsai/cudf pull request #6744
Opened 2020-11-12 06:02 UTC by harrism

Converting libcudf to use `rmm::cuda_stream_view` will require a LOT of changes, so I'm splitting it into multiple PRs to ease reviewing. This is the third PR in the series. This series of PRs will

- Replace usage of `cudaStream_t` with `rmm::cuda_stream_view`
- Replace usage of `0` or `nullptr` as a stream identifier with `rmm::cuda_stream_default`
- Ensure all APIs always order the stream parameter before the memory resource parameter. #5119

Contributes to #6645 and #5119

Depends on #6646 and #6648 so this PR will look much bigger until they are merged.

This third PR converts:
 - remaining dictionary functionality
 - cuio
 - lists
 - scalar
 - strings

2020-11-12 06:03 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-13 16:35 UTC, mike-wendt reviewed
Approved changes for our `CODEOWNERS` files; will rely on team to verify other changes

2020-11-22 22:58 UTC, harrism commented
rerun tests

2020-11-22 23:30 UTC, kkraus14 commented
rerun tests

2020-11-23 16:23 UTC, jlowe approved these changes
Java approval.

2020-11-23 18:50 UTC, rgsl888prabhu approved these changes
LGTM, just small changes

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/regex/regexec.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/replace/backref_re.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/replace/multi_re.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/replace/replace_re.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/substring.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/strings/translate.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 18:50 UTC, rgsl888prabhu commented on cpp/src/text/generate_ngrams.cu
> +#include "rmm/cuda_stream_view.hpp"
```suggestion
#include <rmm/cuda_stream_view.hpp>
```

2020-11-23 22:06 UTC, harrism commented on cpp/include/cudf/strings/detail/merge.cuh
> +#include "rmm/cuda_stream_view.hpp"
OMG I'm so sick of clangd sneaking these in. Thanks!

2020-11-23 22:18 UTC, rgsl888prabhu commented on cpp/include/cudf/strings/detail/merge.cuh
> +#include "rmm/cuda_stream_view.hpp"
Just reviewing drained me , I can't even imagine how you felt after three such PRs.

2020-11-23 22:25 UTC, devavret requested changes
Suggest making a debug build once and changing any `CHECK_CUDA(stream)` to `CHECK_CUDA(stream.view())`. There are several instances in this PR which I cannot request changes in because those lines are not part of diffs.

2020-11-23 22:43 UTC, harrism commented
> Suggest making a debug build once and changing any `CHECK_CUDA(stream)` to `CHECK_CUDA(stream.view())`. There are several instances in this PR which I cannot request changes in because those lines are not part of diffs.

Thanks @devavret , done. Running a debug build in the background...

2020-11-23 22:58 UTC, codereport approved these changes
LGTM :+1:

2020-11-24 00:21 UTC, harrism commented
@devavret I found and fixed an unrelated debug build issue. Can you approve?

2020-11-24 09:41 UTC, devavret approved these changes

2020-11-24 17:34 UTC, merged