First class support for unbounded window function bounds
rapidsai/cudf pull request #6811
Opened 2020-11-19 21:31 UTC by mythrocks

This change is in relation to https://github.com/NVIDIA/spark-rapids/issues/1039.

CUDF  does not currently support the notion of an `UNBOUNDED` window frame, i.e. a way to specify `UNBOUNDED PRECEDING` or `UNBOUNDED FOLLOWING` boundary. This is faked by the caller by specifying `std::numeric_limits<size_type>::max` for either bounds.

This workaround is acceptable for `ROW`-based window frames, but not for `RANGE`-based queries such as those supported by `cudf::grouped_time_range_rolling_window()`.

For instance, consider the following dataset:
```
// For this illusion, assume the following:
//   1. timestamp column values to be, say, the day in January 2020.
//   2. ∅ == null

Group-by column    (gby):   [0, 0, 0, 0, 0,  1, 1, 1, 1, 1]
Aggregation column (agg):   [0, 1, 2, 3, 4,  5, 6, 7, 8, 9]
Timestamp column    (ts):   [∅, ∅, ∅, 1, 2,  ∅, ∅, 3, 4, 5]
```
As per the changes in #6557, a `COUNT(agg)` over time-range rolling_window `(5000 DAYS PRECEDING, 1 DAY FOLLOWING)` would yield:
```
Count over (5000d,1d):      [3, 3, 3, 2, 2,  2, 2, 2, 3, 3]
```
This is understandable, since `NULL` timestamps cannot participate in timestamp subtraction. However, for a truly `UNBOUNDED PRECEDING` window, the expected result (congruent with the semantics of SQL and most big data analytics systems) would be:
```
Count over (UNBOUNDED, 1d): [3, 3, 3, 5, 5,  2, 2, 4, 5, 5]
```
This change attempts to add explicit support for `UNBOUNDED` window boundaries, for use with `grouped_time_range_rolling_window()`.

2020-11-19 21:31 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-11-20 00:09 UTC, harrism commented
Please use draft PRs while WIP so it's obvious from the github notifications view (which doesn't show labels).

2020-11-20 00:16 UTC, mythrocks commented
> Please use draft PRs while WIP so it's obvious from the github notifications view (which doesn't show labels).

Oh, right. Sorry.

2020-11-20 08:09 UTC, harrism approved these changes
I'm convinced that "rolling windows" is what happens  when people generalize computing needs into APIs rather than programming languages. What a complete mess.

But hey, it wasn't your idea.  This PR looks clean. I approve.

2020-11-20 19:19 UTC, mythrocks commented
> What a mess (I mean the conglomeration of features, not the code.)

"This isn't even my final form."

2020-11-20 22:10 UTC, nvdbaranec requested changes
Couple of tiny nitpicks.  And one additional question :  I'm assuming we're leaving the old size_type based bounding interfaces in there for backwards compatibility?

2020-11-20 22:10 UTC, nvdbaranec commented on cpp/src/rolling/rolling.cu
> +    if (following_window_is_unbounded) { return group_end - idx - 1; }
Nitpick:  should always err on the side of parentheses with compound arithmetic.

2020-11-20 22:10 UTC, nvdbaranec commented on cpp/src/rolling/rolling.cu
> +    if (following_window_is_unbounded) { return num_rows - idx - 1; }
Same comment on parentheses as above.

2020-11-20 22:10 UTC, nvdbaranec commented on cpp/src/rolling/rolling.cu
> +    if (preceding_window_is_unbounded) { return idx - group_start + 1; }
Parentheses

2020-11-20 22:10 UTC, nvdbaranec commented on cpp/src/rolling/rolling.cu
> +    if (following_window_is_unbounded) { return group_end - idx - 1; }
Parentheses.

2020-11-21 20:26 UTC, mythrocks commented on cpp/include/cudf/rolling.hpp
> +    return window_bounds(true, std::numeric_limits<cudf::size_type>::max());
> Or is it the case that for range based bounds we check the `is_unbounded` bool?

Yes, that's right. It should be correct to use the bounds value for non-range queries.

2020-11-21 20:46 UTC, mythrocks commented
> I'm assuming we're leaving the old size_type based bounding interfaces in there for backwards compatibility?

Yes, that is right; these are public APIs.

Also, I am leaving the `rolling_window()` functions unchanged for the moment. These overloads can be introduced at a later time, if the Pandas side requires them.

2020-11-23 22:50 UTC, revans2 approved these changes

2020-11-24 04:24 UTC, mythrocks commented
Found a bug in the `WindowOptions.hashCode()`. (I neglected to account for the new unbounded flags.)

I have added tests for all combinations of `UNBOUNDED`, `PRECEDING`/`FOLLOWING`/`CURRENT ROW` on the JNI side, in case I've missed something else. Could I request @revans2 to please take a look at the new changes?

2020-11-24 13:04 UTC, revans2 approved these changes

2020-11-24 18:26 UTC, merged

2020-11-24 21:11 UTC, mythrocks commented
This has been merged. Thank you for the reviews, all.