Add null count test for apply_boolean_mask
rapidsai/cudf pull request #6903
Opened 2020-12-04 03:01 UTC by harrism

2020-12-04 03:02 UTC, GPUtester commented
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

2020-12-09 08:15 UTC, karthikeyann requested changes

2020-12-09 15:15 UTC, kkraus14 commented on CHANGELOG.md
> +## Bug Fixes
```suggestion
```

2020-12-09 15:15 UTC, kkraus14 commented on CHANGELOG.md
> + - PR #6903 Add null count test for apply_boolean_mask
```suggestion
- PR #6903 Add null count test for apply_boolean_mask
```

2020-12-09 15:51 UTC, karthikeyann approved these changes
LGTM

2020-12-11 04:37 UTC, harrism commented
rerun tests

2020-12-14 07:14 UTC, devavret approved these changes

2020-12-15 03:52 UTC, merged