Build libcudf with -Wall
rapidsai/cudf pull request #7105
Opened 2021-01-08 21:52 UTC by trxcllnt

I discovered we're not building libcudf the `-Wall` GCC flag. This PR enables `-Wall` for GCC and nvcc, and fixes most of the errors.

The only error I haven't fixed yet is `-Werror=uninitialized` on this line [this line](https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/include/cudf/scalar/scalar.hpp#L334), but @codereport is on it.

2021-01-09 03:46 UTC, codereport approved these changes
:100:

2021-01-09 06:51 UTC, kkraus14 commented
Looks like `-Wall` isn't supported on `CUDA 10.1`?

2021-01-12 00:55 UTC, harrism requested changes
Use `std::size_t`. Also caught one case where `cudf::size_type` should be used.

2021-01-12 00:55 UTC, harrism commented on cpp/benchmarks/common/generate_benchmark_input.cpp
> +    for (uint32_t row = 1; row < num_rows + 1; ++row) {
```suggestion
    for (cudf::size_type row = 1; row < num_rows + 1; ++row) {
```

2021-01-12 00:55 UTC, harrism commented on cpp/src/strings/regex/regcomp.cpp
> +    for (size_t p = 0; p < cls.size(); p += 2)
Should be `std::size_t` everywhere.

```suggestion
    for (std::size_t p = 0; p < cls.size(); p += 2)
```

2021-01-12 01:39 UTC, trxcllnt reviewed
`size_t` -> `std::size_t`

2021-01-12 01:39 UTC, trxcllnt commented on cpp/benchmarks/common/generate_benchmark_input.cpp
> +  if (dtype_ids.size() == static_cast<size_t>(num_cols)) { return dtype_ids; }
```suggestion
  if (dtype_ids.size() == static_cast<std::size_t>(num_cols)) { return dtype_ids; }
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/interop/to_arrow.cpp
> +  CUDF_EXPECTS(metadata.children_meta.size() == static_cast<size_t>(input.num_children()),
```suggestion
  CUDF_EXPECTS(metadata.children_meta.size() == static_cast<std::size_t>(input.num_children()),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/interop/to_arrow.cpp
> +  CUDF_EXPECTS((metadata.size() == static_cast<size_t>(input.num_columns())),
```suggestion
  CUDF_EXPECTS((metadata.size() == static_cast<std::size_t>(input.num_columns())),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/io/avro/avro.cpp
> +            size_t pos = parent_idx + 1;
```suggestion
            std::size_t pos = parent_idx + 1;
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/io/parquet/parquet.cpp
> +  if (static_cast<size_t>(WalkSchema(md)) != md->schema.size()) return false;
```suggestion
  if (static_cast<std::size_t>(WalkSchema(md)) != md->schema.size()) return false;
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +      for (size_t np = p + 2; np < cls.size(); np += 2)
```suggestion
      for (std::size_t np = p + 2; np < cls.size(); np += 2)
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +      size_t p = 0;
```suggestion
      std::size_t p = 0;
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +    for (size_t i = 0; i < in.size(); i++) {
```suggestion
    for (std::size_t i = 0; i < in.size(); i++) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +          for (size_t j = 0; j < i - rep_start; j++) out.pop_back();
```suggestion
          for (std::size_t j = 0; j < i - rep_start; j++) out.pop_back();
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +            for (size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```suggestion
            for (std::size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +            for (size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```suggestion
            for (std::size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +            for (size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```suggestion
            for (std::size_t k = rep_start; k < i; k++) out.push_back(in[k]);
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/src/strings/regex/regcomp.cpp
> +  for (size_t i = 0; i < _insts.size(); i++) {
```suggestion
  for (std::size_t i = 0; i < _insts.size(); i++) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/copying/slice_tests.cpp
> +  EXPECT_EQ(static_cast<size_t>(type_match_count), expected);
```suggestion
  EXPECT_EQ(static_cast<std::size_t>(type_match_count), expected);
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/copying/split_tests.cpp
> +  for (size_t i = 0; i < ret_cols_0.size(); ++i) {
```suggestion
  for (std::size_t i = 0; i < ret_cols_0.size(); ++i) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/copying/split_tests.cpp
> +  for (size_t i = 0; i < result.size(); ++i) { Compare(expected[i], result[i]); }
```suggestion
  for (std::size_t i = 0; i < result.size(); ++i) { Compare(expected[i], result[i]); }
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/copying/split_tests.cpp
> +  for (size_t index = 0; index < result.size(); index++) {
```suggestion
  for (std::size_t index = 0; index < result.size(); index++) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/copying/split_tests.cpp
> +  for (size_t index = 0; index < result.size(); index++) {
```suggestion
  for (std::size_t index = 0; index < result.size(); index++) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/io/parquet_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(result.tbl->view().column(0).size()),
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(result.tbl->view().column(0).size()),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/io/parquet_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(result.tbl->view().column(1).size()),
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(result.tbl->view().column(1).size()),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/io/parquet_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(result.tbl->view().column(0).size()),
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(result.tbl->view().column(0).size()),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/io/parquet_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(result.tbl->view().column(1).size()),
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(result.tbl->view().column(1).size()),
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/hash_partition_test.cpp
> +  EXPECT_EQ(size_t{0}, offsets.size());
```suggestion
  EXPECT_EQ(std::size_t{0}, offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/hash_partition_test.cpp
> +  EXPECT_EQ(size_t{0}, offsets.size());
```suggestion
  EXPECT_EQ(std::size_t{0}, offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/hash_partition_test.cpp
> +  EXPECT_EQ(size_t{0}, offsets.size());
```suggestion
  EXPECT_EQ(std::size_t{0}, offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +    EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
    EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/partitioning/round_robin_test.cpp
> +  EXPECT_EQ(static_cast<size_t>(num_partitions), expected_partition_offsets.size());
```suggestion
  EXPECT_EQ(static_cast<std::size_t>(num_partitions), expected_partition_offsets.size());
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/strings/extract_tests.cpp
> +  for (size_t idx = 0; idx < patterns.size(); ++idx) {
```suggestion
  for (std::size_t idx = 0; idx < patterns.size(); ++idx) {
```

2021-01-12 01:39 UTC, trxcllnt commented on cpp/tests/utilities_tests/column_utilities_tests.cpp
> +  EXPECT_EQ(size_t{3}, host_data.first.size());
```suggestion
  EXPECT_EQ(std::size_t{3}, host_data.first.size());
```

2021-01-12 02:37 UTC, kkraus14 approved these changes
cmake approval

2021-01-12 03:59 UTC, harrism approved these changes

2021-01-12 05:17 UTC, kkraus14 commented
@trxcllnt Are we clear to remove the DO NOT MERGE label now and put on the auto merge?

2021-01-12 16:37 UTC, trxcllnt commented
@kkraus14 yep

2021-01-12 23:52 UTC, merged