Use `uvector` in `replace_nulls`; Fix `sort_helper::grouped_value` doc
rapidsai/cudf pull request #7256
Opened 2021-01-29 22:22 UTC by isVoid

Small PR to provide two fixes:
- Use `rmm::device_uvector` in place of `device_vector` to improve efficiency. This is a scratch space, so supplied stream and default memory resource is used.
- Update `sort_helper::grouped_value` docstring to reflect update after use of stable sort.

2021-01-29 22:25 UTC, vuule commented on cpp/include/cudf/detail/groupby/sort_helper.hpp
> +   * The values within each group maintains their original order.
```suggestion
   * The values within each group maintain their original order.
```

2021-01-29 22:32 UTC, vuule approved these changes

2021-01-29 22:36 UTC, rgsl888prabhu approved these changes
LGTM, have to update copyright

2021-02-02 01:32 UTC, harrism requested changes

2021-02-02 01:32 UTC, harrism commented on cpp/include/cudf/detail/groupby/sort_helper.hpp
> +   * The values within each group maintain their original order.
Update file copyright dates.

2021-02-02 01:32 UTC, harrism commented on cpp/src/replace/nulls.cu
> +  rmm::device_uvector<cudf::size_type> gather_map(input.size(), stream);
I think you should also update line 405 below (cudf::detail::gather call) to pass it the same stream.

2021-02-02 01:35 UTC, harrism commented
This PR was opened during burndown, so really it should target branch-0.19. In this case it's probably safe, but please be careful in the future.

2021-02-02 03:28 UTC, harrism approved these changes

2021-02-03 19:56 UTC, isVoid commented
rerun tests

2021-02-03 22:07 UTC, davidwendt commented on cpp/src/groupby/sort/sort_helper.cu
> + * Copyright (c) 2019-2021, NVIDIA CORPORATION.
Only change the  year if you've changed the file.

2021-02-04 20:09 UTC, kkraus14 commented
@gpucibot merge

2021-02-04 20:09 UTC, merged