fix Arrow CMake file
rapidsai/cudf pull request #7358
Opened 2021-02-09 20:51 UTC by rongou

With the latest cmake (built from head), it crashes with `-DARROW_STATIC_LIB=ON`. Adding `cmake_minimum_required` to match what's in the top-level file.

2021-02-09 22:40 UTC, jlowe requested changes
This needs to target branch-0.19.

2021-02-09 22:40 UTC, jlowe commented on cpp/cmake/Templates/Arrow.CMakeLists.txt.cmake
>  # limitations under the License.
2021 copyrights

2021-02-09 22:59 UTC, rongou commented on cpp/cmake/Templates/Arrow.CMakeLists.txt.cmake
>  # limitations under the License.
Done.

2021-02-09 23:05 UTC, harrism commented
Is there a good reason to force push?

2021-02-09 23:06 UTC, harrism approved these changes

2021-02-09 23:20 UTC, jlowe approved these changes

2021-02-09 23:42 UTC, rongou commented
@harrism I had to rebase on branch-0.19.

2021-02-10 00:17 UTC, kkraus14 commented
@rongou do you happen to have a stacktrace of how it was crashing? Would like to understand what CMake policy introduced in 3.18+ is giving it issues.

2021-02-10 04:51 UTC, rongou commented
@kkraus14 
```console
CMake Error in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.19)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".


-- Configuring incomplete, errors occurred!
See also "/home/rou/src/cudf/cpp/build/arrow/CMakeFiles/CMakeOutput.log".
CMake Error at cmake/Modules/ConfigureArrow.cmake:39 (message):
  Configuring Arrow failed: 1
Call Stack (most recent call first):
  CMakeLists.txt:205 (include)
```

2021-02-10 16:10 UTC, kkraus14 approved these changes

2021-02-10 16:12 UTC, kkraus14 commented
@rongou how are you invoking CMake / using the `ConfigureArrow` module? It should be inheriting the `cmake_minimum_required` from the parent `CMakeLists.txt` as far as I know.

2021-02-10 16:12 UTC, kkraus14 commented
cc @robertmaynard for visibility

2021-02-10 17:29 UTC, rongou commented
Currently this is done through `execute_process` (https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/cmake/Modules/ConfigureArrow.cmake#L33). This module can probably use some refactoring, e.g. switching to CPM.

2021-02-10 17:31 UTC, kkraus14 commented
🤦 well that explains it. This should be fixed in #7107 then, but this is a good bandaid until then.

Is this broken for 0.18 as well? Does this require a patch for the JNI build to work properly?

2021-02-10 17:44 UTC, rongou commented
This is only a problem if you build `cmake` from head. I've been testing the cmake nvcc symlink change, thus was using the head version. The current release version of cmake still works. Yeah #7107 would be a more permanent fix.

2021-02-10 17:58 UTC, kkraus14 commented
Going to merge this in as is then, thanks!

2021-02-10 17:58 UTC, kkraus14 commented
@gpucibot merge

2021-02-10 17:59 UTC, merged