Detail APIs for datetime functions
rapidsai/cudf pull request #7430
Opened 2021-02-23 22:21 UTC by magnatelee

This PR adds detail APIs for datetime functions so that users can pass stream arguments to them.

2021-02-24 18:22 UTC, vuule requested changes
Looks good; couple of small suggestions:

2021-02-24 18:22 UTC, vuule commented on cpp/include/cudf/detail/datetime.hpp
> + * Copyright (c) 2018-2021, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2021, NVIDIA CORPORATION.
```

2021-02-24 18:22 UTC, vuule commented on cpp/src/datetime/datetime_ops.cu
> +  return detail::extract_second(column, 0, mr);
More explicit:
```suggestion
  return detail::extract_second(column, rmm::cuda_stream_default, mr);
```
The suggestion applies to all `detail::` calls here.

2021-02-24 19:19 UTC, vuule approved these changes

2021-02-24 22:22 UTC, ajschmidt8 approved these changes

2021-02-25 13:08 UTC, davidwendt approved these changes
Looks good. You should add 2021 to the copyright in `datetime_ops.cu`

2021-02-25 18:41 UTC, magnatelee commented
@davidwendt Thanks for catching it. I just added the year.

2021-02-25 19:55 UTC, kkraus14 commented
@gpucibot merge

2021-02-25 19:56 UTC, kkraus14 commented
Thanks @magnatelee!

2021-02-25 22:16 UTC, merged