Add gbenchmarks for strings filter functions
rapidsai/cudf pull request #7438
Opened 2021-02-24 18:11 UTC by davidwendt

Reference #5698
This creates a gbenchmark for the `cudf::strings::filter_characters`, `cudf::strings::filter_characters_of_type`,  and `cudf::strings::strip` functions.

This PR also includes changes to `strip.cu` and `filter_chars` to use the more efficient `make_strings_children` utility. This improved performance on these functions by 2x on average.

2021-02-24 19:13 UTC, kkraus14 approved these changes
cmake lgtm

2021-02-24 21:20 UTC, codereport requested changes
lgtm, other than a couple small things

2021-02-24 21:20 UTC, codereport commented on cpp/benchmarks/string/filter_benchmark.cpp
> +  auto types = cudf::strings::string_character_types::SPACE;
```suggestion
  auto const types = cudf::strings::string_character_types::SPACE;
```

2021-02-24 21:20 UTC, codereport commented on cpp/src/strings/strip.cu
> +    // auto itr              = d_str.begin();
I assumed we can remove this?
```suggestion
```

2021-02-25 16:39 UTC, codereport approved these changes
:+1:

2021-02-25 16:59 UTC, davidwendt commented on cpp/benchmarks/string/filter_benchmark.cpp
> +      case filter: cudf::strings::filter_characters_of_type(input, types); break;
Seems to be working though.

2021-02-26 18:18 UTC, karthikeyann approved these changes

2021-02-26 18:48 UTC, kkraus14 commented
@gpucibot merge

2021-02-26 18:48 UTC, merged