Use device_uvector, device_span in sort groupby
rapidsai/cudf pull request #7523
Opened 2021-03-05 22:12 UTC by karthikeyann

- Replace device_vector with device_uvector
- Replace device_vector const& with device_span<const>

Ref. https://github.com/rapidsai/cudf/pull/7387#discussion_r587718013

2021-03-06 02:37 UTC, hyperbolic2346 requested changes

2021-03-06 02:37 UTC, hyperbolic2346 commented on cpp/src/groupby/sort/sort_helper.cu
> +  //(*)[num_groups] = num_keys(stream);
```suggestion
```

2021-03-08 08:00 UTC, karthikeyann commented
rerun tests

2021-03-08 15:49 UTC, jrhemstad commented
CI is failing due to a segfault in a groupby test. You should verify that none of the places where `device_vector` was replaced with `device_uvector` relied on the default initialization of `device_vector`.

2021-03-08 19:02 UTC, hyperbolic2346 approved these changes
This looks good to me.

2021-03-11 14:31 UTC, jrhemstad commented
rerun tests

2021-03-11 19:18 UTC, davidwendt approved these changes
Looks good. Some of these files need their copyright year updated.

2021-03-15 11:38 UTC, karthikeyann commented
@gpucibot merge

2021-03-15 11:38 UTC, merged