Remove unneeded step parameter from strings::detail::copy_slice
rapidsai/cudf pull request #7525
Opened 2021-03-05 22:54 UTC by davidwendt

This started to be a change converting some `device_vector` usages in `cpp/src/strings` source files to use `device_uvector` instead. The `cpp/src/strings/copying/copying.cu` source has the implementation for `cudf::strings::detail::copy_slice()` and used a `device_vector` to handle a `step` parameter. I can not longer find this parameter being used. I believe it was a hold over from porting nvstrings. So this PR mainly includes changes for removing this unneeded parameter which also removes the need for the `device_vector` or temporary memory in this function.
And, it also includes changes to `attributes.cu` to use the `device_uvector` as well.

 I'm marking this as non-breaking change since it is a change to a `detail` API and did not seem to be used anywhere in this repo.

2021-03-06 01:59 UTC, hyperbolic2346 requested changes
Looks good to me.

2021-03-08 15:39 UTC, davidwendt commented on cpp/include/cudf/strings/copying.hpp
> + * s2 is ["d", "e"]
Oops. Yes, I was looking at `s2`. Good catch.

2021-03-08 18:56 UTC, ajschmidt8 approved these changes

2021-03-08 19:11 UTC, hyperbolic2346 approved these changes

2021-03-09 20:17 UTC, davidwendt commented
rerun tests

2021-03-11 15:05 UTC, jrhemstad approved these changes

2021-03-11 22:18 UTC, davidwendt commented
@gpucibot merge

2021-03-11 22:18 UTC, merged