Support Decimal DIV changes in cudf [skip ci]
rapidsai/cudf pull request #7527
Opened 2021-03-07 03:50 UTC by razajafri

@codereport is making changes to the way `DIV` will behave for fixed-point types #7435. This PR contains Java changes to support those changes. 

Note: This is a draft until #7435 is merged

2021-03-12 23:48 UTC, razajafri commented
Now that #7435 is merged. The plugin will stop working unless we merge this

2021-03-13 00:07 UTC, mythrocks commented on java/src/main/java/ai/rapids/cudf/ColumnView.java
> +  public static int getFixedPointOutpuScale(BinaryOp op, DType lhsType, DType rhsType) {
Typo: `getFixedPointOutputScale()`.

2021-03-13 00:08 UTC, mythrocks commented on java/src/main/java/ai/rapids/cudf/ColumnView.java
> +  public static int getFixedPointOutpuScale(BinaryOp op, DType lhsType, DType rhsType) {
Also, missing docs.

2021-03-13 00:09 UTC, jlowe requested changes

2021-03-13 00:09 UTC, jlowe commented on java/src/main/java/ai/rapids/cudf/ColumnView.java
> +  public static int getFixedPointOutpuScale(BinaryOp op, DType lhsType, DType rhsType) {
If this remains a public function it needs the full Javadoc treatment.

2021-03-13 00:11 UTC, mythrocks approved these changes
A couple of minor nitpicks, but looks good to me.

2021-03-13 00:12 UTC, mythrocks requested changes
(Accidentally approved, earlier.) 
Minor nitpicks: Javadoc + typo in method name.

2021-03-13 00:12 UTC, jlowe commented on java/src/main/native/src/ColumnViewJni.cpp
> +                                                                  jint lhs_scale, jint rhs_scale) {
Indentation is off here.

2021-03-15 18:18 UTC, gerashegalov reviewed
@razajafri can you merge the parent branch-0.19 to consume `binary_operation_fixed_point_scale` into your PR (, and address the previous comments on the PR?

Otherwise, LGTM

2021-03-15 19:01 UTC, razajafri commented
Addressed comments. PTAL 

@jlowe do you have any more concerns? I added a small change to the CMakeLists.txt for not overriding the `CUDF_CPP_BUILD_DIR` if its set in the environment. This is needed to build the bindings within the compose docker. Let me know if you want me to spin this change into a separate PR.

2021-03-15 19:32 UTC, jlowe commented on java/src/main/native/CMakeLists.txt
> +if (NOT CUDF_CPP_BUILD_DIR)
Was this supposed to be `if (NOT DEFINED CUDF_CPP_BUILD_DIR)`?  Otherwise there's no variable expansion in what is written that I can see.

2021-03-15 19:32 UTC, jlowe commented on java/src/main/java/ai/rapids/cudf/ColumnView.java
> +  protected static int getFixedPointOutputScale(BinaryOp op, DType lhsType, DType rhsType) {
This should be package-private.

2021-03-15 19:35 UTC, jlowe commented on java/src/main/native/CMakeLists.txt
> +if (NOT CUDF_CPP_BUILD_DIR)
Oh nevermind, this should be OK as-is.

2021-03-15 21:54 UTC, razajafri commented
@jlowe PTAL.

2021-03-15 21:58 UTC, jlowe approved these changes

2021-03-15 22:35 UTC, mythrocks approved these changes

2021-03-16 22:05 UTC, gerashegalov approved these changes
LGTM

2021-03-16 23:00 UTC, jlowe commented
@gpucibot merge

2021-03-16 23:00 UTC, merged