Refactor string conversion check
rapidsai/cudf pull request #7599
Opened 2021-03-15 15:56 UTC by ttnghia

This addresses #7557.

In summary:
 * Move `cudf::strings::is_integer()` code from `strings/chars_types.*` to `strings/convert/convert_integers.hpp/cu`
 * Move `cudf::strings::is_float()` code from `strings/chars_types.*` to `strings/convert/convert_floats.hpp/cu`
 * Remove `cudf::strings::all_integer()` and `cudf::strings::all_float()`

2021-03-15 16:37 UTC, davidwendt commented
You will have to change the cython/python interfaces to these too or this will not build.

2021-03-15 17:15 UTC, davidwendt commented on cpp/tests/strings/chars_types_tests.cpp
> +#include <cudf/strings/convert/convert_integers.hpp>
The gtests for `cudf::strings::is_integers()` and `cudf::strings::is_floats()` should be moved to `integers_tests.cpp` and `floats_tests.cpp` appropriately as well.

2021-03-15 17:34 UTC, ttnghia commented
> You will have to change the cython/python interfaces to these too or this will not build.

Done.

2021-03-15 19:11 UTC, ttnghia commented
Rerun tests.

2021-03-15 20:38 UTC, galipremsagar approved these changes
cython/python refactor LGTM

2021-03-15 21:27 UTC, jlowe approved these changes
Java approval

2021-03-15 23:27 UTC, ttnghia commented
Rerun tests.

2021-03-16 02:20 UTC, ttnghia commented
Can anybody tell me how to correctly format python code, please? @rapidsai/cudf-python-codeowners? My local `black` version is 19.10b0 (ubuntu), and if I run `black --check python` then it tells me `166 files would be reformatted, 76 files would be left unchanged`.

2021-03-16 13:43 UTC, ttnghia commented
Rerun tests.

2021-03-16 17:23 UTC, ttnghia commented
Rerun tests.

2021-03-16 17:28 UTC, jrhemstad approved these changes

2021-03-16 21:34 UTC, ttnghia commented
Rerun tests.

2021-03-16 23:45 UTC, ttnghia commented
Rerun tests.

2021-03-17 12:05 UTC, ttnghia commented
Rerun tests.

2021-03-17 14:12 UTC, davidwendt requested changes
Can you update the copyright years for these files?

2021-03-17 14:31 UTC, ttnghia commented
> Can you update the copyright years for these files?

Sorry I forgot that again. Just updated.

2021-03-17 14:42 UTC, davidwendt approved these changes

2021-03-17 18:48 UTC, ttnghia commented
@gpucibot merge

2021-03-17 18:48 UTC, merged