Enable merge for decimal types in cuDF
rapidsai/cudf pull request #7670
Opened 2021-03-22 18:34 UTC by ChrisJar

This enables merging `decimal` columns with different scale and precision values in cuDF. It casts the input to a `Decimal64Dtype` large enough to encapsulate both of the columns being merged to avoid rounding errors and casts the output to be the smallest `Decimal64Dtype` needed encapsulate the results.

This closes #7497

2021-03-22 19:52 UTC, brandon-b-miller requested changes
Thanks so much for working on this! The way our logic usually goes for merge based typecasting is:

- Promote to a common dtype for inner and outer joins
- For left joins, prefer the left dtype, as long as all the data in the right column may be cast to the left dtype with no loss of precision (a scan is O.K. to determine this). For this to work fully you'll need to implement `DecimalColumn.can_cast_safely`, which triggers the code to fall back to the common dtype if the cast isn't safe.  
- for right joins, the invert the rules for left

For numeric cases, we don't require the output dtype be readjusted to be the minimum size required to contain the data, we just leave it as whatever we cast it to before the merge operation. As such, I am not sure you even need the logic in `_libcudf_to_output_casting_rules`.

2021-03-25 00:04 UTC, kkraus14 commented
cc @skirui-source as you assigned yourself the issue this is supposed to resolve

2021-03-25 18:20 UTC, shwina commented on python/cudf/cudf/core/join/casting_logic.py
> +            return rtype
This can never happen, as we handle `"right"` joins much earlier, converting them into left joins.

2021-03-25 18:21 UTC, shwina commented on python/cudf/cudf/core/join/casting_logic.py
> +            precision = scale + min(p1 - s1, p2 - s2)
Could we add a small comment explaining why we chose to compute the result scale/precision this way? I'll admit it's not obvious to me :)

2021-03-25 18:22 UTC, shwina commented on python/cudf/cudf/core/join/casting_logic.py
> +            precision = scale + min(p1 - s1, p2 - s2)
Ditto below for the `"outer"` case.

2021-03-30 15:34 UTC, closed without merging