Add column_device_view to orc writer
rapidsai/cudf pull request #7676
Opened 2021-03-23 04:51 UTC by kaatish

2021-03-23 05:13 UTC, kaatish commented on cpp/src/io/orc/writer_impl.cu
> +  auto device_columns    = table_device_view::create(table);
Will add stream to the create call.

2021-03-24 04:58 UTC, vuule commented
> Fixes #7347, #5682 Addresses #7334

You cannot apply "fixes" to multiple issues like this. Has to be "Fixes #7347, fixes #5682, addresses #7334"

2021-03-24 05:32 UTC, vuule commented
Should this PR close #5682? I see uses of nvstrdesc_s that are not removed in this PR. I would expect for all nvstrdesc_s declaration to be removed before we close #5682.

2021-03-24 06:24 UTC, vuule requested changes
Big fan of the changes. Just needs more span and to add missing docs. And the span use can be pushed to another PR IMO.

Have you run the benchmarks?

2021-03-24 06:24 UTC, vuule commented on cpp/src/io/orc/dict_enc.cu
> +static inline __device__ uint32_t hash_string(const string_view &val)
again, I think this should be passed by value, but libcudf is not very consistent. Will check.

2021-03-24 06:24 UTC, vuule commented on cpp/src/io/orc/dict_enc.cu
> +      uint32_t string_length, hash;
please declare at first use (as const, if possible)

2021-03-24 14:32 UTC, ttnghia commented
> Fixes #7347, #5682 Addresses #7334

Please add more description. It's not obvious to know what this PR is doing unless we have to click/hover on those links to open these issues.

2021-03-24 15:07 UTC, davidwendt commented
> > Fixes #7347, #5682 Addresses #7334
> 
> Please add more description. It's not obvious to know what this PR is doing unless we have to click/hover on those links to open these issues.

Also, the description gets added to the changelog entry so even a simple description here would be helpful.

2021-03-24 17:08 UTC, kaatish commented
> Should this PR close #5682? I see uses of nvstrdesc_s that are not removed in this PR. I would expect for all nvstrdesc_s declaration to be removed before we close #5682.

I have removed the link to that issue for now but it talks about removing nvstrdesc_s in the writers only which has been done in this PR.

2021-03-24 17:29 UTC, vuule commented
> > Should this PR close #5682? I see uses of nvstrdesc_s that are not removed in this PR. I would expect for all nvstrdesc_s declaration to be removed before we close #5682.
> 
> I have removed the link to that issue for now but it talks about removing nvstrdesc_s in the writers only which has been done in this PR.

@devavret to clarify the issue. My interpretation is that all nvstrdesc_s uses should be replaced.

2021-03-24 17:48 UTC, devavret commented
> > > Should this PR close #5682? I see uses of nvstrdesc_s that are not removed in this PR. I would expect for all nvstrdesc_s declaration to be removed before we close #5682.
> > 
> > 
> > I have removed the link to that issue for now but it talks about removing nvstrdesc_s in the writers only which has been done in this PR.
> 
> @devavret to clarify the issue. My interpretation is that all nvstrdesc_s uses should be replaced.

That is true. It just might need one more PR. So it could be an "addresses" here.

2021-03-24 20:09 UTC, vuule approved these changes

2021-03-24 20:33 UTC, devavret commented on cpp/src/io/orc/writer_impl.cu
> +  // void const *data() const noexcept { return _data; }
Cleanups?

2021-03-24 20:38 UTC, devavret commented on cpp/src/io/orc/orc_gpu.h
> +void set_chunk_columns(const table_device_view &view,
doc

2021-03-24 20:42 UTC, kaatish commented on cpp/src/io/orc/writer_impl.cu
> +  // void const *data() const noexcept { return _data; }
Yes, missed this one.

2021-03-24 22:23 UTC, devavret approved these changes

2021-03-24 23:21 UTC, vuule commented
rerun tests

2021-03-25 05:14 UTC, vuule commented
@gpucibot merge

2021-03-25 05:14 UTC, merged