support space in workspace
rapidsai/cudf pull request #7956
Opened 2021-04-14 15:00 UTC by jolorunyomi

# Summary
Support space in WORKSPACE

2021-04-14 15:16 UTC, ajschmidt8 requested changes
found a couple errors

2021-04-14 15:16 UTC, ajschmidt8 commented on ci/gpu/build.sh
> +    export LIB_BUILD_DIR="$WORKSPACE/ci/artifacts/cudf/cpu/libcudf"_work/cpp/build"
```suggestion
    export LIB_BUILD_DIR="$WORKSPACE/ci/artifacts/cudf/cpu/libcudf_work/cpp/build"
```

2021-04-14 15:16 UTC, ajschmidt8 commented on ci/gpu/build.sh
> +py.test -n 6 --cache-clear --basetemp="$WORKSPACE/dask-cudf-cuda-tmp" --junitxml="$WORKSPACE/junit-dask-cudf.xml" -v --cov-config=.coveragerc --cov=dask_cudf --cov-report=xml:"$WORKSPACE/python/dask"
```suggestion
py.test -n 6 --cache-clear --basetemp="$WORKSPACE/dask-cudf-cuda-tmp" --junitxml="$WORKSPACE/junit-dask-cudf.xml" -v --cov-config=.coveragerc --cov=dask_cudf --cov-report=xml:"$WORKSPACE/python/dask_cudf/dask-cudf-coverage.xml" --cov-report term
```

2021-04-14 15:16 UTC, ajschmidt8 commented on ci/gpu/build.sh
> +cd "$WORKSPACE/python/dask"_cudf
```suggestion
cd "$WORKSPACE/python/dask_cudf"
```

2021-04-14 19:16 UTC, jolorunyomi commented
> found a couple errors

Thanks for 👁️ @ajschmidt8

2021-04-14 20:35 UTC, ajschmidt8 requested changes
found one more that might require review

2021-04-14 20:35 UTC, ajschmidt8 commented on ci/cpu/build.sh
> +  CONDA_CHANNEL="-c "$WORKSPACE/ci/artifacts/cudf/cpu/.conda-bld/"
```suggestion
  CONDA_CHANNEL="-c $WORKSPACE/ci/artifacts/cudf/cpu/.conda-bld/"
```

I think this may be fine as it was.

2021-04-15 18:39 UTC, ajschmidt8 approved these changes

2021-05-25 02:26 UTC, harrism commented
@jolorunyomi @ajschmidt8 should this be merged?

2021-05-25 12:40 UTC, jolorunyomi commented
> @jolorunyomi @ajschmidt8 should this be merged?

Yes please this should be merged

2021-05-27 01:26 UTC, GaryShen2008 approved these changes

2021-05-27 01:27 UTC, harrism commented
@gpucibot merge

2021-05-27 01:27 UTC, merged