remove decimals_as_float64 from orc benchmarks
rapidsai/cudf pull request #8007
Opened 2021-04-20 16:43 UTC by cwharris

`decimals_as_float64` was recently removed in https://github.com/rapidsai/cudf/pull/7970. This PR fix benchmark builds by removing it's usage from benchmarks.

2021-04-20 16:46 UTC, galipremsagar approved these changes

2021-04-20 21:20 UTC, codereport approved these changes
:+1:

2021-04-21 05:58 UTC, devavret requested changes
Can drop the MSB from these then? https://github.com/rapidsai/cudf/blob/41af1581f5668a4ec5f8f58acd4dcb6fd29495d7/cpp/benchmarks/io/orc/orc_reader_benchmark.cpp#L168
https://github.com/rapidsai/cudf/blob/41af1581f5668a4ec5f8f58acd4dcb6fd29495d7/cpp/benchmarks/io/orc/orc_reader_benchmark.cpp#L179
https://github.com/rapidsai/cudf/blob/41af1581f5668a4ec5f8f58acd4dcb6fd29495d7/cpp/benchmarks/io/orc/orc_reader_benchmark.cpp#L190

2021-04-22 00:56 UTC, vuule requested changes
missed one more line that needs to change

2021-04-22 00:56 UTC, vuule commented on cpp/benchmarks/io/orc/orc_reader_benchmark.cpp
>    cudf::size_type const chunk_row_cnt = view.num_rows() / num_chunks;
Can't leave a comment there, but line 190 should be modified to only vary the two remaining options:
`{0b11, 0b10, 0b01},  // `true` is default for each boolean parameter here`

2021-04-22 01:18 UTC, vuule approved these changes

2021-04-22 05:37 UTC, devavret approved these changes

2021-04-22 06:24 UTC, vuule commented
@gpucibot merge

2021-04-22 06:24 UTC, merged