Add binary ops benchmark
rapidsai/cudf pull request #8008
Opened 2021-04-20 18:09 UTC by karthikeyann

closes https://github.com/rapidsai/cudf/issues/4118

2021-04-29 18:49 UTC, ttnghia requested changes

2021-04-29 18:49 UTC, ttnghia commented on cpp/benchmarks/binaryop/jit_binaryop_benchmark.cpp
> +// BINARYOP_BENCHMARK_DEFINE(duration_s,   duration_ms,  MOD,                  duration_us);
Should we clean this up?

2021-04-29 18:49 UTC, ttnghia commented on cpp/benchmarks/binaryop/jit_binaryop_benchmark.cpp
> +#include <fixture/benchmark_fixture.hpp>
Please reorder the headers (close to far).

2021-04-30 12:04 UTC, ttnghia approved these changes

2021-04-30 14:33 UTC, rgsl888prabhu approved these changes

2021-05-03 06:38 UTC, karthikeyann commented
```
JIT_BINARYOP<float, int64_t, int32_t>/ADD/10000/manual_time                                                        0.017 ms        0.037 ms        41566
JIT_BINARYOP<float, int64_t, int32_t>/ADD/100000/manual_time                                                       0.022 ms        0.040 ms        31392
JIT_BINARYOP<float, int64_t, int32_t>/ADD/1000000/manual_time                                                      0.047 ms        0.064 ms        14925
JIT_BINARYOP<float, int64_t, int32_t>/ADD/10000000/manual_time                                                     0.280 ms        0.299 ms         2501
JIT_BINARYOP<float, int64_t, int32_t>/ADD/100000000/manual_time                                                     2.66 ms         2.69 ms          264
JIT_BINARYOP<duration_s, duration_D, duration_ms>/SUB/10000/manual_time                                            0.018 ms        0.037 ms        38226
JIT_BINARYOP<duration_s, duration_D, duration_ms>/SUB/100000/manual_time                                           0.022 ms        0.040 ms        29850
JIT_BINARYOP<duration_s, duration_D, duration_ms>/SUB/1000000/manual_time                                          0.051 ms        0.070 ms        13703
JIT_BINARYOP<duration_s, duration_D, duration_ms>/SUB/10000000/manual_time                                         0.345 ms        0.365 ms         2023
JIT_BINARYOP<duration_s, duration_D, duration_ms>/SUB/100000000/manual_time                                         3.41 ms         3.45 ms          205
JIT_BINARYOP<float, float, int64_t>/MUL/10000/manual_time                                                          0.019 ms        0.038 ms        34950
JIT_BINARYOP<float, float, int64_t>/MUL/100000/manual_time                                                         0.022 ms        0.039 ms        31819
JIT_BINARYOP<float, float, int64_t>/MUL/1000000/manual_time                                                        0.044 ms        0.064 ms        15740
JIT_BINARYOP<float, float, int64_t>/MUL/10000000/manual_time                                                       0.286 ms        0.306 ms         2444
JIT_BINARYOP<float, float, int64_t>/MUL/100000000/manual_time                                                       2.87 ms         2.90 ms          244
JIT_BINARYOP<int64_t, int64_t, int64_t>/DIV/10000/manual_time                                                      0.018 ms        0.037 ms        37241
JIT_BINARYOP<int64_t, int64_t, int64_t>/DIV/100000/manual_time                                                     0.024 ms        0.041 ms        28941
JIT_BINARYOP<int64_t, int64_t, int64_t>/DIV/1000000/manual_time                                                    0.057 ms        0.076 ms        12263
JIT_BINARYOP<int64_t, int64_t, int64_t>/DIV/10000000/manual_time                                                   0.408 ms        0.428 ms         1717
JIT_BINARYOP<int64_t, int64_t, int64_t>/DIV/100000000/manual_time                                                   3.96 ms         4.00 ms          177
JIT_BINARYOP<int64_t, int64_t, int64_t>/TRUE_DIV/10000/manual_time                                                 0.019 ms        0.038 ms        37909
JIT_BINARYOP<int64_t, int64_t, int64_t>/TRUE_DIV/100000/manual_time                                                0.023 ms        0.040 ms        30107
JIT_BINARYOP<int64_t, int64_t, int64_t>/TRUE_DIV/1000000/manual_time                                               0.056 ms        0.075 ms        12338
JIT_BINARYOP<int64_t, int64_t, int64_t>/TRUE_DIV/10000000/manual_time                                              0.406 ms        0.426 ms         1724
JIT_BINARYOP<int64_t, int64_t, int64_t>/TRUE_DIV/100000000/manual_time                                              3.96 ms         4.00 ms          177
JIT_BINARYOP<int64_t, int64_t, int64_t>/FLOOR_DIV/10000/manual_time                                                0.019 ms        0.038 ms        35681
JIT_BINARYOP<int64_t, int64_t, int64_t>/FLOOR_DIV/100000/manual_time                                               0.024 ms        0.041 ms        29291
JIT_BINARYOP<int64_t, int64_t, int64_t>/FLOOR_DIV/1000000/manual_time                                              0.057 ms        0.076 ms        12018
JIT_BINARYOP<int64_t, int64_t, int64_t>/FLOOR_DIV/10000000/manual_time                                             0.407 ms        0.427 ms         1717
JIT_BINARYOP<int64_t, int64_t, int64_t>/FLOOR_DIV/100000000/manual_time                                             3.96 ms         3.99 ms          177
JIT_BINARYOP<double, double, double>/MOD/10000/manual_time                                                         0.018 ms        0.038 ms        38669
JIT_BINARYOP<double, double, double>/MOD/100000/manual_time                                                        0.023 ms        0.041 ms        28886
JIT_BINARYOP<double, double, double>/MOD/1000000/manual_time                                                       0.058 ms        0.076 ms        11825
JIT_BINARYOP<double, double, double>/MOD/10000000/manual_time                                                      0.408 ms        0.427 ms         1717
JIT_BINARYOP<double, double, double>/MOD/100000000/manual_time                                                      3.97 ms         4.02 ms          176
JIT_BINARYOP<int64_t, int64_t, double>/POW/10000/manual_time                                                       0.019 ms        0.038 ms        35454
JIT_BINARYOP<int64_t, int64_t, double>/POW/100000/manual_time                                                      0.026 ms        0.044 ms        26382
JIT_BINARYOP<int64_t, int64_t, double>/POW/1000000/manual_time                                                     0.062 ms        0.081 ms        10983
JIT_BINARYOP<int64_t, int64_t, double>/POW/10000000/manual_time                                                    0.422 ms        0.441 ms         1662
JIT_BINARYOP<int64_t, int64_t, double>/POW/100000000/manual_time                                                    4.06 ms         4.10 ms          172
JIT_BINARYOP<int64_t, int32_t, int16_t>/BITWISE_AND/10000/manual_time                                              0.016 ms        0.036 ms        42023
JIT_BINARYOP<int64_t, int32_t, int16_t>/BITWISE_AND/100000/manual_time                                             0.021 ms        0.039 ms        32868
JIT_BINARYOP<int64_t, int32_t, int16_t>/BITWISE_AND/1000000/manual_time                                            0.046 ms        0.062 ms        15250
JIT_BINARYOP<int64_t, int32_t, int16_t>/BITWISE_AND/10000000/manual_time                                           0.258 ms        0.275 ms         2716
JIT_BINARYOP<int64_t, int32_t, int16_t>/BITWISE_AND/100000000/manual_time                                           2.40 ms         2.42 ms          292
JIT_BINARYOP<int16_t, int32_t, int64_t>/BITWISE_OR/10000/manual_time                                               0.017 ms        0.036 ms        40212
JIT_BINARYOP<int16_t, int32_t, int64_t>/BITWISE_OR/100000/manual_time                                              0.020 ms        0.038 ms        32908
JIT_BINARYOP<int16_t, int32_t, int64_t>/BITWISE_OR/1000000/manual_time                                             0.039 ms        0.059 ms        17544
JIT_BINARYOP<int16_t, int32_t, int64_t>/BITWISE_OR/10000000/manual_time                                            0.253 ms        0.273 ms         2711
JIT_BINARYOP<int16_t, int32_t, int64_t>/BITWISE_OR/100000000/manual_time                                            2.57 ms         2.59 ms          273
JIT_BINARYOP<int16_t, int64_t, int32_t>/BITWISE_XOR/10000/manual_time                                              0.018 ms        0.037 ms        38144
JIT_BINARYOP<int16_t, int64_t, int32_t>/BITWISE_XOR/100000/manual_time                                             0.021 ms        0.039 ms        32280
JIT_BINARYOP<int16_t, int64_t, int32_t>/ [...]

2021-05-04 00:49 UTC, harrism approved these changes

2021-05-04 00:49 UTC, harrism commented
@gpucibot merge

2021-05-04 00:49 UTC, merged