Numba version and deprecation updates
rapidsai/cudf pull request #8017
Opened 2021-04-21 10:21 UTC by gmarkall

Some small Numba-related changes:

- Testing on CI appears to be picking up Numba 0.53.1, and there have been quite a lot of CUDA changes between Numba 0.49 (the old minimum) and 0.53.1 - increase the minimum required Numba version to 0.53.1
  accordingly.
- Remove old import guards and alternatives for Numba versions < 0.49 - these were needed because of Numba's internals refactor between 0.48 and 0.49.
- Replace the use of `inspect_ptx()` with `compile_ptx()` in `test_ptx_generic()` - `inspect_ptx()` has always had various issues so it is being deprecated and will be removed in a later version. `compile_ptx()` provides a better alternative. See https://github.com/numba/numba/pull/6953

2021-04-21 13:47 UTC, kkraus14 reviewed
Changes LGTM but we need to handle the versioning in the conda environment files and the conda recipes as well.

2021-04-22 11:29 UTC, gmarkall commented
> Changes LGTM but we need to handle the versioning in the conda environment files and the conda recipes as well.

Many thanks for catching this!

2021-04-22 14:49 UTC, kkraus14 approved these changes

2021-04-22 16:28 UTC, kkraus14 commented
Need to update the integration repo as well, I will put in a PR

https://github.com/rapidsai/integration/blob/branch-0.19/conda/recipes/versions.yaml#L105-L106

2021-04-23 19:51 UTC, ajschmidt8 approved these changes

2021-04-23 22:01 UTC, galipremsagar requested changes

2021-04-23 22:01 UTC, galipremsagar commented on python/cudf/requirements/cuda-11.1/dev_requirements.txt
> +numba>=>=0.53.1
```suggestion
numba>=0.53.1
```

looks like a typo here

2021-04-26 20:37 UTC, galipremsagar approved these changes

2021-04-26 20:37 UTC, kkraus14 commented
@gpucibot merge

2021-04-27 03:25 UTC, kkraus14 commented
@gpucibot merge

2021-04-27 03:25 UTC, merged