Split up scan.cu to improve compile time
rapidsai/cudf pull request #8183
Opened 2021-05-07 17:57 UTC by davidwendt

Moving to thrust 1.12 from 1.10 increased compile time for `scan.cu` significantly. This is likely due to the improvements made to the scan algorithm to use CUB's DeviceScan: https://github.com/NVIDIA/thrust/pull/1304

This PR splits up scan.cu into `scan_exclusive.cu` and `scan_inclusive.cu` to help speed up build time when running parallel compiles.
This PR also includes patches to libcudf's thrust's CUB source to disable compiling tuning artifacts for architectures below sm60.
The result is about 2 minute (~11%) overall speedup on a parallel  build and reduces the libcudf.so by about 25MB (17%).

2021-05-10 15:19 UTC, robertmaynard reviewed
`scan_delete_me.cu` needs to be deleted :)

2021-05-10 15:32 UTC, ajschmidt8 approved these changes
Approving `ops-codeowner` file changes

2021-05-10 22:40 UTC, harrism commented
> This PR also includes patches to libcudf's thrust's CUB source to disable compiling tuning artifacts for architectures below sm60.

Since Thrust is header-only, shouldn't only the architectures the compilation unit is being compiled for be compiled anyway?

2021-05-11 23:02 UTC, harrism commented
What are the chances of having two thrust patch PRs at the same time...

2021-05-12 15:27 UTC, nvdbaranec requested changes
Some copyright stuff.

2021-05-12 15:27 UTC, nvdbaranec commented on cpp/src/reductions/scan/scan.cpp
> + * Copyright (c) 2019-2021, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2021, NVIDIA CORPORATION.
```

2021-05-12 15:27 UTC, nvdbaranec commented on cpp/src/reductions/scan/scan.cuh
> + * Copyright (c) 2019-2021, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2021, NVIDIA CORPORATION.
```

2021-05-12 15:27 UTC, nvdbaranec commented on cpp/src/reductions/scan/scan_exclusive.cu
> + * Copyright (c) 2019-2021, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2021, NVIDIA CORPORATION.
```

2021-05-12 15:27 UTC, nvdbaranec commented on cpp/src/reductions/scan/scan_inclusive.cu
> + * Copyright (c) 2019-2021, NVIDIA CORPORATION.
```suggestion
 * Copyright (c) 2021, NVIDIA CORPORATION.
```

2021-05-12 19:45 UTC, nvdbaranec approved these changes

2021-05-14 14:22 UTC, davidwendt commented
@gpucibot merge

2021-05-14 14:22 UTC, merged