Fix structs column description in dev docs
rapidsai/cudf pull request #8318
Opened 2021-05-21 19:29 UTC by isVoid

Currently structs column section of developer documentation mentions there's an offset column tied to its layout. This is not true and this PR fixes that.

2021-05-21 19:37 UTC, rgsl888prabhu approved these changes

2021-05-21 19:40 UTC, nvdbaranec requested changes

2021-05-21 19:40 UTC, nvdbaranec commented on cpp/docs/DEVELOPER_GUIDE.md
> +field of struct `42`, etc.
<!--StartFragment-->With this representation, `child[0][10]` is the first field of struct `10`, `child[1][42]` is the second




    
```suggestion
With this representation, `child[0][10]` is row 10 of the first field of the struct, `child[1][42]` is row 42 of the second field of the struct.
```

2021-05-21 19:40 UTC, nvdbaranec commented on cpp/docs/DEVELOPER_GUIDE.md
> +not represented.
```suggestion
A struct is a nested data type with a set of child columns each representing an individual field of a logical struct. Field names are not represented.
```

2021-05-21 20:21 UTC, mythrocks commented on cpp/docs/DEVELOPER_GUIDE.md
> +`STRUCT` and contains no data, its size represents the number of structs in the column, and its
```suggestion
`STRUCT` and contains no data, its size represents the number of struct rows in the column, and its
```

2021-05-21 20:22 UTC, mythrocks commented
Thanks for fixing this. I'm not sure how I missed this when reviewing the last doc PR. I guess I concentrated on the `struct` null-mask bit.

2021-05-21 22:24 UTC, mythrocks approved these changes

2021-05-25 00:55 UTC, harrism approved these changes

2021-05-25 14:23 UTC, nvdbaranec approved these changes

2021-05-25 14:23 UTC, nvdbaranec commented
@gpucibot merge

2021-05-25 14:23 UTC, merged