Fix null_equality config of rolling_collect_set
rapidsai/cudf pull request #8415
Opened 2021-06-01 10:13 UTC by sperlingxx

Fix #8405, and add some tests for various `null_equality` and `nan_equality`.

2021-06-01 12:16 UTC, ttnghia requested changes
Also please check and fix other comments as I may miss something.

2021-06-01 12:16 UTC, ttnghia commented on cpp/tests/groupby/collect_set_tests.cpp
> +  // null equal with nan unequal
```suggestion
  // null equal with nan equal
```

2021-06-01 12:16 UTC, ttnghia commented on cpp/tests/groupby/collect_set_tests.cpp
> +  // null unequal with nan unequal
```suggestion
  // null unequal with nan equal
```

2021-06-02 00:25 UTC, harrism commented
We are code frozen. Can this wait for 21.08?

2021-06-02 12:05 UTC, ttnghia approved these changes

2021-06-02 23:49 UTC, mythrocks approved these changes
This looks good. The only gripe I have is that the `rolling/collect_ops_test.cpp` does not specifically have a test for `nan_equality`, like you have added for `groupby`. :]

2021-06-03 07:42 UTC, sperlingxx commented
> This looks good. The only gripe I have is that the `rolling/collect_ops_test.cpp` does not specifically have a test for `nan_equality`, like you have added for `groupby`. :]

I added it. Thanks for catching that :)

2021-06-03 15:01 UTC, sperlingxx commented
@gpucibot merge

2021-06-03 15:02 UTC, merged