Add constructors accepting orphaned buffer for `string_scalar` and `struct_scalar`
rapidsai/cudf pull request #8428
Opened 2021-06-02 15:36 UTC by ttnghia

This PR adds some constructors for `string_scalar` and `struct_scalar` that accept an orphaned buffer. By doing so, the buffer is moved into the internal buffer of the newly constructed scalars instead of copying.

This also cleanup/rewrite doxygens for `scalar.hpp`.

Closes #8427.

2021-06-02 18:24 UTC, davidwendt requested changes
Why are all the comments reformatted?

2021-06-02 18:24 UTC, davidwendt commented on cpp/include/cudf/scalar/scalar.hpp
> +   * Note that this function move the orphaned buffer into the internal buffer.
```suggestion
   * 
   * Note that this constructor moves the orphaned buffer into the internal buffer.
```

2021-06-02 18:24 UTC, davidwendt commented on cpp/include/cudf/scalar/scalar.hpp
> +   * Note that this function move the orphaned table into the internal data table.
```suggestion
   * 
   * Note that this function moves the orphaned table into the internal table member.
```

2021-06-02 18:31 UTC, ttnghia commented
> Why are all the comments reformatted?

I just want to enforce aesthetic consistency for them: some comments ended with a period (`.`) while some others don't.

2021-06-03 01:14 UTC, harrism requested changes
I think secretly this PR is more about adding periods to the comments. :)

I think this is a good addition, just some doc suggestions.

2021-06-03 01:14 UTC, harrism commented on cpp/include/cudf/scalar/scalar.hpp
> +   * @param[in] mr Device memory resource to use for device memory allocation.
While you are adding periods, you could remove the [in]s.

2021-06-03 01:14 UTC, harrism commented on cpp/include/cudf/scalar/scalar.hpp
> +   * @brief Construct a new string scalar object from an orphaned buffer in device memory.
Let's not add potentially confusing terminology ("orphaned"). 
```suggestion
   * @brief Construct a new string scalar object by moving an existing string data buffer.
```

2021-06-03 01:14 UTC, harrism commented on cpp/include/cudf/scalar/scalar.hpp
> +   * Note that this constructor moves the orphaned buffer into the internal data buffer.
```suggestion
   * Note that this constructor moves the existing buffer into the internal data buffer; no copy is performed.
```

2021-06-03 01:14 UTC, harrism commented on cpp/include/cudf/scalar/scalar.hpp
> +   * @brief Construct a new struct scalar object from an orphaned table in device memory.
```suggestion
   * @brief Construct a new struct scalar object from an existing table in device memory.
```

2021-06-03 01:14 UTC, harrism commented on cpp/include/cudf/scalar/scalar.hpp
> +   * Note that this constructor moves the orphaned table into the internal data table.
```suggestion
   * Note that this constructor moves the existing table data into the internal data table; no copies are performed.
```

2021-06-03 01:17 UTC, harrism commented
> Other (line adjustment) may be due to some explicit reformatting done by my IDE.

Please disable this and just use our mandated clang-format settings. Other than automatic line-wrapping to ensure passing clang-format tests, any reformatting of comments should be done manually and not on every file save or it will make PRs harder to review.

I had a hard time getting to the real changes in this PR.

2021-06-03 02:41 UTC, ttnghia commented
> Please disable this and just use our mandated clang-format settings. Other than automatic line-wrapping to ensure passing clang-format tests, any reformatting of comments should be done manually and not on every file save or it will make PRs harder to review (and cause more conflicts, e.g. with my in-progress scalar.hpp refactor PR)
> 
> I had a hard time getting to the real changes in this PR.

I'm sorry about that. Typically it is disabled, I just accidentally called that this time.

2021-06-03 13:02 UTC, ttnghia commented
Rerun tests.

2021-06-03 20:45 UTC, ttnghia commented
Rerun tests.

2021-06-04 13:54 UTC, ttnghia commented
Rerun tests.

2021-06-07 20:20 UTC, hyperbolic2346 approved these changes

2021-06-07 20:41 UTC, mythrocks approved these changes
LGTM.

(Sorry, I thought I had already approved this PR last week.)

2021-06-07 21:04 UTC, davidwendt approved these changes

2021-06-08 04:25 UTC, harrism approved these changes

2021-06-08 10:41 UTC, karthikeyann approved these changes

2021-06-08 11:49 UTC, ttnghia commented
@gpucibot merge

2021-06-08 11:49 UTC, merged