Add public libcudf match_dictionaries API
rapidsai/cudf pull request #8429
Opened 2021-06-02 20:42 UTC by davidwendt

This PR creates a public API for the internal libcudf `cudf::dictionary::detail::match_dictionaries` function to help with transitioning the cudf python CategoricalColumn over to using the libcudf dictionary column.

No function has changed or been added but this PR does add a formal gtest for the new public API.

2021-06-02 23:00 UTC, ttnghia approved these changes

2021-06-02 23:25 UTC, vuule requested changes
a few very small suggestions

2021-06-02 23:25 UTC, vuule commented on cpp/include/cudf/dictionary/update_keys.hpp
> + * @return New dictionary column.
```suggestion
 * @return New dictionary columns.
```

2021-06-02 23:25 UTC, vuule commented on cpp/include/cudf/dictionary/update_keys.hpp
> +  std::vector<dictionary_column_view> input,
```suggestion
  host_span<dictionary_column_view const> input,
```

2021-06-03 17:22 UTC, vuule approved these changes
Thank you :)

2021-06-03 18:19 UTC, devavret approved these changes

2021-06-04 00:27 UTC, galipremsagar commented
rerun tests

2021-06-04 12:28 UTC, davidwendt commented
@gpucibot merge

2021-06-04 12:28 UTC, merged