Fix failures when performing binary operations on DataFrames with empty columns
rapidsai/cudf pull request #8452
Opened 2021-06-07 21:26 UTC by ChrisJar

Closes #8434

2021-06-14 14:43 UTC, galipremsagar requested changes

2021-07-19 16:28 UTC, beckernick commented
@ChrisJar is this on target for 21.08 or should we push to 21.10?

2021-07-19 16:54 UTC, ChrisJar commented
Yep! This is still on track I'm just finishing up some refactoring that should be done by this afternoon

2021-07-20 16:41 UTC, ChrisJar commented on python/cudf/cudf/core/series.py
> +            and self.isnull().all()
So the issue is that in Pandas performing an arithmetic binary operation on empty or an all null object columns returns the column unchanged and performing a comparison operation returns the appropriate boolean column. However, in cudf both of these actions currently throw. The behavior is already correct for other column types it just needs to be fixed for object columns

2021-07-20 16:46 UTC, galipremsagar approved these changes

2021-07-20 16:49 UTC, galipremsagar approved these changes

2021-07-20 17:15 UTC, charlesbluca approved these changes

2021-07-20 17:23 UTC, galipremsagar commented
@gpucibot merge

2021-07-20 17:23 UTC, merged