Modify strings::extract to return groups in a single pass
rapidsai/cudf pull request #8460
Opened 2021-06-08 17:41 UTC by davidwendt

This PR modifies the internal regex `reprog_device::extract` function to return all matching groups in a single call. Previously, retrieving each group range required individual calls to this `extract` function requiring re-matching the entire given pattern. The code logic would identify each group but only return the range for the specified group. 

The code change here passes a pre-allocated global memory array to capture each group range in a single pass. The extract is an all-or-nothing process. In fact, a `find` function must first be executed to retrieve the bounds of the given pattern. So if any of the groups are missing or do not match, no groups are returned for that row. Retrieving the last group would always require processing the previous groups and the code logic now records those positions in the global memory array. The memory array can then be used directly to build the output columns.

This simplifies the code around extract and also improves performance especially for long strings or patterns with many groups. For small strings and a small number of groups, the gbenchmark showed equivalent performance to the previous implementation. For larger strings and more groups, the gbenchmark showed a 2-3x improvement.

2021-06-15 23:11 UTC, vuule requested changes
Looks good, got a few mostly stylistic suggestions.
Didn't dig too deep into the algorithmic aspect of the changes, let me know if it's needed.

2021-06-16 15:29 UTC, davidwendt commented on cpp/src/strings/regex/regex.cuh
> +    int32_t idx, string_view const& d_str, int32_t begin, int32_t end, string_index_pair* indices);
Thanks Vukasin. I'd rather keep this particular API as a simple data pointer for now. But I think using the `device_2dspan` and `device_span` in the calling functions makes sense.

2021-06-16 15:30 UTC, davidwendt commented on cpp/src/strings/extract.cu
> +    for (int i = 0; i < groups; ++i) { d_output[i] = string_index_pair{nullptr, 0}; }
I can use a `thrust::fill` here.

2021-06-16 15:40 UTC, davidwendt commented on cpp/src/strings/regex/regex.cuh
> +    int32_t idx, string_view const& d_str, int32_t begin, int32_t end, string_index_pair* indices);
After adding the `device_2dspan` changing this interface to accept a `device_span` was fairly trivial.

2021-06-16 22:31 UTC, vuule approved these changes

2021-06-17 15:32 UTC, robertmaynard approved these changes
CMake changes LGTM

2021-06-18 18:38 UTC, cwharris approved these changes

2021-06-18 18:58 UTC, vuule commented
@gpucibot merge

2021-06-18 18:58 UTC, merged