Struct scalar from host dictionary
rapidsai/cudf pull request #8629
Opened 2021-06-29 20:35 UTC by shaneding

Allows the creation of a `struct_scalar` from python dictionary

2021-07-06 22:31 UTC, brandon-b-miller commented on python/cudf/cudf/_lib/scalar.pyx
> +        # print("hello world")
```suggestion
```

2021-07-07 16:52 UTC, brandon-b-miller commented on python/cudf/cudf/_lib/scalar.pyx
> +        new struct_scalar(struct_view)
Missing `valid` here?

2021-07-07 16:53 UTC, brandon-b-miller commented on python/cudf/cudf/tests/test_struct.py
> +        {"b": [], "c": [1, 2, 3]},
We also want to make sure we can construct an `NA` scalar here so long as we pass a valid `StructDtype`.

2021-07-07 16:54 UTC, brandon-b-miller requested changes
Couple of questions but looking great.

2021-07-09 13:51 UTC, brandon-b-miller approved these changes

2021-07-09 14:47 UTC, rgsl888prabhu approved these changes

2021-07-09 15:27 UTC, shaneding commented
@gpucibot merge

2021-07-09 15:29 UTC, brandon-b-miller commented
@gpucibot merge

2021-07-09 15:29 UTC, merged