Ensure dev environment uses Arrow GPU packages
rapidsai/cudf pull request #8637
Opened 2021-07-01 19:12 UTC by charlesbluca

With #7495 merged, it seems like the dev environment files create an environment with the CPU packages for `pyarrow` and `arrow-cpp`; this results in failure when trying to compile libcudf or `import cudf`:

```python
ModuleNotFoundError: No module named 'pyarrow._cuda'
    from cudf import rmm
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import _internals, buffer, column, column_accessor, common
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/_internals/__init__.py", line 3, in <module>
    from cudf.core._internals.where import where
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/_internals/where.py", line 11, in <module>
    from cudf.core.column import ColumnBase
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/column/categorical.py", line 25, in <module>
    from cudf import _lib as libcudf
  File "/opt/conda/lib/python3.8/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
ImportError: libarrow_cuda.so.400: cannot open shared object file: No such file or directory
```

This updates the dev environments and recipe to ensure that the GPU package of `pyarrow` (and `arrow-cpp` accordingly) are used.

2021-07-01 19:46 UTC, raydouglass requested changes
Can you also update https://github.com/rapidsai/cudf/blob/branch-21.08/conda/recipes/libcudf/meta.yaml#L40

2021-07-01 19:47 UTC, charlesbluca commented
Do you know if the formatting for the recipe is correct? Not sure if the syntax differs significantly from the conda env file

2021-07-02 03:13 UTC, jakirkham commented on conda/recipes/cudf/meta.yaml
> +    - pyarrow 4.0.1=*cuda
```suggestion
    - pyarrow 4.0.1 *cuda
```

2021-07-02 17:58 UTC, ajschmidt8 approved these changes

2021-07-02 18:01 UTC, jakirkham commented
@gpucibot merge

2021-07-02 18:01 UTC, merged

2021-07-02 18:02 UTC, jakirkham commented
Thanks all! 😄

2021-07-02 22:26 UTC, jakirkham commented
Looks like we needed another change to the recipe. Added here ( https://github.com/rapidsai/cudf/pull/8651 )