Fix repeated mangled names in read_csv with duplicate column names
rapidsai/cudf pull request #8645
Opened 2021-07-02 14:51 UTC by karthikeyann

Fixes mangled name bug `read_csv` with duplicate columns.
mismatch with pandas behavior.
#### csv file:
```csv
A,A,A.1,A,A.2,A,A.4,A,A
1,2,3,4.0,a,a,a.4,a,a
2,4,6,8.0,b,b,b.4,b,a
3,6,2,6.0,c,c,c.4,c,c
```

|A|	A|		A.1|	A|		A.2|	A|		A.4|	A|		A|
|-|-|-|-|-|-|-|-|-|
|A|	A.1|	A.1.1|	A.2|	A.2.1|	A.3| 	A.4| 	A.4.1|	A.5|

#### Pandas:
```python
In [1]: import pandas as pd
In [2]: pd.read_csv("test.csv")
Out[2]: 
   A  A.1  A.1.1  A.2 A.2.1 A.3  A.4 A.4.1 A.5
0  1    2      3  4.0     a   a  a.4     a   a
1  2    4      6  8.0     b   b  b.4     b   a
2  3    6      2  6.0     c   c  c.4     c   c
```

#### cudf: (21.08 nightly docker)
```python
In [1]: import cudf
In [2]: cudf.__version__
Out[2]: '21.08.00a+238.gfba09e66d8'
In [3]: cudf.read_csv("test.csv")
Out[3]: 
   A  A.1 A.2 A.3 A.4 A.5
0  1    3   a   a   a   a
1  2    6   b   b   b   a
2  3    2   c   c   c   c
```

This PR fixes this issue.
```python
In [2]: cudf.read_csv("test.csv")
Out[2]: 
   A  A.1  A.1.1  A.2 A.2.1 A.3  A.4 A.4.1 A.5
0  1    2      3  4.0     a   a  a.4     a   a
1  2    4      6  8.0     b   b  b.4     b   a
2  3    6      2  6.0     c   c  c.4     c   c
```

2021-07-03 04:26 UTC, vuule approved these changes

2021-07-05 07:46 UTC, elstehle approved these changes

2021-07-05 07:48 UTC, vuule requested changes
Just remembered - please add a test case that exercises the behavior change.

2021-07-05 08:55 UTC, vuule approved these changes

2021-07-05 14:25 UTC, rgsl888prabhu approved these changes

2021-07-06 04:45 UTC, hyperbolic2346 approved these changes

2021-07-06 06:14 UTC, vuule commented
rerun tests

2021-07-06 12:40 UTC, karthikeyann commented
@gpucibot merge

2021-07-06 20:06 UTC, merged