Add `datetime::is_leap_year`
rapidsai/cudf pull request #8711
Opened 2021-07-09 23:30 UTC by isVoid

This PR adds `datetime::is_leap_year`. The function returns `true` for datetime column rows with leap year; `false` for rows with non leap years, and `null` for null rows.

2021-07-12 09:21 UTC, karthikeyann requested changes

2021-07-12 09:21 UTC, karthikeyann commented on cpp/include/cudf/detail/datetime.hpp
> +  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());
`stream` argument is missing.
```suggestion
  rmm::cuda_stream_view stream        = rmm::cuda_stream_default,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());
```

2021-07-12 09:21 UTC, karthikeyann commented on cpp/src/datetime/datetime_ops.cu
> +  auto mask   = copy_bitmask(column.null_mask(), column.offset(), column.offset() + column.size());
use `stream` and `mr` for `copy_bitmask`
```suggestion
  auto mask   = detail::copy_bitmask(column, stream, mr);
```

2021-07-12 09:21 UTC, karthikeyann commented on cpp/include/cudf/datetime.hpp
> + * `output[i] is null` if year of `column[i]` is null
```suggestion
 * `output[i] is null` if `column[i]` is null
```

2021-07-12 09:21 UTC, karthikeyann commented on cpp/src/datetime/datetime_ops.cu
>  #include <cudf/null_mask.hpp>
```suggestion
```

2021-07-12 13:35 UTC, jrhemstad commented on cpp/src/datetime/datetime_ops.cu
> +  auto years_view = years->view();
There's no need to materialize the column of years. You can extract the year on the fly inside your transform kernel below.

2021-07-12 20:32 UTC, isVoid commented
The implementation has changed to largely reusing existing `apply_datetime_op` scaffolding.

2021-07-13 00:07 UTC, harrism approved these changes
Looks great.

2021-07-13 02:35 UTC, karthikeyann approved these changes

2021-07-13 05:43 UTC, harrism commented
@gpucibot merge

2021-07-13 05:43 UTC, merged