Handle sliced structs properly in pack/contiguous_split.
rapidsai/cudf pull request #8739
Opened 2021-07-13 22:33 UTC by nvdbaranec

Pre-sliced struct columns (those with a positive offset) were not being handled correctly.

Depends on https://github.com/rapidsai/cudf/pull/8738  (a fix in slice() itself)

2021-07-15 16:00 UTC, ttnghia requested changes

2021-07-15 16:02 UTC, nvdbaranec commented on cpp/include/cudf/detail/null_mask.cuh
> +  subtract_set_bits_range_boundaries_kerenel<<<grid.num_blocks,
Wait, what happened here?  Didn't I fix this yesterday?

2021-07-15 16:03 UTC, ttnghia commented on cpp/include/cudf/detail/null_mask.cuh
> +  subtract_set_bits_range_boundaries_kerenel<<<grid.num_blocks,
Yesterday typo was in your other PR.

2021-07-15 16:15 UTC, ttnghia approved these changes

2021-07-15 16:15 UTC, ttnghia commented on cpp/include/cudf/detail/null_mask.cuh
> + * updated
Sorry that I'm a bit OCD about the style. This is just a suggestion (align multiple-line param doxygen with the parameter name), you can ignore it if you don't like :smiley: 
```suggestion
 * @param[in] bitmask The bitmask whose non-zero bits outside the range in the
 *                    boundary words will be counted.
 * @param[in] num_ranges The number of ranges
 * @param[in] first_bit_indices The indices (inclusive) of the first bit in each
 *                     range
 * @param[in] last_bit_indices The indices (exclusive) of the last bit in each
 *                     range
 * @param[in,out] null_counts The number of non-zero bits in each range to be
 *                          updated
```

2021-07-15 16:15 UTC, ttnghia commented on cpp/include/cudf/detail/null_mask.cuh
> + *
```suggestion
```

2021-07-15 16:15 UTC, ttnghia commented on cpp/include/cudf/detail/null_mask.cuh
> +  __host__ to_word_index(bool inclusive, size_type const* d_bit_indices)
I'm not sure if we ever need the `__host__` qualifier here.

2021-07-15 17:47 UTC, robertmaynard approved these changes
CMake changes LGTM

2021-07-19 18:04 UTC, vuule approved these changes

2021-07-19 18:45 UTC, nvdbaranec commented
Temporarily adding do-not-merge tag so @charlesbluca can run some additional tests.

2021-07-19 18:56 UTC, vuule approved these changes
still looks good :)

2021-07-19 19:00 UTC, ttnghia approved these changes

2021-07-19 22:50 UTC, nvdbaranec commented
@gpucibot merge

2021-07-19 22:50 UTC, merged