Provide a better error message when `CUDA::cuda_driver` not found
rapidsai/cudf pull request #8794
Opened 2021-07-20 13:45 UTC by robertmaynard

cuDF JITIFY sources require the the CUDA driver ( libcuda.so ) or
stub to exist for correct compilation/linking. If they can't be
found explain why, instead of producing a bad error message

2021-07-20 18:24 UTC, davidwendt commented
As one who was victim of the build failure that this PR addresses, I have verified this change works for me.

2021-07-20 21:56 UTC, harrism requested changes

2021-07-20 21:56 UTC, harrism commented on cpp/CMakeLists.txt
> +endif()
The error message is unclear. It sounds like it requires building libcuda.so, which it doesn't. :)
```suggestion
if(NOT TARGET CUDA::cuda_driver)
    message(FATAL_ERROR "Building libcudf requires `libcuda.so` to be present.
        This error often occurs when trying to build libcudf from a container without the NVIDIA runtime loaded.")
endif()
```

2021-07-22 01:46 UTC, harrism approved these changes

2021-07-22 01:46 UTC, harrism commented
@gpucibot merge

2021-07-22 01:46 UTC, merged