Add groupby_aggregation and groupby_scan_aggregation classes and force their usage.
rapidsai/cudf pull request #8906
Opened 2021-07-29 23:00 UTC by nvdbaranec

Followup to https://github.com/rapidsai/cudf/pull/8052
Partially addresses Partially addresses #7106

Adds the `groupby_aggregation` class and forces usage of that type when calling `groupby::aggregate()`

Adds the `groupby_scan_aggregation` class and forces usage of that type when calling `groupby::scan()`

2021-07-30 15:43 UTC, revans2 commented
@nvdbaranec this breaks the java code/build.  Could you apply this somewhat of a hack patch to this so we don't break the java code?  I'll file a follow on issue to try and make the java APIs match what is being done for the C++ APIs.

```diff
diff --git a/java/src/main/native/src/TableJni.cpp b/java/src/main/native/src/TableJni.cpp
index c092450da1..f306121947 100644
--- a/java/src/main/native/src/TableJni.cpp
+++ b/java/src/main/native/src/TableJni.cpp
@@ -2194,11 +2194,18 @@ JNIEXPORT jlongArray JNICALL Java_ai_rapids_cudf_Table_groupByAggregate(
     for (int i = 0; i < n_values.size(); i++) {
       cudf::groupby::aggregation_request req;
       int col_index = n_values[i];
+      cudf::groupby_aggregation *agg =
+          dynamic_cast<cudf::groupby_aggregation *>(n_agg_instances[i]);
+      JNI_ARG_CHECK(env, agg != nullptr, "aggregation is not an instance of groupby_aggregation",
+                    nullptr);
+      std::unique_ptr<cudf::groupby_aggregation> cloned(
+          dynamic_cast<cudf::groupby_aggregation *>(agg->clone().release()));
+
       if (col_index == previous_index) {
-        requests.back().aggregations.push_back(n_agg_instances[i]->clone());
+        requests.back().aggregations.push_back(std::move(cloned));
       } else {
         req.values = n_input_table->column(col_index);
-        req.aggregations.push_back(n_agg_instances[i]->clone());
+        req.aggregations.push_back(std::move(cloned));
         requests.push_back(std::move(req));
       }
       previous_index = col_index;
@@ -2250,17 +2257,25 @@ JNIEXPORT jlongArray JNICALL Java_ai_rapids_cudf_Table_groupByScan(
 
     // Aggregates are passed in already grouped by column, so we just need to fill it in
     // as we go.
-    std::vector<cudf::groupby::aggregation_request> requests;
+    std::vector<cudf::groupby::scan_request> requests;
 
     int previous_index = -1;
     for (int i = 0; i < n_values.size(); i++) {
-      cudf::groupby::aggregation_request req;
+      cudf::groupby::scan_request req;
       int col_index = n_values[i];
+
+      cudf::groupby_scan_aggregation *agg =
+          dynamic_cast<cudf::groupby_scan_aggregation *>(n_agg_instances[i]);
+      JNI_ARG_CHECK(env, agg != nullptr,
+                    "aggregation is not an instance of groupby_scan_aggregation", nullptr);
+      std::unique_ptr<cudf::groupby_scan_aggregation> cloned(
+          dynamic_cast<cudf::groupby_scan_aggregation *>(agg->clone().release()));
+
       if (col_index == previous_index) {
-        requests.back().aggregations.push_back(n_agg_instances[i]->clone());
+        requests.back().aggregations.push_back(std::move(cloned));
       } else {
         req.values = n_input_table->column(col_index);
-        req.aggregations.push_back(n_agg_instances[i]->clone());
+        req.aggregations.push_back(std::move(cloned));
         requests.push_back(std::move(req));
       }
       previous_index = col_index;
```

2021-07-30 15:45 UTC, nvdbaranec commented
> 
> @nvdbaranec this breaks the java code/build. Could you apply this somewhat of a hack patch to this so we don't break the java code? I'll file a follow on issue to try and make the java APIs match what is being done for the C++ APIs.

Will do.  I'm in the process of adding the python changes as well.

2021-07-30 16:22 UTC, ttnghia commented on cpp/include/cudf/detail/aggregation/aggregation.hpp
> +    : aggregation{aggregation::VARIANCE}, std_var_aggregation{aggregation::VARIANCE, ddof}
You should only call constructor of the direct base class (`std_var_aggregation`). The class `std_var_aggregation` should be the one to call `groupby_aggregation{aggregation::VARIANCE}` which in turn calls `aggregation{aggregation::VARIANCE}`. The constructors should be called in chain.

2021-08-02 16:50 UTC, devavret commented on cpp/include/cudf/detail/aggregation/aggregation.hpp
> + * two template parameters. The first is a type dispatche `type`. The
Accidental change?

2021-08-02 17:23 UTC, devavret commented on python/cudf/cudf/_lib/aggregation.pyx
> +    cumsum = sum
Not needed for groupby. Only groupby scan

2021-08-04 17:10 UTC, revans2 approved these changes

2021-08-04 18:49 UTC, davidwendt requested changes
Looks good. Just need to fix a couple constructors I think.

2021-08-04 18:49 UTC, davidwendt commented on cpp/include/cudf/detail/aggregation/aggregation.hpp
> +    : aggregation{aggregation::STD}, std_var_aggregation{aggregation::STD, ddof}
```suggestion
    : std_var_aggregation{aggregation::STD, ddof}
```
Same for `var_aggregation` ctor as mentioned https://github.com/rapidsai/cudf/pull/8906/files#r680051532

2021-08-04 18:51 UTC, jrhemstad approved these changes

2021-08-06 03:48 UTC, davidwendt approved these changes
Looks like the virtual base class requires explicit ctor call from the final class ctor.

2021-08-18 14:15 UTC, galipremsagar commented on python/cudf/cudf/_lib/groupby.pyx
> +                raise
Can we now remove this todo since https://github.com/rapidsai/cudf/issues/7611 is resolved?

2021-08-18 14:15 UTC, galipremsagar commented on python/cudf/cudf/_lib/groupby.pyx
>              # https://github.com/rapidsai/cudf/issues/7611
This aswell.

2021-08-19 03:11 UTC, galipremsagar approved these changes

2021-08-19 03:18 UTC, ttnghia approved these changes

2021-08-19 09:21 UTC, devavret approved these changes

2021-08-19 14:12 UTC, nvdbaranec commented
@gpucibot merge

2021-08-19 14:12 UTC, merged