Fix concatenate empty structs
rapidsai/cudf pull request #8947
Opened 2021-08-04 04:05 UTC by sperlingxx

Signed-off-by: sperlingxx <lovedreamf@gmail.com>

Closes #8929

2021-08-04 04:45 UTC, ttnghia requested changes

2021-08-04 04:45 UTC, ttnghia commented on cpp/src/structs/copying/concatenate.cu
> +    }
```suggestion
  auto const total_length = !children.empty() ? 
                                          children[0]->size() : 
                                          std::accumulate(columns.begin(), columns.end(), size_type{0});
```

2021-08-04 04:47 UTC, ttnghia commented
In cudf PR, you don't have to add "Signed-off-by" in the PR description. Instead, add more true "description" for what the PR is doing.

2021-08-05 12:47 UTC, ttnghia commented
Rerun tests.

2021-08-05 13:03 UTC, ttnghia requested changes

2021-08-05 13:03 UTC, ttnghia commented on cpp/src/structs/copying/concatenate.cu
> +  auto accSizeFn          = [](size_type s, const column_view& c) { return s + c.size(); };
By cudf convention, we use `type const`.
```suggestion
  auto accSizeFn          = [](size_type s, column_view const& c) { return s + c.size(); };
```

2021-08-05 15:49 UTC, ttnghia approved these changes

2021-08-05 16:19 UTC, ttnghia commented on cpp/src/structs/copying/concatenate.cu
> +  auto const total_length = children[0]->size();
CIs fail: /src/structs/copying/concatenate.cu(60): error: "total_length" has already been declared in the current scope
```suggestion
```

2021-08-05 16:20 UTC, ttnghia commented on cpp/src/structs/copying/concatenate.cu
> +  auto accSizeFn          = [](size_type s, column_view const& c) { return s + c.size(); };
```suggestion
  auto const accSizeFn          = [](size_type s, column_view const& c) { return s + c.size(); };
```

2021-08-05 16:29 UTC, sperlingxx commented
@ttnghia Thanks for correcting my mistakes ^ ^

2021-08-05 16:38 UTC, sperlingxx commented on cpp/src/structs/copying/concatenate.cu
> +  auto const accSizeFn          = [](size_type s, column_view const& c) { return s + c.size(); };
```suggestion
  auto const accSizeFn   = [](size_type s, column_view const& c) { return s + c.size(); };
```

2021-08-05 16:39 UTC, sperlingxx commented on cpp/src/structs/copying/concatenate.cu
> +  auto const accSizeFn          = [](size_type s, column_view const& c) { return s + c.size(); };
```suggestion
  auto const accSizeFn    = [](size_type s, column_view const& c) { return s + c.size(); };
```

2021-08-06 02:24 UTC, hyperbolic2346 approved these changes

2021-08-06 06:40 UTC, sperlingxx commented
@gpucibot merge

2021-08-06 06:40 UTC, merged