use correct namespace in cuio code examples
rapidsai/cudf pull request #9037
Opened 2021-08-13 22:59 UTC by cwharris

2021-08-14 09:30 UTC, karthikeyann requested changes
check all files for similar change in this PR.

2021-08-14 09:30 UTC, karthikeyann commented on cpp/include/cudf/io/orc.hpp
> - *  auto result = cudf::read_orc(options);
other documentation string in this file still has `cudf::orc` usage. 
`cudf::write_`, `cudf::read_` also. Check all the edited files in this PR.

2021-08-19 03:22 UTC, ttnghia approved these changes
Please add PR description :smiley:

2021-08-19 05:12 UTC, cwharris commented
@ttnghia I was under the impression the title of the PR becomes part of the description...

2021-08-19 08:56 UTC, karthikeyann approved these changes

2021-08-19 09:24 UTC, devavret approved these changes

2021-08-19 16:28 UTC, cwharris commented
@gpucibot merge

2021-08-19 16:28 UTC, merged