Series `apply` method backed by masked UDFs
rapidsai/cudf pull request #9217
Opened 2021-09-10 18:58 UTC by brandon-b-miller

Depends on https://github.com/rapidsai/cudf/pull/9174

2021-09-15 14:35 UTC, shwina commented on python/cudf/cudf/core/udf/api.py
> +    # lowering to grab onto. Just a dummy function for us to
```suggestion
    # lowering to grab onto. Just a placeholder function for us to
```

https://developers.google.com/style/inclusive-documentation

2021-09-15 20:34 UTC, thomcom requested changes
Very cool contribution. Just a few bits in commentary.

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +def masked_arrty_from_np_type(dtype):
```suggestion
def masked_array_from_np_type(dtype):
```

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +        sig.append(masked_arrty_from_np_type(col.dtype))
```suggestion
        sig.append(masked_array_from_np_type(col.dtype))
```

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +        offsets.append(int64)
I'm curious about `offsets` being fixed to 64 bit? Is this a limitation of numba or something you're going to add?

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +    sig = void(*(sig + offsets + [int64]))
I do not like using the same `int64` for values inserted into `offsets` and also for the argument to `_kernel`.

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +    return kernel_template.format(**d)
fun!

2021-09-15 20:34 UTC, thomcom commented on python/cudf/cudf/core/udf/pipeline.py
> +            lcl,
What is an `lcl dict`?

2021-09-17 14:20 UTC, brandon-b-miller commented
@thomcom thank you for the review! would you mind moving your comments to https://github.com/rapidsai/cudf/pull/9174, this PR is just a minor set of diffs on top of that one. Hopefully I can address them there!

2021-09-29 18:07 UTC, brandon-b-miller commented
rerun tests

2021-09-29 21:37 UTC, brandon-b-miller commented
This is now ready for review.

2021-09-29 22:04 UTC, shwina approved these changes
This looks great to me!

2021-09-30 15:48 UTC, thomcom approved these changes

2021-10-01 15:07 UTC, brandon-b-miller commented
rerun tests

2021-10-01 15:33 UTC, galipremsagar approved these changes

2021-10-01 18:47 UTC, brandon-b-miller commented
@gpucibot merge

2021-10-01 18:47 UTC, merged