Fixing SubwordTokenizer docs issue
rapidsai/cudf pull request #9354
Opened 2021-10-01 16:39 UTC by mayankanand007

This PR deals with issue #9245 where in the nightly build docs, there is no link to `SubwordTokenizer`. 

Now:
![subword](https://user-images.githubusercontent.com/36782063/135656756-df469d3d-9db0-41f0-962d-93d59063ab85.JPG)

2021-10-01 16:46 UTC, galipremsagar requested changes
You'll also need to add an entry for `subword_tokenize` in `index.rst` for it to show up in docs: https://github.com/rapidsai/cudf/blob/branch-21.12/docs/cudf/source/api_docs/index.rst

The current changes will only allow it to show up in searches.

2021-10-01 16:55 UTC, mayankanand007 commented
Thanks for catching that, done!

2021-10-04 15:13 UTC, galipremsagar approved these changes

2021-10-04 15:13 UTC, galipremsagar commented
@gpucibot merge

2021-10-04 15:13 UTC, merged