Add offsets_begin/end() to strings_column_view
rapidsai/cudf pull request #9559
Opened 2021-10-29 14:26 UTC by davidwendt

Closes #9548 

Adds `offsets_begin()` and `offsets_end()` to `cudf::strings_column_view`. Also adds `chars_begin()` and `chars_end()` as well. The `offsets_begin()` and `offsets_end()` apply any sliced values (offset, size) from the parent.

Also changed a few source files where these new functions can be used.

2021-10-29 19:31 UTC, jrhemstad commented on cpp/include/cudf/strings/strings_column_view.hpp
> +   * The offsets child must be used to properly address
Maybe add an example, e.g.,
```
To access the first character of string `i` (accounting for a sliced column offset):
chars_begin() + *(offsets_begin() + i)
```

2021-11-01 14:48 UTC, jrhemstad reviewed
Any sanity checking tests we want to add?

2021-11-01 14:57 UTC, davidwendt commented
> Any sanity checking tests we want to add?

Do you mean like `CUDF_EXPECTS` checks for valid values? Or do you mean a gtest?

2021-11-02 00:46 UTC, vyasr approved these changes
CMake approval.

2021-11-02 02:31 UTC, harrism requested changes
Couple of doc issues.

2021-11-02 02:31 UTC, harrism commented on cpp/include/cudf/strings/strings_column_view.hpp
> +   * This does not applies the offset of the parent.
```suggestion
   * This does not apply the offset of the parent.
```

2021-11-02 02:31 UTC, harrism commented on cpp/include/cudf/strings/strings_column_view.hpp
> +   * This automatically applies the offset of the parent.
Why does chars_end apply the offset of the parent if `chars_begin()` does not?  I think maybe this is just a copy paste error in the docs?

2021-11-03 01:50 UTC, harrism approved these changes

2021-11-03 13:55 UTC, jrhemstad approved these changes

2021-11-03 13:56 UTC, jrhemstad commented
@gpucibot merge

2021-11-03 14:00 UTC, davidwendt commented
rerun tests

2021-11-03 20:02 UTC, merged