Spell check fixes
rapidsai/cudf pull request #9682
Opened 2021-11-15 06:07 UTC by karthikeyann

Regular spell check fixes in comments and docs.

2021-11-15 13:44 UTC, galipremsagar approved these changes

2021-11-15 18:49 UTC, charlesbluca requested changes

2021-11-15 18:49 UTC, charlesbluca commented on python/cudf/cudf/tests/test_datetime.py
> +# licudf doesn't respect timezones
```suggestion
# libcudf doesn't respect timezones
```

2021-11-15 18:51 UTC, charlesbluca approved these changes

2021-11-15 19:16 UTC, karthikeyann commented
rerun tests

2021-11-16 15:22 UTC, karthikeyann commented
rerun tests

2021-11-17 07:55 UTC, karthikeyann commented
rerun tests

2021-11-18 07:43 UTC, karthikeyann commented
rerun tests

2021-11-18 20:36 UTC, karthikeyann commented
@gpucibot merge

2021-11-18 20:36 UTC, merged